### ISSUE TITLE
Show progress of uncompressing recovery image

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#105]
Uncompressing the ZIP file is a pure-python implementation and we can integrate this in the existing progress dialog. Also the downloading should go into the existing progress dialog.

I would use this distribution, so that the download itself is visually identifiable:
- Download: 50%
- Uncompressing: 45%
- Extraction: 5%

**Comment by michaelarnauts** [comment]
Can all three steps be tracked progress-wise? Maybe 3 separate steps can be a better solution then and have each step be from 0 to 100%. On a really slow connnection and a fast cpu, the uncompressing will take a lot more time. Or a fast connection and a rpi that takes more time do decompress?

Like "Downloading... (1/3)", "Extracting... (2/3)", ...

**Comment by dagwieers** [comment]
It is like that now, but it doesn't look good.
A single progress bar gives a much better indication, despite it not being lineair in time (which isn't the case for downloading either..)

**Comment by michaelarnauts** [comment]
Hmm, okay. It's just that the 50/45/5 seperarion is a bit strange then.

**Comment by dagwieers** [comment]
It is arbitrary, it is always arbitrary since both the download as the uncompression depend on external factors and cannot be compared. So we shouldn't even bother.

But having the download finish half-way gives a visual indication (especially if you learned this) when the download finishes. And the extraction is just a matter of seconds, but it consists of a few steps, so there you go.

**Comment by dagwieers** [comment]
This is nearly impossible with the python zipfile implementation. The only possibility is that we monitor the destination file while extracting in a separate thread. And TBH that is not something I think we should pursue.

**Comment by dagwieers** [comment]
We need to show some progress here. My proposal would be to implement this 50:50 with downloading. And for uncompressing I would advance 5% of the remaining bar every 10 seconds.
That would mean it would never go to 100%, but do:
- After 5 secs: 5% (5% of 100%)
- After 10 secs: 9.75% = 5% + 4.75% (5% of 95%)
- After 15 secs: 14.26% = 9.75% + 4.51% (5% of 90.25%)
- After 20 secs: 18.55% = 14.26% + 4.29% (5% of 85.74%)
- After 25 secs: 22.62% = 18.55% + 4.07% (5% of 81.45%)
- After 30 secs: 26.49% = 22.62% + 3.87% (5% of 77.38%)
- After 60 secs: 45.96%
- After 120 secs: 70.80%
- After 180 secs: 84.22%
- After 240 secs: 91.47%
- After 300 secs: 95.39%
- After 360 secs: 97.51%  &larr; After 5 minutes it may appear at a standstill
- After 420 secs: 98.65%

**Comment by michaelarnauts** [comment]
Isn't a better solution to do this in the background with a ProgressDialogBG? You don't need to have a progress bar there, and that is kind of the situation here. Think like "Windows update" in the background. Combined with the "safe extract to a different location then the actual libs (see @dagwieers his proposal in #218 )", this could provide a nice way to do the update without having the issue that it is interrupted.

**Comment by dagwieers** [comment]
@michaelarnauts No, we cannot just do it in the background because the number one use-case today is that the user starts playback of a video, then has to wait until everything is finished to have the video started. If there is no dialog, the user doesn't know the video will be started, and he might be starting a second or third interaction.

We had this problem in the past because there was no progress dialog, only a window that said "This will be happening in the background. [OK]" and then a spinning icon. And users would be cancelling without knowing/understanding. So we definitely do not want the user to do anything while downloading/uncompressing, and for ARM (which is the real problem scenario) the system is unusably slow anyway during this process.

**Comment by dagwieers** [comment]
My preferred workflow is that we don't ask to update every X (31) days, but only go through this process when playback actually failed because of Widevine issues. Or even better, periodically test Widevine playback in the background and when it stops working because of Widevine CDM issues, perform these actions in the background.

But that would require support in **inputstream.adaptive** to detect the cause of playback issues and send out an event, or test Widevine playback.

**Comment by dagwieers** [comment]
BTW We could remove the cancel button from the progress dialog, but I think the user should have the possibility to cancel it at any time. The problem is not that the user cancelled, the problem is that he cancelled because it takes too long and thinks it is stuck. And that cancelling may corrupt a working system. So we need to fix those two things.
