### ISSUE TITLE
Successive installation crashes inputstream.adaptive

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#106]
When installing Widevine CDM twice in a single Kodi session, it triggers a crash in **inputstream.adaptive**.

**Comment by dagwieers** [comment]
I reported this at: peak3d/inputstream.adaptive#309

**Comment by pumpkinbum** [comment]
I can not upload input.streamadaptive from either repozitory or zip file for kodi leila running ubuntu focal fossa and/or change widewine setting
