### ISSUE TITLE
ldd Error with Libreelec 9

### ISSUE THREAD

**Issue by gismo112** [emilsvennesson/script.module.inputstreamhelper#11]
Hi @emilsvennesson,

we have another Problem with version 0.3.1:

`13:54:43.545 T:3370140560   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'subprocess.CalledProcessError'>
                                            Error Contents: Command '['ldd', '/storage/.kodi/cdm/libwidevinecdm.so']' returned non-zero exit status 1
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 2541, in <module>
                                                PlayVideo(args.get('name'), args.get('asin'), args.get('adult'), int(args.get('trailer', '0')), int(args.get('selbitrate', '0')))
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 1013, in PlayVideo
                                                playable = IStreamPlayback(asin, name, trailer, isAdult, extern)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 1130, in IStreamPlayback
                                                if not inputstream_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 712, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 690, in _check_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 610, in _check_widevine
                                                if self._missing_widevine_libs():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 572, in _missing_widevine_libs
                                                output = subprocess.check_output(cmd)
                                              File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
                                            CalledProcessError: Command '['ldd', '/storage/.kodi/cdm/libwidevinecdm.so']' returned non-zero exit status 1
                                            -->End of Python script error report<--`

I use Libreelec 9 / Kodi18 / Custom-Build on a Ondroid-C2

Here the compete Debug-Log:
[ix.io/EWE](url)

Edit: Here the Console-Output with ldd command:
`LibreELEC:~ # ldd /storage/.kodi/cdm/libwidevinecdm.so
ldd: $warning: you do not have execution permission for `/storage/.kodi/cdm/libwidevinecdm.so'
/usr/bin/ldd: eval: line 1: /storage/.kodi/cdm/libwidevinecdm.so: Permission denied
LibreELEC:~ #
`

**Comment by emilsvennesson** [comment]
Hi! That's... interesting. Can you run `ldd /storage/.kodi/cdm/libwidevinecdm.so` in the terminal?

**Comment by gismo112** [comment]
Yes :-)

`LibreELEC:~ # ldd /storage/.kodi/cdm/libwidevinecdm.so
ldd: $warning: you do not have execution permission for `/storage/.kodi/cdm/libwidevinecdm.so'
/usr/bin/ldd: eval: line 1: /storage/.kodi/cdm/libwidevinecdm.so: Permission denied
`

**Comment by gismo112** [comment]
When i give "777" Permisssions, then it works:

`LibreELEC:~ # chmod 777 /storage/.kodi/cdm/libwidevinecdm.so
LibreELEC:~ # ldd ~/.kodi/userdata/addon_data/script.module.inputstreamhelper/cdm/libwidevinecdm.so
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0xf719e000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xf7059000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0xf7046000)
        librt.so.1 => /usr/lib/librt.so.1 (0xf702f000)
        libnss3.so => /usr/lib/libnss3.so (0xf6f3e000)
        libnssutil3.so => /usr/lib/libnssutil3.so (0xf6f0e000)
        libnspr4.so => /usr/lib/libnspr4.so (0xf6edb000)
        libm.so.6 => /usr/lib/libm.so.6 (0xf6e5c000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xf6e2f000)
        libc.so.6 => /usr/lib/libc.so.6 (0xf6cf9000)
        /lib/ld-linux-armhf.so.3 (0xf71c6000)
        libplc4.so => /usr/lib/libplc4.so (0xf71ea000)
        libplds4.so => /usr/lib/libplds4.so (0xf71e6000)`

**Comment by emilsvennesson** [comment]
Does it work with 755?

**Comment by gismo112** [comment]
Yes, can confirm.

`LibreELEC:~ # chmod 755 /storage/.kodi/cdm/libwidevinecdm.so
LibreELEC:~ # ldd /storage/.kodi/cdm/libwidevinecdm.so
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0xf7267000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xf7122000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0xf710f000)
        librt.so.1 => /usr/lib/librt.so.1 (0xf70f8000)
        libnss3.so => /usr/lib/libnss3.so (0xf7007000)
        libnssutil3.so => /usr/lib/libnssutil3.so (0xf6fd7000)
        libnspr4.so => /usr/lib/libnspr4.so (0xf6fa4000)
        libm.so.6 => /usr/lib/libm.so.6 (0xf6f25000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xf6ef8000)
        libc.so.6 => /usr/lib/libc.so.6 (0xf6dc2000)
        /lib/ld-linux-armhf.so.3 (0xf728f000)
        libplc4.so => /usr/lib/libplc4.so (0xf72b3000)
        libplds4.so => /usr/lib/libplds4.so (0xf72af000)`

**Comment by emilsvennesson** [comment]
@gismo112 Could you please retry with the latest master?

**Comment by gismo112** [comment]
I testing it :-)

**Comment by gismo112** [comment]
@emilsvennesson  Yes, the Problem is solved. I changed the Permissions before test to "644"
and now there are "755" 👍
