### ISSUE TITLE
Help test and translate InputStream Helper v0.4.0

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#113]
We would like to have the help of past and new testers/translators to get InputStream Helper tested and translated to the existing (and potentially) new languages.

InputStream Helper currently ships with translations for:
- ~Dutch **nl_nl** -- *@mediaminister, @basrieter, @dnicolaas*~ #117 #121
- ~German **de_de** -- *@flubshi, @horstle, @asciidisco*~ #120 #125
- ~Greek **el_gr** -- *@Twilight0, @paraskevasleivadaros*~ #124 #127
- ~Italian **it_it** -- *@pinoelefante*~ #136 
- ~Russian **ru_ru** -- *@vlmaksime*~ #118 

New languages:
- Swedish **sv_se** -- *@emilsvennesson* #126 

Please translate the untranslated strings. We like to release by 2019-09-01.
Any translations we get after that cutoff date will go into v0.4.1 or v0.5.0 (whichever comes first.

**Comment by basrieter** [comment]
Working on the Dutch now

**Comment by Twilight0** [comment]
Done the greek update. Cheers.

**Comment by dagwieers** [comment]
We have everything translated in time.
Now we need more people to test the master branch.

**Comment by mediaminister** [comment]
I'm busy testing.

**Comment by mediaminister** [comment]
Tested on Windows10 Kodi 19 python3 , Windows10 Kodi 18.3 python 2, LibreELEC 8.2.5, LibreELEC 9.0.2 and Android Kodi 18.3 and found no problems.

**Comment by dagwieers** [comment]
I think we're good to go. The known issues we can fix in the next release.
I will release v0.4.0 this evening and push it to xbmc/repo-plugins

**Comment by mediaminister** [comment]
Shouldn't you push to xbmc/repo-scripts because the name begins with script? 

Multiple extension points or plugin-like functionality seems no problem for getting merged in xbmc/repo-scripts, for instance https://github.com/xbmc/repo-scripts/pull/1134

**Comment by dagwieers** [comment]
Yup, that was a thinko :-) I wouldn't have missed though, building on top of what already exists.

**Comment by dagwieers** [comment]
InputStream Helper v0.4.0 has been released: https://github.com/emilsvennesson/script.module.inputstreamhelper/releases/tag/v0.4.0

**Comment by dagwieers** [comment]
Thanks everybody! The new release has been submitted to Kodi:
https://github.com/xbmc/repo-scripts/pull/1140

**Comment by dagwieers** [comment]
We have created translator-teams in the @add-ons organization at: https://github.com/orgs/add-ons/teams/translators

This will help us translate Kodi add-ons to more languages in the future using less effort.
If you are willing to help out, join a language team!
