### ISSUE TITLE
ERROR: Unable to find plugin script.module.inputstreamhelper

### ISSUE THREAD

**Issue by horstle** [emilsvennesson/script.module.inputstreamhelper#132]
Hi, this issue can probably be closed right away, but I still thought I should report this:

I did a clean install of an addon relying on inputstreamhelper and updated the helper to the master branch right afterwards. Then I tried to run it via the settings page, but got the error in the title.
The addon I installed was able to run it and a restart of Kodi immediately fixed this, so I guess it's more of a Kodi issue and can be closed (here).

System is Kodi 18.3 from the official Repo on Ubuntu 18.04.3.

**Comment by dagwieers** [comment]
I would like to get a reproducer of this to understand what is happening.

**Comment by horstle** [comment]
Ok, so what I did was basically:

* On Ubuntu 18.04.3 install Kodi via `sudo apt install kodi`
* Install an addon with which inputstreamhelper will be installed, in my case Amazon VOD (this step might not be necessary)
* Download and install the zip of the master branch from Github
* Open the inputstreamhelper settings
* Try running either (re)install or remove. No matter which, you will see no reaction and the above error will be logged (and nothing more).

**Comment by dagwieers** [comment]
@horstle It would be interesting to see if modifications to `addon.xml` would influence this behavior.

**Comment by horstle** [comment]
The problem seems to be that script.module.routing does not install correctly. If I go to
settings > system > add-ons > manage dependencies > Plugin routing
and click on update, it works afterwards.

I did also try this by only installing the ZIP of 0.3.5 (instead of an addon relying on inputstreamhelper) and immediately afterwards the ZIP of master and could reproduce the same thing.
Only installing master without any previous install seems to correctly install script.module.routing.

**Comment by horstle** [comment]
My guess is that Kodi might not reload PYTHONPATH in this situation (only after a manual update).

**Comment by dagwieers** [comment]
I have seen that exact issue before, modules that have been installed just recently do not end up in PYTHONPATH and cause an import error.

**Comment by horstle** [comment]
By the way, I was able to reproduce this in LibreELEC 9.1.002 on an RPi3, too.

**Comment by mediaminister** [comment]
@horstle Can you confirm this is fixed now in the master branch?

**Comment by horstle** [comment]
Yes, confirmed. Closing this.
