### ISSUE TITLE
Fails if kernel has block device loop as module ...

### ISSUE THREAD

**Issue by mkreisl** [emilsvennesson/script.module.inputstreamhelper#14]
and module is not already loaded

see PR https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/13

**Comment by emilsvennesson** [comment]
@mkreisl Could you please try the latest master and confirm that it works?

**Comment by mkreisl** [comment]
Sure, will do it this evening

**Comment by mkreisl** [comment]
Checked and everything is working 👍 

Thanks for your help and fast response

**Comment by mkreisl** [comment]
@emilsvennesson 

Please don't forget to update your changelog

**Comment by emilsvennesson** [comment]
@mkreisl Great! Thanks a lot for your PR and for helping out with the testing. :-)
