### ISSUE TITLE
add french language

### ISSUE THREAD

**Issue by brunoduc** [emilsvennesson/script.module.inputstreamhelper#158]
I created the .po file if you want.

[strings.po.txt](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/3573852/strings.po.txt)

**Comment by dagwieers** [comment]
Yes, please. Can you create a PR for this ?

**Comment by brunoduc** [comment]
@dagwieers
I don't how create a PR for this ...

**Comment by dagwieers** [comment]
You can do this through the GitHub interface.
1. Go to https://github.com/emilsvennesson/script.module.inputstreamhelper/new/master/resources/language
2. Create a new file named: **resource.language.fr_fr/strings.po**
3. Put the content in that file.

If anything is wrong, I can fix your PR and you still get credited for it ;-)

**Comment by horstle** [comment]
He already did. #159
