### ISSUE TITLE
Widevine CDM version selection and rollback support

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#165]
This functionality has various aspects that are intertwined with:

- The ability to backup Widevine CDM versions (up to 5, configurable) when updating
- The ability to install/rollback a Widevine CDM version of your choice (from backup, or online)
- ~The ability to configure the interval to check for Widevine CDM updates~ #173
- The ability to pin to a specific version (so a way to disable updating Widevine)

We would also like to have a way to detect when Widevine playback fails (see #69), in that case pinning to a specific Widevine CDM would get overruled when it fails to work.

These features were listed in [the Ideas in our Wiki](https://github.com/emilsvennesson/script.module.inputstreamhelper/wiki/Ideas#settings)

A rationale for giving this kind of control to the user is available from issues like:
- [Incompatibility with newest Widevine on ARM systems (netflix#465)](https://github.com/asciidisco/plugin.video.netflix/issues/465)
- [Stuttering playback of streams using new widevine (inputstream.adaptive#305)](https://github.com/peak3d/inputstream.adaptive/issues/305)

**Comment by Smeulf** [comment]
I really like the pin idea, and rollback!

Hope you can implement it soon :)

If I may ask for an extra option: give a way to save previous version on a configurable path, ie nfs or SMB, because it's a lot to keep on some Raspberry Pi (~2gb). That would be awesome.

Thanks!

**Comment by dagwieers** [comment]
The implementation requires us (on ARM) to also keep track of the Chrome OS version in relation to the Widevine version. Since multiple Chrome OS releases ship with the same Widevine image (and we only know after extraction), recording which Widevine ships with what Widevine version will offer us a table to select the right Chrome OS image for a given Widevine release.

We may want to ship our own table as a reference, and InputStream Helper will continue to register newer versions going forward. I think this offers the best user experience on ARM.

**Comment by Smeulf** [comment]
> From what I understood, not the full 2GB image is kept. The widevine files are extracted and the image is removed again.

So obvious and space saving!

**Comment by the-isz** [comment]
Would be great to at least have an "Ignore" option when inputstreamhelper detects an outdated widevine version.

You probably already know, but just in case:

Right now, on ARM, you can't use plugins that use inputstreamhelper even though the outdated widevine version (4.10.1440.18) is able to play the streams. You only have the options "download an update that doesn't exist" and "don't even try to play the video".

I found that disabling inputstreamhelper is a workaround for the time being.

P.S.: Thank you very much for all of your great work!

**Comment by horstle** [comment]
@the-isz Please have a look at #191 if that somewhat relates to your situation. If I understand correctly you get an update message every time you try to play something? Not only each 14/31/... days?

**Comment by horstle** [comment]
I don't really understand what would be the difference between "pinning" to a specific version and disabling after installing that version.

**Comment by dagwieers** [comment]
In fact version 4.10.1440.18 is the latest available Widevine version.

**Comment by the-isz** [comment]
@horstle Yes, exactly, I'm getting a popup telling me that a newer widevine version is needed to play the content every time I try to play a video. Then, I can either start the update or cancel. If I choose to cancel, the video isn't played.

@dagwieers Oh, OK. I thought I had read that there were 4.10.1440.19 versions out there for other platforms (e.g. x64) and I also saw that version in [versions.txt](https://dl.google.com/widevine-cdm/versions.txt). But if you say that .19 is the latest available then we might even have another problem here. Either:

1. inputstreamhelper is trying to update although the most recent version is already installed or
2. the fact that I'm manually updating widevine is confusing inputstreamhelper

FYI: I'm manually updating inputstreamhelper because I don't have enough disk space on my raspberry to download and unpack the Chrome OS recovery images.

**Comment by horstle** [comment]
@the-isz There is a new version called .19, but it's identical to the .18 version. That's one of the reasons it's trying to update. The other one is that it still checks the widevine_config.json to see which version is installed, which you presumably don't change (so it's your 2. assumption).

There is a fix for the disk space problem  in master, which should be released soon, but you're welcome to test now by downloading the repo as a .zip and installing manually.

**Comment by Smeulf** [comment]
> FYI: I'm manually updating inputstreamhelper because I don't have enough disk space on my raspberry to download and unpack the Chrome OS recovery images.

If I'm correct, then InputStream Helper thinks you didn't install the last version. There's no binaries check, just it compares what it gets in its settings.xml file.

If you update manually, you should also update the settings.xml file so it matches the current version installed.

**Comment by the-isz** [comment]
@horstle I actually manually update widevine_config.json as well.
@Smeulf Can you give me more details which settings.xml to update and what to update it with? Until now, libwidevinecdm.so and widevine_config.json used to be sufficient.

**Comment by Smeulf** [comment]
> Can you give me more details which settings.xml to update and what to update it with? Until now, libwidevinecdm.so and widevine_config.json used to be sufficient

@the-isz Sorry, just checked again, and I was wrong thinking the current version is in settings.xml.

**Comment by dagwieers** [comment]
With PR #193 merged we can close this issue. Any issues with the current master branch should be opened as a new issue. Please test !
