### ISSUE TITLE
Widevine extraction on ARM now needs 2.7GiB

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#168]
What we anticipated in #62 finally happened. The newer Chrome OS images are larger in size (older Chrome OS devices are no longer supported). Unfortunately the newer Chrome OS images do not include a newer Widevine, which is still ~v4.10.1440.19~ v4.10.1440.18. (in disguise).

This means the newer images available to us are larger in size and **now require 2.7GB of free disk space** (600MiB for the ZIP file, and 2.1GiB for the extracted image).

It is safe to say we expect at least an 8GB disk nowadays for Kodi (for Widevine playback) if we want to be future-proof.

```
Debug: [script.module.inputstreamhelper-2.3.4]: Find best ARM image to use from recovery.conf
Debug: [script.module.inputstreamhelper-2.3.4]: BIG (2139677845) is smaller than BOB (3373816646)
Debug: [script.module.inputstreamhelper-2.3.4]: JERRY (12239.92.1) is newer than BIG (12239.92.0)
Debug: [script.module.inputstreamhelper-2.3.4]: MICKEY (2871488773) is smaller than JERRY (3359473879)
```

A solution to not need storage for both the ZIP file and the extracted image would be something like #72 (this would only require 600MiB for download+extraction), or hope that Google would release the ARM libraries separately like they do for other architectures.

**Comment by dagwieers** [comment]
I regularly run the following script to check if perhaps the Widevine library is not released for ARM as well.

```python
#!/usr/bin/python
# coding: utf-8

from __future__ import absolute_import, division, unicode_literals
import sys
import requests

if len(sys.argv) > 1:
    version = sys.argv[1]
else:
    version = '4.10.1440.19'

archs = ['aarch32', 'aarch64', 'aarch64_be', 'arm', 'arm32', 'arm64', 'arm7', 'arm8', 'armv4', 'armv6', 'armv7', 'armel', 'armhf', 'armv71', 'armv7l', 'armv8', 'ia32', 'x64', 'ARM', 'ARMv4', 'ARMv7', 'ARMv8', 'NEON', 'neon', 'uarm']
oses = ['android', 'chrm', 'chos', 'chrome', 'ChromeOS', 'chromeos', 'chrome_os', 'chromiumos', 'chromium-os', 'chronos', 'chros', 'cos', 'cros', 'crosrec', 'mac', 'linux', 'win', 'ChromeCDM', 'chromium', 'posix']
url = 'https://dl.google.com/widevine-cdm/{version}-{os}-{arch}.zip'

for arch in archs:
    for os in oses:
        zipfile = url.format(version=version, arch=arch, os=os)
        r = requests.head(zipfile)
        if r.status_code == 404:
            print('   %s -> %s %s' % (zipfile, r.status_code, r.reason))
        else:
            print('\033[1;37m** %s -> %s %s\033[0;39m' % (zipfile, r.status_code, r.reason))
```

**Comment by dagwieers** [comment]
PR #21 may soothe the pain.

**Comment by floyd-fuh** [comment]
May I suggest as well that when it is detected that there is not 2.7GB free space, you suggest that the user can choose a different temporary path? Because I have (as many other users I suppose) a small SD card but a large disc attached to the device. Unfortunately a simple trick symlinking `~/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp` to an empty directory on the large disc did not work, as there seems to be an rmtree call somewhere and the exception `OSError cannot call rmtree on a symbolic link` is thrown and of course hardlinks do not work across devices.

**Comment by dagwieers** [comment]
@floyd-fuh Like I mentioned in the previous comment, PR #21 ?

**Comment by floyd-fuh** [comment]
right, sorry, missed that one

**Comment by dagwieers** [comment]
Going to close this again. Only Google can help us here by distributing Widevine as a separate ZIP for ARM as they do for other platforms/architectures.

**Comment by dagwieers** [comment]
Things improved, but it depends on what Google is offering. Now **2.0GiB** thanks to a newer KITTY image.
> Debug: [script.module.inputstreamhelper] Find best ARM image to use from the Chrome OS recovery.conf
> Debug: [script.module.inputstreamhelper] ELM (3314702422) is smaller than BOB (3463197456)
> Debug: [script.module.inputstreamhelper] EXPRESSO (2947171636) is smaller than ELM (3314702422)
> Debug: [script.module.inputstreamhelper] KITTY (2156811608) is smaller than EXPRESSO (2947171636)
> YESNO: [Information] Due to distribution rights, Widevine CDM has to be extracted from a Chrome OS recovery image. This process requires **at least 2.0GiB of free disk space**. Do you wish to continue?
```
