### ISSUE TITLE
Make inputstream configurable

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#177]
Currently we have a hard-coded mapping between input-format and inputstream plugin. And this makes sense because there currently are only 2 inputstream plugins (**adaptive** and **rtmp**) however in the future it is likely alternative inputstream implementations exists.

So rather than make this hard-coded, we could allow the user to select what inputstream plugin is used for what input-format. This is possible using:
```xml
<setting label="32111" type="addon" id="is_mpd" default="inputstream.adaptive" addontype="inputstream"  multiselect="false"/>
<setting label="32112" type="addon" id="is_hls" default="inputstream.adaptive" addontype="inputstream"  multiselect="false"/>
<setting label="32113" type="addon" id="is_ism" default="inputstream.adaptive" addontype="inputstream"  multiselect="false"/>
<setting label="32114" type="addon" id="is_rtmp" default="inputstream.rtmp" addontype="inputstream"  multiselect="false"/>
```

Even if we don't want to make this configurable (yet), we could add this as invisible settings until it becomes useful.

This would make config.py a little less relevant.

**Comment by emilsvennesson** [comment]
I'm not a fan of this idea. Right now, there's really no reason to allow the user to choose which add-on to use because there is only one option that will work. 

This would make sense to me if there were multiple add-ons supporting one protocol, which may happen in the future, but I don't see the benefit of this right now.

**Comment by emilsvennesson** [comment]
I just saw your edit about making it a hidden setting. That's completely fine with me. :-)

**Comment by dagwieers** [comment]
> I just saw your edit about making it a hidden setting. That's completely fine with me. :-)

It would indeed be moving this out of *config.py* into *settings.xml*. The goal being that we get rid of *config.py* (as a config file) into e.g. *data.py* (a datastore with fixed mappings).

Relates to #94

**Comment by emilsvennesson** [comment]
@dagwieers Sounds good to me. config.py has always been intended as an internal dictionary and not for users to edit themselves. The naming of the file was pretty stupidly thought out... 😬️

**Comment by dagwieers** [comment]
Revisit later.
