### ISSUE TITLE
[Feature Request] Custom path for tmp

### ISSUE THREAD

**Issue by Gaet81** [emilsvennesson/script.module.inputstreamhelper#20]
Hello,

Will it be possible to set a custom path to the tmp folder?

On RPi the installation request 1.9gb so it's quiet extensive when you are on a SD card.
I've tried to make a symbolic link to an external drive but the plugin use rmtree in the clean function and rmtree doesn't work on symbolic link...

Gaet81

**Comment by horstle** [comment]
Hi,

I created an option to do so here:

https://github.com/horstle/script.module.inputstreamhelper/tree/custom_path

If you want to you can try it out. I just tested it and found no errors. It asks for a directory if there is not enough space.

If it works for you and @emilsvennesson  is fine with it, I'll create a PR.

**Comment by emilsvennesson** [comment]
Hi!

This is definitely a good idea and would be a nice enhancement. 

@horstle A PR for this would be nice indeed. :-)

**Comment by Gaet81** [comment]
Hello,

I have finally some time to give you feedback.
I've tested on 3 differents harddrive and it hasn't worked...
It seems that losetup is failing but don't know why...I've made a which and the losetup cmd exists 

which losetup
/usr/bin/losetup

The debug log is here:
https://framabin.org/?01370dfcdb2cff38#ep+48GPObOzIP5wRIlCorMG0xkdL4hVYREMOFyByNd8=

**Comment by horstle** [comment]
There seems to be a problem with the sudo command. Did you change anything else on your system?

**Comment by emilsvennesson** [comment]
@Gaet81 The script needs to be able to run sudo without entering a password which is the default in most Raspberry Pi distros. That doesn't seem to be the case in Arch Linux though. :open_mouth:

**Comment by Gaet81** [comment]
really? how secure is that? Anyway I suppose I will need to make a viduso and update it then.
I'm not at home but as soon as I'm back I'm testing this.
________________________________
De : emilsvennesson <notifications@github.com>
Envoyé : mercredi 23 mai 2018 20:45
À : emilsvennesson/script.module.inputstreamhelper
Cc : Gaet81; Mention
Objet : Re: [emilsvennesson/script.module.inputstreamhelper] [Feature Request] Custom path for tmp (#20)


@Gaet81<https://github.com/Gaet81> The script needs to be able to run sudo without entering a password which is the default in most Raspberry Pi distros. That doesn't seem to be the case in Arch Linux though. 😮

**Comment by horstle** [comment]
I guess passwordless sudo is considered safe enough, as long as you're not reachable from the internet. You can even ssh into Libreelec as root with default password "libreelec", it just assumes you're behind a good-enough firewall.

Anyways, it should probably be possible to implement using the password if necessary with xbmcgui.Dialog.input and Popen.communicate? Maybe it could check whether the password is needed with "sudo -n true".

But I guess this should be discussed in a new issue, if wanted.

**Comment by Gaet81** [comment]
Hello,

It was indeed due to the sudo.
I've know been able to install widivine!

Thanks for your help.
probably that an implementation using the password might be needed a more global availability otherwise I guess that adding a note in the readme saying that sudo need to work without entering a password should be enough...

I think you can merge the PR from @horstle I haven't found any other issue.

Thanks for this great module!

**Comment by leosmeira** [comment]
You could open a prompt to select the external disk to be used as the temporary directory when there is no space on the local disk.

**Comment by leosmeira** [comment]
Has a pull request:

https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/21

**Comment by horstle** [comment]
That's exactly what my commit does, as I explained in the first comment. It asks for any directory, which can be on an external disk or different partition.

**Comment by dagwieers** [comment]
We finally merged #21. It has been a long ride. Thanks to @horstle for his commitment and patience.
