### ISSUE TITLE
inputstreamhelper not found

### ISSUE THREAD

**Issue by AlleSchonWeg** [emilsvennesson/script.module.inputstreamhelper#203]
Hi,
i'm trying to access the inputstreamhelper settings, but i can't find the addon. If i search in the addon manger for "inputstream helper" nothing is found or if i list all addons.
I use latest (26.09.) milhouse rpi3 libreelec build. But i'm sure it's installed, because i can start dazn and other addons. I also checked /storage/.kodi/addons/script.module.inputstreamhelper folder.

**Comment by dagwieers** [comment]
That is how Kodi deals with 'script.module' plugins. You can only access them by opening the **Information** pane of an add-on that uses it, and go to the **Dependencies**. There you can click on **InputStream Helper**.

If you have a more recent version (v0.4.0+) you will find the InputStream Helper in your program add-on listing.

**Comment by AlleSchonWeg** [comment]
Hi, 
thank you. I found it in the DAZN AddOn Dependencies. But no entry in the program AddOn listing.
i have version 0.4.2. No newer version available in the kodi repository.

**Comment by dagwieers** [comment]
@AlleSchonWeg It should be in the main Add-ons view under Program add-ons. But maybe this is specific to the skin used. My experience is purely based on Estuary.

Although we encourage add-on developers using InputStream Helper to add an entry to their add-on settings for users to find the settings more easily.
https://github.com/emilsvennesson/script.module.inputstreamhelper/wiki/Integration#integrating-in-your-add-on-settings

**Comment by AlleSchonWeg** [comment]
Hi,
i never changed the skin. I checked and it's Estuary, But no Inputstream Helper AddOn in Program AddOns and no AddOn in All view.

**Comment by dagwieers** [comment]
What version of Kodi are you using?

**Comment by AlleSchonWeg** [comment]
Kodi 19. This version: https://forum.kodi.tv/showthread.php?tid=343068&pid=2888099#pid2888099

**Comment by dagwieers** [comment]
So I tested on Kodi 18.4, Kodi 19 Alpha3 and the latest Kodi nightly build and after some troubleshooting it appears my systems are *tainted*. It appears only in the Add-ons Program section if you have tested development versions. So I guess you are right.

Starting from v0.4.3 (I think) it will start to appear in the Program Add-ons, I think. Can't be too sure because I no longer trust what I see on my systems :-)

**Comment by dagwieers** [comment]
In any case, pure script.module plugins are hidden on purpose by Kodi, so how it appears is outside of the scope of this plugin. Even if it does affect us, hence our recommendation to add-on developers to reference our settings from their add-on settings.
