### ISSUE TITLE
Widevine CDM install crashing on ARM

### ISSUE THREAD

**Issue by GitUser4711** [emilsvennesson/script.module.inputstreamhelper#210]
During extraction (according to dialog) of the downloaded recovery image, process crashes. Log see attachement. Traced it down to the extraction run through _run_cmd(), but no idea where to go from there...

[error.txt](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/3722098/error.txt)

InputStream Helper 0.4.3 (0.4.2 previously also failed)
Kodi 18.2 Leia from Raspbian Stretch official repository
Raspberry Pi 3b on Raspbian Stretch, latest updates/upgrades from official repository

Let me know in case you require additional information. Thanks!

**Comment by GitUser4711** [comment]
I figured out the root cause. On a regular Linux system (so **not** LibreElec, OSMC, etc.), your user running Kodi might not have the right to use `sudo` command. In that case your agreement with the addon dialog ("plugin will use root commands x , y ,z") does not help and the related commands, mainly required for mounting the downloaded Chrome OS image, will fail.
You can work around this by adding the three commands mentioned in the respective addon dialog to your `etc/sudoers` file for the user running Kodi.

You might want to add a specific error message or at least remove the encoding issue from the current one so that the error message points in a more helpful direction.

**Comment by mediaminister** [comment]
Unicode problems should be fixed in version 0.4.3, please provide a full debug log from version 0.4.3

**Comment by mediaminister** [comment]
@GitUser4711 Can you try this fix: 
[script.module.inputstreamhelper-0.4.3-unicode-9b0d5c2.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/3848529/script.module.inputstreamhelper-0.4.3-unicode-9b0d5c2.zip)

**Comment by dagwieers** [comment]
We did not get feedback. I assume this was fixed, if not reopen this issue, or leave feedback and we can reopen it.
