### ISSUE TITLE
Translate inputstream.adaptive to more languages

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#211]
Since it improves inputstreamhelper indirectly as well, I would like to have the same languages available in **inputstream.adaptive** as we already offer with ISH.

So this is an appeal to the existing translators.

- Dutch nl_nl -- @mediaminister, @basrieter, @dnicolaas &rarr; peak3d/inputstream.adaptive#338
- French fr_fr -- @brunoduc &rarr; peak3d/inputstream.adaptive#344
- German de_de -- @flubshi, @horstle, @asciidisco &rarr; peak3d/inputstream.adaptive#341
- Greek el_gr -- @Twilight0, @paraskevasleivadaros
- Italian it_it -- @pinoelefante &rarr; peak3d/inputstream.adaptive#336
- Russian ru_ru -- @vlmaksime &rarr; peak3d/inputstream.adaptive#340
- Swedish sv_se -- @emilsvennesson @sopor &rarr; peak3d/inputstream.adaptive#346

It is not a lot of work, [it only includes 22 strings that require translations](https://github.com/peak3d/inputstream.adaptive/blob/master/inputstream.adaptive/resources/language/resource.language.en_gb/strings.po).

**Comment by dagwieers** [comment]
Thanks everyone. The translated languages have been merged.
It was a great success! :+1:

**Comment by dagwieers** [comment]
We have created translator-teams in the @Kodi-addons organization at: https://github.com/orgs/kodi-addons/teams/translators

This will help us translate Kodi add-ons to more languages in the future using less effort.
If you are willing to help out, join a language team!

**Comment by dagwieers** [comment]
@emilsvennesson Could you open a translation request at the Add-ons organization? You can do this by clicking [here](https://github.com/add-ons/translations/issues/new?template=translation_request.md&title=Translate+service.module.inputstreamhelper).

You don't have to fill out the template, I will do it.

*I like to have requests opened by the author, instead of having me open each ;-)*

**Comment by emilsvennesson** [comment]
@dagwieers Done! :-)

**Comment by dagwieers** [comment]
We now have a separate ticket for translating **inputstreamhelper** at: https://github.com/add-ons/translations/issues/5
