### ISSUE TITLE
Setting inputstream.adaptive.* properties vs inputstream.rtmp

### ISSUE THREAD

**Issue by ivankokan** [emilsvennesson/script.module.inputstreamhelper#215]
Hi. Considering that `is_helper.inputstream_addon` could result with `inputstream.rtmp` (not only `inputstream.adaptive`), would setting `inputstream.adaptive.*` properties cause any conflicts in this example?

https://github.com/emilsvennesson/script.module.inputstreamhelper/wiki/Integration

```
playitem.setProperty('inputstream.adaptive.manifest_type', PROTOCOL)
playitem.setProperty('inputstream.adaptive.license_type', DRM)
playitem.setProperty('inputstream.adaptive.license_key', LICENSE_URL + '||R{SSM}|')
```

**Comment by dagwieers** [comment]
The example in the wiki is just that. If your add-on supports RTMP, the logic may be somewhat different, but that is unrelated to inputstreamhelper. ListItem properties that are not supported are ignored.

**Comment by ivankokan** [comment]
> The example in the wiki is just that. If your add-on supports RTMP, the logic may be somewhat different, but that is unrelated to inputstreamhelper. **ListItem properties that are not supported are ignored.**

Thanks, I got it!
