### ISSUE TITLE
Widevine CDM was empty

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#218]
On our main Kodi setup the children complained some add-ons no longer worked. After investigating the widevinecdm.so was empty.

There is no clear reason why it would be empty, the disk had +50GB of free disk space. So there are 3 possibilities:
- Kids stopped an automatic Widevine CDM update during uncompressing?
- Software issue (Kodi restarting during uncompressing, other bug)
- Hardware issue

My assumption is the first one. We now we currently have no progress-indication during uncompressing and this may take op 2 minutes (which is awfully long if you are a kid, cannot read and are waiting for a video to start).

So we need to ensure that we uncompress in a different location and move the file. This would protect us against disk full conditions and people interrupting the uncompress stage, and breaking a possibly working Widevine setup.

This relates to #69, #72 and #105

**Comment by horstle** [comment]
That would be pretty much how it had been before #95.

**Comment by dagwieers** [comment]
@horstle We live, we learn :-)

**Comment by dagwieers** [comment]
My original suggestion was to tackle this together with backup/restore of Widevine CDM.

**For ARM** that would mean, extract under a different name `widevinecdm-{chromeos}.so`, and then hardlink to `widevinecdm.so`. **For non-ARM** we have an actually library version, and would be doing `widevinecdm-{version}.so`, and hardlink to `widevinecdm.so`.

Restoring becomes quite efficient, as you could simply list the available files and select the one you would like to hardlink.

**For ARM** that would require a translation table between ChromeOS version to Widevine version (multiple ChromeOS versions offer the same Widevine, so some optimization would be useful to avoid **(a)** redownloading known ChromeOS images and **(b)** storing multiple identical Widevine versions).

**Comment by horstle** [comment]
The newest version of #193 should fix this.

**Comment by dagwieers** [comment]
PR #193 was merged. Let's close this now.
