### ISSUE TITLE
How to use with MPC-HC from Kodi?

### ISSUE THREAD

**Issue by devidin** [emilsvennesson/script.module.inputstreamhelper#228]
Hello, I use that plugin for Kodi to watch Netflix in better quality. It works perfeclty with it's internal player.  But...
I would like to enhance viewing of Netflix even more with additional video and audio renderers (madVR, DmitriRender, JRiver room correction, ...), hence I need to go through MPC-HC.

So, I try to use it with MPC-HC to open the video stream through the add on's service, but the player says "Failed to render the file".
Settings seems ok since the argument received is something like: http://localhost:7968/manifest?id=81026918 
... and should be the same as the one used by internal player of Kodi whith which it works perfecly well.

I have the same problem when I try to open youtube via another add on of Kodi, with URL's like: https://r5---sn-cxab5jvh-cg0ez.googlevideo.com/videoplayback?expire=1574204439 

I don't understand what's going on. Can someone help me please?

(MPC HC works fine from Kodi with local files, mkv ones for instance; playercorefactory.xml is properly configured. 

Thank you in advance!

==============================
playercorefactory.xml
==============================
 <playercorefactory>
  <players>
    <player name="MPC-HC" type="ExternalPlayer" audio="false" video="true">
      <filename>C:\Users\Devidin\AppData\Roaming\Kodi\userdata\startmpchc.bat</filename>
      <args>{1} /fullscreen /close</args>
      <hidexbmc>false</hidexbmc>
      <hideconsole>false</hideconsole>
      <warpcursor>none</warpcursor>
    </player>
  </players>
  <rules action="prepend">
    <rule video="true" player="MPC-HC"/>
  </rules>
 </playercorefactory>

==============================
startmpchc.bat
==============================
echo %*
echo %* > "C:\Users\Devidin\AppData\Roaming\Kodi\userdata\startmpchc.log"
"C:\Program Files\MPC-HC\mpc-hc64.exe" %*

**Comment by dagwieers** [comment]
Inputstreamhelper is only used for downloading Widevine in case it is missing.
And I have no clue what your issue is related to, but it is not related to that.
So I am afraid we cannot help you with your issue.
