### ISSUE TITLE
Unsupported Widevine architecture found: armv6

### ISSUE THREAD

**Issue by ivankokan** [emilsvennesson/script.module.inputstreamhelper#23]
Hi, how about supporting `armv6` (`WIDEVINE_SUPPORTED_ARCHS`)? I got the message below on my [Raspberry Pi Model B 1](https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications):
`05:57:33.349 T:2753557248   DEBUG: [script.module.inputstreamhelper-0.3.3]: Unsupported Widevine architecture found: armv6`.

**Comment by horstle** [comment]
AFAIK there is no widevinecdm.so for that architecture, that's why it can't be supported. Or did you find any?

**Comment by ivankokan** [comment]
I can't find any relevant source for such information.

**Comment by emilsvennesson** [comment]
Hi!

As @horstle said, there is no Widevine binary available for armv6 so this is unfortuantely not possible.
