### ISSUE TITLE
Error Contents: No module named inputstreamhelper

### ISSUE THREAD

**Issue by rickybiscus** [emilsvennesson/script.module.inputstreamhelper#24]
Hi !
I've downloaded your plugin and installed it from the zip, and I'm trying to use it in my plugin as in your example.

But this fires an error :

        import inputstreamhelper
    ImportError: No module named inputstreamhelper
    -->End of Python script error report<--

Can you help ?
Thanks.

**Comment by emilsvennesson** [comment]
Hi!

Have you imported the module in your `addon.xml` file?

```xml
<requires>
    <import addon="script.module.inputstreamhelper" version="0.3.3"/>
</requires>
```

**Comment by dagwieers** [comment]
@rickybiscus Is this still an issue or can we close it?

**Comment by dagwieers** [comment]
I am going to close this as it is more than one year old.
If you still have an issue, feel free to report back.
Thanks!
