### ISSUE TITLE
Doesn't work on Sony Xperia XA2/ARM v8l/Qualcomm SDM630

### ISSUE THREAD

**Issue by cintema** [emilsvennesson/script.module.inputstreamhelper#245]
[kodi.log.txt](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4049171/kodi.log.txt)

![Bildschirmfoto_20200110_003](https://user-images.githubusercontent.com/6923522/72202526-d5ff3b00-3460-11ea-9ecf-0a4dbad4d1b9.png)

Thank you!

**Comment by dagwieers** [comment]
Could you try the master branch?
https://github.com/emilsvennesson/script.module.inputstreamhelper/archive/master.zip

It will report that Widevine is built into Android.

**Comment by dagwieers** [comment]
Based on the log file it may be that Widevine is not supported by your system, or it is an **inputstream.adaptive** issue.
```
VideoPlayer::OpenFile: plugin://plugin.video.tester/?_=play_video&index=3
2020-01-10 18:51:15.357 T:14174  NOTICE: Creating InputStream
2020-01-10 18:51:15.438 T:14174   ERROR: AddOnLog: InputStream Adaptive: Key system request: com.widevine.alpha
2020-01-10 18:51:17.567 T:14174   ERROR: AddOnLog: InputStream Adaptive: Unable to initialize media_drm
2020-01-10 18:51:17.568 T:14174   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
2020-01-10 18:51:17.570 T:14174   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.tester/?_=play_video&index=3]
```

**Comment by cintema** [comment]
There is no widevine installed on my phone yet since it's running Sailfish OS/Aliendalvik.
I thought widevine would be provided by inputstream helper if not preinstalled?

**Comment by dagwieers** [comment]
There is no Widevine CDM library publicly available for us to install on Android AFAIK. It normally ships with the Android OS. If you happen ro find a solution, we could reconsider, but I doubt it's going to be pretty...

**Comment by cintema** [comment]
What exactely is needed for widevine? May it be possible to copy the widevine library from a genuine Sony Xperia Android image? I would be willing to try this but info about which files were needed is hard to find. Can you provide some further information?
Thanks!

**Comment by cintema** [comment]
Wouldn't it be possible to utilize the ChromeOS widevine libraries on SailfishOS/Aliendalvik as well? And if not, why not?

**Comment by dagwieers** [comment]
> Wouldn't it be possible to utilize the ChromeOS widevine libraries on SailfishOS/Aliendalvik as well?
Possibly, but we are not allowed to redistribute these libraries, so we cannot automate it ourselves.
But if you put them in the right place, I believe it ought to work.

**Comment by cintema** [comment]
Sounds interesting.
I've extracted the relevant libraries using this script:
https://gist.github.com/ruario/19a28d98d29d34ec9b184c42e5f8bf29
Can you tell me the path where to put them?
Thank you!

**Comment by dagwieers** [comment]
See my previous message.

**Comment by cintema** [comment]
Already saw it, sorry for asking :)
However, it doesn't seem possible to modify files in /user/0 on sailfishOS at present. Can I change the path at which inputstreamhelper looks for the widevine libs to e.g. $home/Android/data/org.xbmc.kodi/ or somewhere else in the homdir (e.g. $home/.widevine)?
Thank you!

**Comment by dagwieers** [comment]
@cintema You can modify this path from the **inputstream.adaptive** settings in **General » Decrypter path**.

**Comment by cintema** [comment]
![20200115174906](https://user-images.githubusercontent.com/6923522/72453437-602c0400-37bf-11ea-8c86-a2ceb2bf9101.jpg)
I don't think I have this option on android (and the only accessible dir on SfOS-Alien Dalvik is the Android user home directory, therfore copying to /home cdm is not an option, unfortunately).
Can I modify the plugin .py/.xml stored at $home/data?

**Comment by dagwieers** [comment]
I said **inputstream.adaptive**, not **inputstreamhelper**. It is a different add-on.

**Comment by cintema** [comment]
Inputstream.adaptive doesn't appear to be installed nor available for android in the official repo. Installing zip-files fails.
![20200122152232](https://user-images.githubusercontent.com/6923522/72902607-12b61680-3d2c-11ea-8d0d-f7d20d7a8aea.jpg)
May I try the rpi2 version or what would you suggest?
Any other way to supply the widevine lib to inputstream.helper?

**Comment by dagwieers** [comment]
Yes it does.
![Screenshot_20200122-194346](https://user-images.githubusercontent.com/388198/72923601-b369fd80-3d4f-11ea-9f31-c07181d907d6.jpg)

**Comment by cintema** [comment]
I'm using a standard kodi release for android and i didn't modify the repos (except for ADDING some skygo related stuff):
![20200123110009](https://user-images.githubusercontent.com/6923522/72974614-97a63c00-3dcf-11ea-9e8f-be9101df6f34.jpg)

What am I missing?
Thank you.

**Comment by cintema** [comment]
![20200123110802](https://user-images.githubusercontent.com/6923522/72975273-cf61b380-3dd0-11ea-9bf2-1f2873476c89.jpg)

**Comment by dagwieers** [comment]
![Screenshot_20200123-151340](https://user-images.githubusercontent.com/388198/72991903-1e204500-3df3-11ea-8086-a4b17ea4f11b.jpg)

**Comment by dagwieers** [comment]
We have the same Kodi. But your Android may be missing required infrastructure for inputstream.adaptive?

**Comment by cintema** [comment]
As I said, I'm on SailfishOS (which is rather a LSB-Linux devirative (with rpm, zypper etc.) and an Android compatibility layer (Alien Dalvik) than a full featured Android. Since Kodi is somewhat standalone, I wonder if it was possible to utilize third party libwidevine as on Ubutntu instead of searching for Android DRM support. This would also benefit people using Kodi on Foss-Android clones like LineageOS.

**Comment by cintema** [comment]
Plus, I don't understand why inputstream.adaptive is not even offered for my Kodi release (not even when listing incompatible packages). I tried to search for a standalone.zip file but I could only find some packages für x86. Is there no other possibility to address libwidevine from inputstream.helper than inputstream.adaptive? I wonder since the inputstream.helper information screen displays a widevine.cdm path. I would have thought that, if it was possible to change this path to where the libwidevine.so is found, libwidevine might be utilized for decoding...

**Comment by dagwieers** [comment]
@cintema I think this is the wrong forum for your questions, maybe https://github.com/peak3d/inputstream.adaptive is a better location to direct your questions?

**Comment by peak3d** [comment]
We can try to solve issues here, if it is ok for you @dagwieers, I agree that it is not the right place.

- from where do you get kodi, and for what platform exactly @cintema ? How have you installed it?

**Comment by dagwieers** [comment]
@peak3d I don't mind, it's just that I have no clue on the cause, or if a solution is at all possible.

**Comment by cintema** [comment]
Plus, I don't understand why inputstream.adaptive is not even offered for my Kodi release (not even when listing incompatible packages). I tried to search for a standalone.zip file but I could only find some packages für x86. Is there no other possibility to address libwidevine from inputstream.helper than inputstream.adaptive? I wonder since the inputstream.helper information screen displays a widevine.cdm path. I would have thought that, if it was possible to change this path to where the libwidevine.so is found, libwidevine might be utilized for decoding...

**Comment by cintema** [comment]
I downloaded the Android package from kodi.tv.
Since I have both, the 32bit and 64bit release in my download folder I cannot really tell which release is currently installed (I presume the 32bit release as the 64bit release could not be installed - could be vice versa, though). Is there

**Comment by cintema** [comment]
BTW: Sorry for always hitting the wrong (close issue) buttons... wasn't intentional, the issue still exist!)

**Comment by peak3d** [comment]
@cintema search your device for the kodi.log file and post it here. inputstream.adaptive is in general always bundled in the apk's provided by kodi, so either you have picked a bad nightly, or something else is wrong. widevine presence does not influence inputstream.adaptive appearance b.t.w., means it should be there.

**Comment by dagwieers** [comment]
@peak3d It appears my smartphone has the same Kodi release as @cintema, the one from the Play Store (update from 2019-11-17). See screenshots. But mine is running on a real Android.

**Comment by cintema** [comment]
> For android we use MediaDrm for widevine, not libwidevine.so. If you want to use libwidevine on a android device, some deeper changes have to be done, this includes the build system which already sticks MediaDrm to inputstream.adaptive at build time.

Thank you for clarification!
Would it be possible to just install the raspy release of inputstream.adaptive on Android?

**Comment by mirh** [comment]
At least L3 should be possible on every phone, it's just a matter of copy-pasting a [library](https://github.com/Unlegacy-Android/proprietary_vendor_widevine). 
L1 is [also](https://github.com/LineageOS/android_device_sony_pioneer/commit/800c828ff18343690344313d77e86b076102bec2) [possible](https://github.com/LineageOS/android_device_sony_nile-common/commit/b674a0920b7db0e480c710f6695db7ed19a89fea), at least if your device ever got the official certification and you didn't screw keys. 

I'm not sure if it's doable for Kodi to find/ship it itself, but anyway it sounds at least a bug to report to the [jolla guys](https://github.com/mer-hybris/droid-vendor-sony-nile-pioneer).

**Comment by Invictaz** [comment]
@cintema very interesting efforts. It might be that Sailfish didn't pay Google for the required keys for your phone. So a general CDM does not work as it needs hardware decryption keys per device in order to use L1. L3 would be possible by testing this. Get your CDM first. 

https://forum.videohelp.com/threads/404994-Decryption-and-the-Temple-of-Doom
