### ISSUE TITLE
installation failed on Raspbian when not run as pi user

### ISSUE THREAD

**Issue by hvdkooij** [emilsvennesson/script.module.inputstreamhelper#246]
It seems the installation fails on Raspbian when run as user kodi instead of user pi.

Enabling debug logging shows me:

2020-01-11 17:08:18.456 T:1393553632   DEBUG: [script.module.inputstreamhelper]: [u'sudo', u'losetup', u'-o', '163
577856', u'/dev/loop0', u'/home/kodi/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/chromeos_12607
.58.0_nyan-kitty_recovery_stable-channel_kitty-mp-v2.bin'] cmd failed.
2020-01-11 17:08:18.457 T:1393553632   DEBUG: [script.module.inputstreamhelper]: [u'sudo', u'losetup', u'-o', '163
577856', u'/dev/loop0', u'/home/kodi/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/chromeos_12607
.58.0_nyan-kitty_recovery_stable-channel_kitty-mp-v2.bin'] cmd output:

                                            We trust you have received the usual lecture from the local System
                                            Administrator. It usually boils down to these three things:

                                                #1) Respect the privacy of others.
                                                #2) Think before you type.
                                                #3) With great power comes great responsibility.

                                            sudo: no tty present and no askpass program specified
2020-01-11 17:08:18.697 T:1393553632   DEBUG: [script.module.inputstreamhelper]: [u'sudo', u'mount', u'-t', u'ext2
', u'-o', u'ro', u'/dev/loop0', u'/home/kodi/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/mnt']
cmd failed.
2020-01-11 17:08:18.697 T:1393553632   DEBUG: [script.module.inputstreamhelper]: [u'sudo', u'mount', u'-t', u'ext2
', u'-o', u'ro', u'/dev/loop0', u'/home/kodi/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/mnt']
cmd output:

                                            We trust you have received the usual lecture from the local System
                                            Administrator. It usually boils down to these three things:

                                                #1) Respect the privacy of others.
                                                #2) Think before you type.
                                                #3) With great power comes great responsibility.

                                            sudo: no tty present and no askpass program specified

However the kodi user is in all groups that the pi user is in on the system.

I think the bugger here is that the kodi user needs a sudo password.

**Comment by dagwieers** [comment]
We need root privileges at this time if Kodi is not running as root. Please look at: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/57#issuecomment-506321509

This needs to be documented in the Wiki, so your issue ticket for me is a documentation issue.

**Comment by hvdkooij** [comment]
If you go to /etc/sudoers.d you can see the different files:
-r--r----- 1 root root  27 Oct 18  2016 010_pi-nopasswd
-rw-r--r-- 1 root root 120 Jan 11 17:35 020_kodi

I copied the single line from 010_pi-nopasswd to 020_kodi and changed the user in that line from pi to kodi

And that resolved the issue.

So all is well in the end.

**Comment by dagwieers** [comment]
@hvdkooij Great to hear! Could you please write this up as instructions for other users? I can then add those instructions to the Wiki. So we need to tell users to modify file X with changes Y to get result Z on Raspbian version V.

**Comment by horstle** [comment]
AFAIK you're not supposed to edit the sudoers manually, but should always use the visudo command for that.

**Comment by dagwieers** [comment]
@horstle `visudo` is safer as a misedit does not lock you out (when sudo would be the only means to become root). However if `visudo` gets you into a vim session, some users may not get the changes made ;-)

So it is better, but not forbidden.

**Comment by horstle** [comment]
Obviously you can't forbid anything, because the user owns their machine and can use it however he wants, but it is still strongly recommended and I don't think their should be anything different in the wiki.
 I know vi/vim can be difficult for unexperienced users, but a simple `sudo EDITOR=nano/gedit/... visudo` fixes that.

**Comment by dagwieers** [comment]
I think you are jumping the gun here, obviously `visudo` will be in the Wiki, but before we fall over technicalities, I need written up details...

**Comment by horstle** [comment]
Alright, I think nano should be installed on Raspbian by default, so I would put something like this in the wiki:

For the moment Inputstream Helper needs passwordless sudo for various tasks, so make sure the user running Kodi has these rights by following these steps:

- run `sudo EDITOR=nano visudo`
- use the arrow keys to go to the end of the file
- add a line `<USERNAME> ALL=ALL NOPASSWD:ALL`
- Press Ctrl+X and then Y to save the changes and exit

What do you think?

**Comment by dagwieers** [comment]
We could make that more strict. But I personally prefer to add or modify */etc/sudoers.d/*.

**Comment by dagwieers** [comment]
This is now fixed in #348 and will be released as part of **inpustreamhelper** v0.5.0.

**Comment by horstle** [comment]
I think this can be closed because of what @dagwieers said.

**Comment by hvdkooij** [comment]
Not sure if this is resolved as I still have the same issue.
It's also not clear why my original sudoers file for the kodi user was changed at a later day.
I'm in the process of investigating this right now.

**Comment by dagwieers** [comment]
@hvdkooij This is resolved in the master branch as we no longer need sudo-rights.
