### ISSUE TITLE
Suggestion/request to information screen

### ISSUE THREAD

**Issue by CastagnaIT** [emilsvennesson/script.module.inputstreamhelper#248]
Many, many, many people do not understand that on android you can not get the Widevine version with ISHelper
They read "Not found" and most of the time always think the component _is missing_.

I'm really tired of saying the same thing to every new person who comes in...

![image](https://user-images.githubusercontent.com/3257156/72441318-c4909880-37aa-11ea-995d-97e07a15828d.png)

I suggest adding a variable to identify the execution on Android system
and add a new line of information such as:
`- Widevine package:` Embedded [on android] / Installed [to others] / Not installed

And for this line:
`- Widevine version:` N° of version
make it non-visible on android system

this would make it easier for everyone to understand and read the info data

**Comment by dagwieers** [comment]
This is already fixed in the master branch, but we haven't released it yet.

**Comment by CastagnaIT** [comment]
oh luckily, well
thanks!

**Comment by dagwieers** [comment]
Given that we did this in October 2019, maybe we ought to consider making a new v0.5.0 release?

**Comment by dagwieers** [comment]
I would also like to query the library to get the version from it directly, rather than grep for a pattern.

**Comment by CastagnaIT** [comment]
you can try to get the android widevine version in in this way:

create a instance of xbmcdrm.CryptoSession, then get the "version" string

look at android_crypto.py in https://github.com/CastagnaIT/plugin.video.netflix/pull/438

**Comment by dagwieers** [comment]
@CastagnaIT It doesn't seem to work, every key I ask for is empty. At least on a Raspberry Pi.

**Comment by dagwieers** [comment]
This works to get the version on Linux:
```python
from ctypes import *
_widevine_lib = cdll.LoadLibrary('libwidevinecdm.so')
get_cdm_version = _widevine_lib.GetCdmVersion
get_cdm_version.restype = c_char_p
print('Widevine version: %s' % get_cdm_version())
```
