### ISSUE TITLE
Wrong widevine version number with Kodi 19

### ISSUE THREAD

**Issue by Essam311** [emilsvennesson/script.module.inputstreamhelper#250]
Just a minor problem I found. In Kodi 19 when I go to "InputStream Helper information" number "3" been added before the widevine version number. I used the latest nightly for Kodi 19 and 18 for windows 64.

Kodi 19

<img width="700" alt="2222" src="https://user-images.githubusercontent.com/59211054/73094339-0a570a80-3ee9-11ea-9c1e-9a74b76be788.png">

Kodi 18

<img width="701" alt="1111" src="https://user-images.githubusercontent.com/59211054/73094361-15aa3600-3ee9-11ea-84b3-4f6699cf55a0.png">

**Comment by mediaminister** [comment]
I fixed it. There was a problem converting bytes to a string on Windows with Kodi 19 (Python3), but I can't explain why we got a 3. I debugged this on Linux and couldn't reproduce getting a 3.

**Comment by Essam311** [comment]
@mediaminister Thank you so much, the problem fixed on Windows with Kodi 19.
