### ISSUE TITLE
Something strange when call check_inputstream() with InputStream Adaptive disabled

### ISSUE THREAD

**Issue by CastagnaIT** [emilsvennesson/script.module.inputstreamhelper#251]
I realized while i was doing tests on Kodi 19 with Netflix addon
that if you disable manually the InputStream Adaptive
and try to play a video on Netflix
the helper ask to you if you want enable the InputStream Adaptive, but after press "Yes" respose
the `check_inputstream` method do not return the right value
this way it's blocking my addon from playing the video

If you have need, log here: https://paste.kodi.tv/owizizadaj.kodi
line 3556

happens both on windows and android

can you check it out?
thanks

**Comment by dagwieers** [comment]
We do accept patches 😉

I'll look at it, hopefully this evening.

**Comment by dagwieers** [comment]
I see this when I disable **inputstream.adaptive**:
![screenshot027](https://user-images.githubusercontent.com/388198/73128171-c0932080-3fcb-11ea-914b-a77000897ab5.png)

**Comment by dagwieers** [comment]
On the other hand, without this piece, it would still fail. I can see that with other add-ons, inputstreamhelper doesn't seem to intervene when **inputstream.adaptive** is disabled.

**Comment by dagwieers** [comment]
Ok, so I found a logic error in v0.4.3 causing  `check_inputstream()` to report False even when it just enabled **inputstream.adaptive** successfully. With this small change it works as expected.

So this will be fixed in v0.5.0 !

**Comment by dagwieers** [comment]
The master branch should be fine now. Please test and report back!

**Comment by CastagnaIT** [comment]
now is working thanks,
now that check_inputstream() return the right value, the code of the screenshot error mentioned is not executed

**Comment by dagwieers** [comment]
Thanks for reporting!

**Comment by CastagnaIT** [comment]
is possible to know more or less, when the new release will be out?

**Comment by dagwieers** [comment]
@mediaminister When do we plan a new release?
Is the rollback functionality solid and tested for release?

**Comment by mediaminister** [comment]
Rollback is untested. Maybe I find some time by the end of February to test this and make a release.
