### ISSUE TITLE
error installing Widevine CDM - stops on 5% on extracting screen

### ISSUE THREAD

**Issue by lpt2007** [emilsvennesson/script.module.inputstreamhelper#253]
Here I posted issue and they say that is  script.module.inputstreamhelper related?

CastagnaIT/plugin.video.netflix#454

**Comment by dagwieers** [comment]
This appears related to #146

**Comment by horstle** [comment]
The log you provided doesn't contain debugging info. Please enable debug logging and try to manually install widevine via the inputstreamhelper settings page.

**Comment by horstle** [comment]
Whatever happened here was resolved with #348 .
