### ISSUE TITLE
Error while extracting chrome os recovery image

### ISSUE THREAD

**Issue by Chris2711** [emilsvennesson/script.module.inputstreamhelper#265]
Hello everybody,
while setting up Netflix-Addon ( CastagnaIT / plugin.video.netflix)  to my Raspi3+ (libreelec 9.2.0) everything is working fine until downloading the chrome OS recovery images. When download is complete i get following error while extracting the package :

error: Error -3 while decompressing: invalid stored block lengths

I´ve installed:
plugin.video.netflix-0.16.4.zip / CastagnaIT

and tried following modules due to #146 (unable update or re-install widevine for netflix):
script.module.inputstreamhelper-0.4.1-armfix-5dc3e7b.zip
script.module.inputstreamhelper-0.4.2-release-73fc720.zip
and the actual one 0.4.3 which is automatically installed with the plugin

What´s wrong here. I attached my kodi.log. Can anybody help me?

Thanks Chris
[KODI LOG.txt](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4177850/KODI.LOG.txt)

**Comment by dcambria** [comment]
Similar problem here. Tested with script.module.inputstreamhelper-0.4.2 and 0.4.3 from repo.
Thanks
[kodi.log](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4184186/kodi.log)


2020-02-11 02:04:19.448 T:1475338464   DEBUG: [script.module.inputstreamhelper-0.4.2]: [u'modinfo', u'loop'] cmd failed.
2020-02-11 02:04:19.455 T:1475338464   DEBUG: [script.module.inputstreamhelper-0.4.2]: [u'modinfo', u'loop'] cmd output:
                                            modinfo: ERROR: Module loop not found.
2020-02-11 02:04:19.456 T:1475338464   DEBUG: [script.module.inputstreamhelper-0.4.2]: loop is built in the kernel.
2020-02-11 02:04:19.556 T:1475338464   DEBUG: [script.module.inputstreamhelper-0.4.2]: [u'losetup', u'-f'] cmd executed successfully.
2020-02-11 02:04:19.557 T:1475338464   DEBUG: [script.module.inputstreamhelper-0.4.2]: [u'losetup', u'-f'] cmd output:
                                            /dev/loop1
2020-02-11 02:04:19.557 T:1475338464   DEBUG: [script.module.inputstreamhelper-0.4.2]: Found free loop device: /dev/loop1
2020-02-11 02:04:19.739 T:1475338464   DEBUG: [script.module.inputstreamhelper-0.4.2]: [u'fdisk', u'/home/dcambria/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/chromeos_12607.82.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin', u'-l'] cmd executed successfully.
2020-02-11 02:04:19.740 T:1475338464   DEBUG: [script.module.inputstreamhelper-0.4.2]: [u'fdisk', u'/home/dcambria/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/chromeos_12607.82.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin', u'-l'] cmd output:
                                            GPT PMBR size mismatch (8609948 != 4436015) will be corrected by write.
                                            Disk /home/dcambria/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/chromeos_12607.82.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin: 2.1 GiB, 2271240192 bytes, 4436016 sectors
                                            Units: sectors of 1 * 512 = 512 bytes
                                            Sector size (logical/physical): 512 bytes / 512 bytes
                                            I/O size (minimum/optimal): 512 bytes / 512 bytes
                                            Disklabel type: gpt
                                            Disk identifier: F46DA093-FAF4-874A-BC1C-FD9B0D3015DD

                                            Device                                                                                                                                                Start     End Sectors  Size Type
                                            /home/dcambria/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/chromeos_12607.82.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin1  4415488 4435967   20480   10M Linux filesystem
                                            /home/dcambria/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/chromeos_12607.82.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin2    20480   53247   32768   16M ChromeOS kernel
                                            /home/dcambria/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/chromeos_12607.82.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin3   319488 4415487 4096000    2G ChromeOS root fs
                                            /home/dcambria/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/chromeos_12607.82.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin4    53248   86015   32768   16M ChromeOS kernel
                                            /home/dcambria/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/chromeos_12607.82.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin5   315392  319487    4096    2M ChromeOS root fs
                                            /home/dcambria/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/chromeos_12607.82.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin6    16448   16448       1  512B ChromeOS kernel
                                            /home/dcambria/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/chromeos_12607.82.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin7    16449   16449       1  512B ChromeOS root fs
                                            /home/dcambria/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/chromeos_12607.82.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin8    86016  118783   32768   16M Linux filesystem
                                            /home/dcambria/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/chromeos_12607.82.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin9    16450   16450       1  512B ChromeOS reserved
                                            /home/dcambria/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/chromeos_12607.82.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin10   16451   16451       1  512B ChromeOS reserved
                                            /home/dcambria/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/chromeos_12607.82.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin11      64   16447   16384    8M unknown
                                            /home/dcambria/.kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/chromeos_12607.82.0_veyron-jaq_recovery_stable-channel_jaq-mp-v5.bin12  249856  315391   65536   32M EFI System

                                            Partition table entries are not in disk order.

**Comment by horstle** [comment]
@dcambria It sounds like your issue could be the same as #223 .

**Comment by Chris2711** [comment]
Meanwhile i tried setting up the Netlix-Addon on a plain Rasbian lite system with KODI 18.2. Everything is working fine including the widevine cdm extraction. I only have the issue with using Libreelec 9.2.0 OS.

**Comment by Chris2711** [comment]
when I try extract the ZIP-File which is downloded with 7Zip I get an data-error too.
This is the ZIP-FILE which is downloaded and 279 MB of 1490MB is extracted until the error: Error -3 while decompressing: invalid stored block lengths appears :
chromeos_12607.82.0_nyan-kitty_recovery_stable-channel_kitty-mp-v2.bin.zip

Is it a corrupted file?

**Comment by horstle** [comment]
Might be. Did you try manually reinstalling via the settings page?

**Comment by dagwieers** [comment]
We probably want to check the filesize (or the checksum) after the download has finished.
The filesize is probably the best tradeoff, since a checksum would add additional time to the process.
(Given the size of these files, it flushes memory caches additionally)

**Comment by Chris2711** [comment]
@ horstle: What do you with manually reinstalling via settings page?
The Zip-File is downloaded and extracted when first time try to start a film or tvshow automatically.

**Comment by Chris2711** [comment]
@dagwieers: Thanks for info. Is there anything i can do to support you? Do you need more Log-Files?

**Comment by horstle** [comment]
Somewhere in your addons section should be an entry "InputStream Helper" if you click on it its settings page will open and you will see an option to reinstall manually.

**Comment by Chris2711** [comment]
@horstle: i tried installing via setting page. The task is breaking down while extracting with no errormessage and no cdm is displayed. i can choose installing cdm like before.

**Comment by horstle** [comment]
What does the log say? Is it the same error as before? Please upload.

**Comment by dcambria** [comment]
> @dcambria It sounds like your issue could be the same as #223 .

thank you! It is working now :)

**Comment by Chris2711** [comment]
I sucessfully installed the cdm via settings page. There was still the old chromeos.zip-file and the partly extrackted .so-file in the cdm-folder. I removed these old files and then the manually installation was sucessful. I will try it one more time with installing cdm while starting first time a tv-show and let you know if this is working too.

**Comment by Chris2711** [comment]
Both ways working now sucessfully. Sorry for taking your time. Looks like a corrupted zip-file i downloaded on 14th feb. I think this issue is closed now. Thanks for helping.

**Comment by dagwieers** [comment]
The least we can do is verify the size of the ZIP with the expected size of the ZIP. If they don't match the download was interrupted/corrupted.

**Comment by horstle** [comment]
Also, we should do a full cleanup at the beginning of `install_widevine()`, so the temp dir gets removed if it failed previously.

**Comment by dagwieers** [comment]
@horstle Feel free to open new feature requests for individual TODO items, so we can close this ticket eventually. Thanks!

**Comment by horstle** [comment]
I created a PR, since it's basically just one line.
