### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by U5MANKHAL1D** [emilsvennesson/script.module.inputstreamhelper#268]
iPad Air 2
iOS 13.3
Kodi 18.5

Netflix addon on kodi gives error that widevine cdm is not supported on my device. Although it is supported. Please help
<img width="1024" alt="Screenshot 2020-02-15 at 6 50 00 PM" src="https://user-images.githubusercontent.com/61058010/74589244-695dfa00-5025-11ea-8bf2-5afe182ce405.png">
<img width="1024" alt="Screenshot 2020-02-15 at 4 46 30 PM" src="https://user-images.githubusercontent.com/61058010/74589248-74b12580-5025-11ea-8280-29634245b1da.png">

**Comment by dagwieers** [comment]
Please provide us with a Kodi debug log file.

Because I need to know what iOS returns for e.g.
```shell
python -c 'import os, platform; print(os.name); print(platform.system())'
```

I am also not sure if iOS is supported, if you know where to find the Widevine CDM library, that may help as well.

**Comment by horstle** [comment]
The screenshot you provided shows that widevine is not supported on your system (at least in that browser), so why would you say it is?

**Comment by CastagnaIT** [comment]
I'm not sure if there's a way to integrate widevine for ios
from here
https://www.widevine.com/news
it seems to be supported but maybe there is no downloadable version!?
i have preferred leave the last word here, think it's more appropriate

**Comment by U5MANKHAL1D** [comment]
While using Netflix addon, error says Inputstream adaptive is not available. But inputstream adaptive work with other addon. 
<img width="1024" alt="Screenshot 2020-02-17 at 3 07 28 PM" src="https://user-images.githubusercontent.com/61058010/74644821-ba422f80-5198-11ea-99ca-29d5edcc4a4a.png">
<img width="1024" alt="Screenshot 2020-02-17 at 3 07 46 PM" src="https://user-images.githubusercontent.com/61058010/74644857-c5955b00-5198-11ea-90da-ace4322a3f90.png">
Here are logs
[kodi.log](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4213085/kodi.log)

**Comment by CastagnaIT** [comment]
the second one is a generic error of Netflix addon, you can recognize by the window title,
it is a result of the first error, without widewine cdm you can not play videos

**Comment by U5MANKHAL1D** [comment]
So how to get widewine cdm !!?

**Comment by U5MANKHAL1D** [comment]
As per widevine.com
<img width="1024" alt="News" src="https://user-images.githubusercontent.com/61058010/74647818-355a1480-519e-11ea-9970-d4125ba3ac63.png">

**Comment by dagwieers** [comment]
> So how to get widewine cdm !!?

We don't know. So we cannot solve this until someone does. It is not available from the known locations for other platforms afaik.

**Comment by horstle** [comment]
Maybe @peak3d knows some more about this.
And even if we found the binary and put it in place, would inputstream.adaptive be able to make use of it?

**Comment by U5MANKHAL1D** [comment]
Inputstreams adaptive does work for other addons and is included in kodi 18.5. Am I right !?

**Comment by CastagnaIT** [comment]
no, you're confusing videos with DRM protected and unprotected streams

not all addon need to play video with DRM, so Inputstreams adaptive works anyway
if an addon have to play DRM protected stream is needed Inputstreams adaptive with the DRM library (widevine in this case)

**Comment by U5MANKHAL1D** [comment]
Okay. Thanks

**Comment by mediaminister** [comment]
There is no public Widevine binary for iOS, only companies who sign up for Widevine CWIP training get access to these binaries under NDA. We can't and won't fix this for this reason.
