### ISSUE TITLE
chromeos download for widevine installation fails on bad connections

### ISSUE THREAD

**Issue by RolfWojtech** [emilsvennesson/script.module.inputstreamhelper#274]
I have an a95x behind a pretty bad wifi connection. This makes inputstreamhelper fail the 600mb download every time.
I tried to just wget the file which worked fine.
Next I changed __init.py__ to add a timeout of 5 seconds to the urlopen call.

I am creating a pull request, this is just for tracking the issue.
Since recreating the bug is pretty tricky I will not create a new unit test (one would have to simulate a connection that randomly breaks).

**Comment by horstle** [comment]
This could be the cause for #265 , too.

**Comment by RolfWojtech** [comment]
I doubt that is fixed issues with extraction, for me it had presented itself as a HTTPS error (unfortunately I forgot to take screenshots to give an exact error). In any case it didn't even go to the extract stage.
