### ISSUE TITLE
Failing to install inputstreamhelper with the latest Kodi 19

### ISSUE THREAD

**Issue by Essam311** [emilsvennesson/script.module.inputstreamhelper#286]
With the latest nightly for Kodi 19 win64 installing inputstreamhelper fails.

**Comment by mediaminister** [comment]
Okay, this comes as a total surprise for me.

Apparently on the 1st of March https://github.com/xbmc/xbmc/pull/17188 was merged and this broke all addons with `<import addon="xbmc.python" version="2.25.0"/>` in `addon.xml`
I didn't receive any communication from Kodi Team regarding this breaking change. As far as I know the relevant Kodi wiki pages are not updated to inform add-on developers about this breaking change:
https://kodi.wiki/view/General_information_about_migration_to_Python_3
https://kodi.wiki/view/Addon.xml

It seems we have to submit our add-on twice now, one time for Kodi 18 (and older) and one time for Kodi 19. I'll investigate what the best practice is to do so.

**Comment by horstle** [comment]
I think it's best to create a branch for <18 and make the necessary change to master. Since v0.4.4 is currently being released, it would be great if this was done quickly.

**Comment by mediaminister** [comment]
I won't add a change to master branch that breaks InputStream Helper for the currently released and most widely used Kodi 18 version.

Kodi 19 is still in Alpha and practically useless since https://github.com/xbmc/xbmc/pull/17188 has been merged and all Python3 compatible scripts/plugins were removed.
There is also no release date for Kodi 19 communicated, so there is no need to hurry.

Submitting our single Py2/Py3 compatible codebase twice makes no sense to me. I'll wait for Team Kodi to come up with a better solution.

v0.4.4 will be submitted once just like I did for the previous InputStream Helper versions.

**Comment by horstle** [comment]
You could just mark the new branch as default, but that's fine. I actually thought Kodi 19 was closer to release.

**Comment by dagwieers** [comment]
@horstle The problem is that we need to offer 2 ZIP files (pre v19 and post v19) for people to troubleshoot and maintain two branches. Where the only difference is one version in the addon.xml.

**Comment by horstle** [comment]
I totally agree, that having only one branch would be much less hassle, but from what I read it sounded like there was no alternative. I guess waiting is the best thing to do right now.

By the way does anybody know how it shows up in kodi, when an addon is submitted twice to different repos, but with the same version number? Will the user see the same entry twice? In that case on Matrix there would always be two entries, where one fails to install.

**Comment by dagwieers** [comment]
@horstle Entries submitted in any branch prior to Matrix will not be build for Matrix. So you will not have the same add-on version twice.

**Comment by horstle** [comment]
So I guess there is no other option, but to submit twice. Of course sticking with only one branch would still be much easier.

**Comment by dagwieers** [comment]
We will be sticking to one master branch in this project, which will work with v18 and older for now.
But to submit to xbmc/repo-plugins we may have to submit twice.
We could have a make target do this work for us: create 2 branches (krypton and matrix) and the PRs

And for releases we could create 2 ZIP files as well, but it is all so pointless...

**Comment by orfeous1** [comment]
No fixes available?
KodiSetup-20200226-cde760b9-master-x64 is the latest version that hasnt broke the addons.
All versions after that does not work.

**Comment by Essam311** [comment]
> 
> 
> No fixes available?
> KodiSetup-20200226-cde760b9-master-x64 is the latest version that hasnt broke the addons.
> All versions after that does not work.

Temporary you could use this slightly modified inputstreamhelper with the latest Kodi 19 Matrix just remember to install your add-ons from zip files and to install them after installing the modified inputstreamhelper, and in each one of your add-ons zip files open `addon.xml` and replace

`<import addon="xbmc.python" version="2.25.0"/>`

with

`<import addon="xbmc.python" version="3.0.0"/>`

[script.module.inputstreamhelper-0.4.4.py3.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4312391/script.module.inputstreamhelper-0.4.4.py3.zip)

and here are plugin.video.retrospect-5.1.8 and plugin.video.retrospect-5.1.9 modified so you can install them on the latest Kodi 19 Matrix

[plugin.video.retrospect-5.1.8.py3.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4312396/plugin.video.retrospect-5.1.8.py3.zip)

[plugin.video.retrospect-5.1.9.py3.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4312397/plugin.video.retrospect-5.1.9.py3.zip)

**Comment by orfeous1** [comment]
Thank you so much! :)

**Comment by dagwieers** [comment]
> script.module.inputstreamhelper-0.4.4.py3.zip

This is a misleading name because most versions work for both py2 and py3 anyway. Please indicate that they are customized to run on Matrix instead: **script.module.inputstreamhelper-0.4.4-matrix.zip**

**Comment by Essam311** [comment]
@dagwieer I understand inputstreamhelpe work for both py2 and py3, I just named them like the developer of plugin.video.youtube named his version for matrix https://github.com/jdf76/plugin.video.youtube/releases/tag/6.6.0, and modified inputstreamhelpe for my personal use as I said before here https://github.com/CastagnaIT/plugin.video.netflix/issues/506#issuecomment-596341292.

**Comment by mediaminister** [comment]
Once https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/293 gets merged, I could do a Matrix release via Github.

**Comment by mediaminister** [comment]
A matrix compatible zip package is available at https://github.com/emilsvennesson/script.module.inputstreamhelper/releases/download/v0.4.4/script.module.inputstreamhelper-0.4.4+matrix.1.zip

**Comment by Essam311** [comment]
@mediaministe Shouldn't inputstreamhelper be on the Kodi Matrix repo same as it is on the Kodi Leia repo so the other add-ons that depend on inputstreamhelper install it while installing the add-ons on Kodi 19 Matrix (for example the Netflix add-on and Amazon VOD add-on)?

**Comment by Essam311** [comment]
Many thanks for all the developers for submitting inputstreamhelper to the Kodi Matrix repo.

**Comment by CastagnaIT** [comment]
There have been changes in the Kodi 19 python API
the addon doesn't work anymore

https://github.com/xbmc/xbmc/pull/17456
https://github.com/xbmc/xbmc/pull/17494

please check thanks

**Comment by orfeous1** [comment]
It works very well on my end.
Using KodiSetup-20200318-809e36a2-master-x64

**Comment by mediaminister** [comment]
I'm working on it.

**Comment by mediaminister** [comment]
@CastagnaIT Can you please test https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/298

**Comment by CastagnaIT** [comment]
yes now seem all working as expected

**Comment by Mariusz89B** [comment]
You need to remove line1, line2 ect in xbmcgui.Dialog(). otherwise it will fail during install.

https://forum.kodi.tv/showthread.php?tid=344263&pid=2933596#pid2933596

**Comment by flubshi** [comment]
Is there a chance to get an updated version into the Kodi repo? Version 0.4.4 seems not to work with latest Matrix anymore. 

I think @CastagnaIT and @Essam311 already provide a patched version [here](https://github.com/CastagnaIT/plugin.video.netflix/issues/537) for the ntetflix plugin - maybe you could create a PR?

**Comment by Essam311** [comment]
Thank you so much for submitting script.module.inputstreamhelper-0.4.5+matrix.1 to the Kodi Matrix repo.
