### ISSUE TITLE
InputstreamHelper agressively tries to update on linux/arm

### ISSUE THREAD

**Issue by Gujal00** [emilsvennesson/script.module.inputstreamhelper#289]
I have Coreelec 9.2.1 running on my S905X machine with Netflix addon that works perfectly with inputstream adaptive.
Netflix addon uses inputstream helper as a dependency and wont let me disable inputstream helper if required,
With the recent update to 0.4.4 I can't play anything in Netflix because Inputstream helper is called and it wants to update widevine (For apparently no reason)
The currently installed widewine details from debug log is below
```
[script.module.inputstreamhelper] 
Kodi information
 - Kodi version: 18.5
 - Kodi platform/architecture: Linux/arm

InputStream information
 - InputStream Helper version: 0.4.3 
 - InputStream Adaptive version: 2.4.3.1 

 - Widevine information
 - Widevine version: 4.10.1610.6 (last updated on 2020-02-25 10:21)
 - Widevine CDM path: /storage/.kodi/cdm
 - Chrome OS version: 12607.82.0
```
There is no newer ChromeOS Version, yet inputstream helper wants to download `https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_12607.82.0_nyan-kitty_recovery_stable-channel_kitty-mp-v2.bin.zip` even though it is the same version installed.
It really is a pain updating on linux-arm as the file is huge to download and it needs another 2GB space to extract and pull the libwidevine.so.
Why is it trying to update when the latest version is already installed. I even tried with manually changing `InputStream Helper version: 0.4.4` in the settings.xml in addon_data folder, but still wants to update widevine

These amlogic devices hardly have 2GB free on them, it would be nice to have an option to "ignore update" instead of only proving "yes or no" to update and to update later when it is absolutely necessary in cases where netflix refuse to work with the installed widevine library

Also an option that allows user to provide libwidevine.so directly in a designated folder which could be used by inputstream helper would be ideal, as in cases such as mine I have three Amlogic devices and would like to take the file from one device after it has updated and transfer it to the other boxes manually instead of going through the whole update process of downloading ChromeOS and extracting on the other two devices

Please help

**Comment by horstle** [comment]
1. Since you already have the debug log, provide it here, so we can see what happens.

2. Changing the version number makes no sense at all. Revert that.

3. To use your own libwidevinecdm.so currently you have to disable inputstreamhelper completely via its settings page (don't disable the addon itself in the info pane) and put the file in /storage/.kodi/cdm.

**Comment by Gujal00** [comment]
Thanks for the prompt response
1. The [debug log is here](https://hastebin.com/ucojuzebuc) 
2. Yes reverted it back
3. Fantastic, works nicely. Thanks for the tip.

Looks like it is asking to reinstall due to some missing conf file
```2020-03-06 21:03:16.784 T:3520058240   DEBUG: [script.module.inputstreamhelper] Widevine or Chrome OS recovery.conf is missing. Reinstall is required.```
But netflix plays fine if inputstreamhelper is disabled via settings

**Comment by horstle** [comment]
Alright, so the issue is that `WIDEVINE_CONFIG_NAME` was changed in the new release. So the fix for you would be to either reinstall once, or change the name of widevine_config.json in /storage/.kodi/cdm to manifest.json.

**Comment by dagwieers** [comment]
The related change is part of PR #193:  https://github.com/emilsvennesson/script.module.inputstreamhelper/commit/8109dc2dc4919c6941729a3add2695899db9caf4#diff-9646099702737521a584cb23e81f43c3L77-R77

I cannot remember why we modified this.

**Comment by horstle** [comment]
To be able to remove this unnecessary step:
https://github.com/emilsvennesson/script.module.inputstreamhelper/commit/8109dc2dc4919c6941729a3add2695899db9caf4#diff-ea07cc24a79fddee462a6b2b3a614b3aL577-L579

**Comment by Gujal00** [comment]
Thanks very much for the pointers, can close this (not really a) issue now :-)
