### ISSUE TITLE
Install Widevine manually it's possible ?

### ISSUE THREAD

**Issue by DjDiabolik** [emilsvennesson/script.module.inputstreamhelper#292]
Whit Mediaset Play addons:
https://github.com/phate89/Mediaset-Play-plugin.video.videomediaset

At now it's present a film say it's need Widevine......

I use kodi on latest osmc stable image installed on my Pi2..... from "inputstreamhelper" settings there's a option to install Widevine but it's say i need about 2GB of storage for pick Google OS image.

At this point it's question:
I can download this OS from a pc for example from windows and extract all files and after that put on my actually osmc installation ?

**Comment by horstle** [comment]
Yes, it is possible, but why do you want to do that? If you don't have enough free disk space, you could plug in a usb flash drive and specify that as custom temporary path. The 2GB are only needed for a short time to extract the library. After the installation is finished it should only use roughly around 10MB.

**Comment by pejobo** [comment]
I had the same desire some time ago. Reason for me is that I do not want to grant root permissions to the kodi user.

I created the following python script by shamelessly copying code taken from this repository: https://gist.github.com/pejobo/66d6363dcd819023e28fc05a9b44522d

I made minor changes so that it can run without root permissions. Therefore it now depends on 7zip installed on the system.

It`s only tested arch linux arm on a Raspberry Pi 2.

**Comment by dagwieers** [comment]
This is interesting and relates to #72, although getting 7zip on all ARM devices is going to be hard to impossible. And it only fixes the needed root-access, but doesn't help in preserving disk space for the extraction (as we would like to see).

**Comment by horstle** [comment]
The problem with root access would be solved by #267 , at least on systems with udisks2 installed.

**Comment by pejobo** [comment]
udisks2 isn`t installed on my system. But the same was true for p7zip before I used it for installing widevine..

**Comment by DjDiabolik** [comment]
> 
> 
> Yes, it is possible, but why do you want to do that? If you don't have enough free disk space, you could plug in a usb flash drive and specify that as custom temporary path. The 2GB are only needed for a short time to extract the library. After the installation is finished it should only use roughly around 10MB.

Wait a moment............ i have setup a SSH whit a root user on my osmc installation.
If i can use a script command from a usb pendrive correctly mounted used a ssh session how i can found this command ?

**Comment by pejobo** [comment]
This is the same use case I wrote the linked script for (see gist link). Just add the appropriate `mv` commands as last step and you are good to go.

**Comment by horstle** [comment]
@DjDiabolik 
If you want to use the usb drive as custom temporary path, in Kodi go to the addons section, find and open Inputstream Helper. There should be an option "Custom temporary path", were you can specify a directory on your usb. After that, please close and reopen that page (so the setting gets stored) and click on "(re)install widevine cdm".

**Comment by dagwieers** [comment]
I think we could check for any of these and prefer whatever works over requiring root access. So the more alternatives, the better.

**Comment by DjDiabolik** [comment]
> 
> 
> @DjDiabolik
> If you want to use the usb drive as custom temporary path, in Kodi go to the addons section, find and open Inputstream Helper. There should be an option "Custom temporary path", were you can specify a directory on your usb. After that, please close and reopen that page (so the setting gets stored) and click on "(re)install widevine cdm".

oH YEAH... great suggestion :)
I will try later tonight. I need also to free some space from my currently connected pendrive :)

**Comment by DjDiabolik** [comment]
hi @dagwieers i have see yout invitation but i need to enable two-step verification to this my github account to access on it.
I have tryed but apparently i can't do this..... i need some investigation over it because i can't.

Damn.........

**Comment by dagwieers** [comment]
@DjDiabolik It was because you helped translate the YouTube add-on to Italian that I invited you to the Italian translation team. We would like to bring translators together so we can have a concerted effort to translate a few of those important add-ons (YouTube, Netflix, inputstreamhelper, Up Next, inputstream.adaptive, HBO, etc.) to more languages.

**Comment by DjDiabolik** [comment]
@dagwieers are you italian ? We can speak italian in this group ?? Really damn so good :)
You don't have idea... google translator he has become my best friend lately... lol.

**Comment by dagwieers** [comment]
@DjDiabolik I am not Italian ;-) But we do need Italian translators for a few other add-ons, and in the meantime we already have 3 Italian translators joining the project. You can see some progress here: https://github.com/add-ons/translations/issues

**Comment by matt-the-bat** [comment]
I have a usb drive installed and set the tmp directory there. Installation fails with an OSError Errno 18. Changing the  os.link call to os.symlink fixes the issue

**Comment by horstle** [comment]
That was fixed in #296 .

**Comment by matt-the-bat** [comment]
> That was fixed in #296 .

Thanks, friend!

**Comment by horstle** [comment]
Can this be closed? It's gone a little off-topic, but I think everything discussed here is either resolved or tracked in another issue.

**Comment by dagwieers** [comment]
@horstle Sure, you can hide comments that are off-topic and close an issue with a motivation. If for whatever reason people disagree, we will know :-)

**Comment by horstle** [comment]
Ok, so since @DjDiabolik didn't report back, I'll assume https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/292#issuecomment-597183564 worked. I'm going to close this, but if there is any further problem, feel free to reopen or create a new issue.

**Comment by DjDiabolik** [comment]
Oh sorry.. yes... can close whitout problems :)
