### ISSUE TITLE
Coercing to unicode Error

### ISSUE THREAD

**Issue by spikerguy** [emilsvennesson/script.module.inputstreamhelper#294]
Bug report
Your Environment
Netflix add-on version: 1.0
Operating system version/name: Manjaro Linux - Arch - Aarch64
Device model: Pine64 PineBook Pro
Used Operating system:

 Linux - Aaarch64
Describe the bug
Coercing to unicode error while uncompressing Widevine CDM

Expected behavior
After uncompressing it tries to run some python package and fails, Assuming I have python2.7 and python3.8 installed.

Your Environment
Manjaro Linux with Kde Plasma compiled kodi for aarch64 using gles and panfrost driver. Video playback is quite smooth but trying to get netflix to work. 64bit userspace is used.

Steps to reproduce the behavior
Installed plugin.video.addon
Logged in to Netflix and tried playing a movie, this ask for permissions to download Chrome OS image and then after downloading it tries to uncompress it.
While uncompressing I get the Coercing to unicode error and the uncompressing box stays on until I close kodi.
Possible fix
Looks like a python issue.

Debug log
The debug log can be found from this link:
https://pastebin.com/6zb7S3G1

Installation
Installed this plugin from the git wiki.

Screenshots
**Uncompressing**
![image](https://user-images.githubusercontent.com/48839029/76698791-0741f480-66b8-11ea-8e97-dfcaa86bfd51.png)

**IMG_Coering**
![image](https://user-images.githubusercontent.com/48839029/76698790-03ae6d80-66b8-11ea-9d82-90a81b81767a.png)

**Comment by mediaminister** [comment]
It seems you provided just a simple standard log, without specific debug log messages from InputSteamHelper. I can't investigate where it goes wrong. Can you please provide a **full debug log**, following the instructions here: https://kodi.wiki/view/Log_file/Easy

**Comment by horstle** [comment]
This could possibly be related to #253 since it fails at the same point, although with a different error.

**Comment by spikerguy** [comment]
I will try to get the detailed log by tomorrow.  Have anyone tested Netflix on 64bit userspace? 

Afaik it needs 32bit userspace for the plugin to make use of chromeos binaries.

**Comment by spikerguy** [comment]
Hello,
Here is the logs.
https://paste.kodi.tv/poliyecaqo.kodi

**Comment by horstle** [comment]
Ok, so `_set_loop_dev()` fails with permission denied, so `_loop_dev` is None, resulting in `_losetup()` crashing.

Even if `losetup -f` worked, you don't have passwordless sudo enabled.
A quick fix would be to install udisks2 and this version of the addon: https://github.com/horstle/script.module.inputstreamhelper/archive/udisksctl_no_sudo.zip

**Comment by spikerguy** [comment]
I will try this now, But again i have the same question. I have 64bit kernel with 64bit userspace. Do you think widevine will work ?

**Comment by dagwieers** [comment]
@spikerguy No, Widevine will not work as we only have a 32bit ARM Widevine CDM.

**Comment by horstle** [comment]
Sorry, hadn't seen your question. Still, `_losetup()` should probably check `_loop_dev` before using it.

**Comment by mediaminister** [comment]
> No, Widevine will not work as we only have a 32bit ARM Widevine CDM.

So, this bug can't be fixed?

**Comment by dagwieers** [comment]
@mediaminister I thought we checked for a 64bit userspace. So either this is a 32bit userspace or our checks are not working correctly.

**Comment by spikerguy** [comment]
> @mediaminister I thought we checked for a 64bit userspace. So either this is a 32bit userspace or our checks are not working correctly.

I can confirm its a 64bit userspace as we only maintain aarch64 for Manjaro. So maybe the test didn't detect that.

**Comment by horstle** [comment]
The check for 64bit is inside `_missing_widevine_libs` which is executed by `_check_widevine` only **after** the installation. I think it should be a separate function which can then be called earlier.

**Comment by mediaminister** [comment]
We definitely messed up checks. I looked at [Chromium source](https://chromium.googlesource.com/chromium/src/+/refs/heads/master/third_party/widevine/cdm/widevine.gni) and saw the following:

```gni
# Widevine CDM is available as a library CDM on the following platforms and
# architectures. Notably on Android library CDM is not used and Widevine is
# supported via Android MediaDrm API.
# TODO(hmchen): Provide support on "arm64".
library_widevine_cdm_available =
    (is_chromeos && (target_cpu == "x64" || target_cpu == "arm")) ||
    (is_desktop_linux && (target_cpu == "x86" || target_cpu == "x64")) ||
    (is_mac && target_cpu == "x64") ||
    (is_win && (target_cpu == "x86" || target_cpu == "x64"))
```

And then I looked at InputStreamHelper source:

https://github.com/emilsvennesson/script.module.inputstreamhelper/blob/d21bfa9d1af483c9f2cc6b024e00e51a808653df/lib/inputstreamhelper/config.py#L38-L43

So, `arm64` is not supported and I guess removing `arm64` from `WIDEVINE_SUPPORTED_ARCHS` should fix this.

In addition, there shouldn't be any check for platforms, userspaces or architectures in `_missing_widevine_libs`! This should be done in `_supports_widevine`
https://github.com/emilsvennesson/script.module.inputstreamhelper/blob/d21bfa9d1af483c9f2cc6b024e00e51a808653df/lib/inputstreamhelper/__init__.py#L137-L161

And `arch` already takes care of the 32-bit userspace on ARM, I'm not sure this is the right place to do this.

https://github.com/emilsvennesson/script.module.inputstreamhelper/blob/d21bfa9d1af483c9f2cc6b024e00e51a808653df/lib/inputstreamhelper/utils.py#L235-L256

The architecture checks definitely need a clean-up...

**Comment by dagwieers** [comment]
Beware that arm64 is supported:
1. on Android (but we immediately handle that before arch check IIRC)
2. when we have a 32-bit userspace

I think (2) is why arm64 is listed as supported, and the userspace check is performed later...

**Comment by dagwieers** [comment]
The good news is that arm64 support is coming. And I wonder if there isn't already a pure 64-bit ChromeOS image available somewhere?

**Comment by spikerguy** [comment]
> The good news is that arm64 support is coming. And I wonder if there isn't already a pure 64-bit ChromeOS image available somewhere?

I hope the newer chromebook they release will use 64-bit version.
Afaik 64bit version is in the todo list of chrome since 2 years now.  Is there any confirmed news of 64-bit chromOs release anytime soon?

**Comment by mediaminister** [comment]
I moved the userspace detection to `_supports_widevine`, the following zip package should fix the crash and show the user an appropriate error message when trying to install Widevine on ARM64 with 64-bit userspace:
[script.module.inputstreamhelper-0.4.5-userspace-2117ce8.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4464803/script.module.inputstreamhelper-0.4.5-userspace-2117ce8.zip)
[script.module.inputstreamhelper-0.4.5+matrix.1-userspace-2117ce8.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4464802/script.module.inputstreamhelper-0.4.5%2Bmatrix.1-userspace-2117ce8.zip)

Please report if this works as expected.

**Comment by spikerguy** [comment]
@dagwieers Do you have real evidence of the good news you're talking about? As it kinda gets me excited to know we can have widevine on arm64 but I don't want to get my hopes high. 

@mediaminister I will try it on my pinebookpro tonight and share the feedback.

**Comment by dagwieers** [comment]
@spikerguy In the informatio above it was stated (on 2018-10-01) that:

> # TODO(hmchen): Provide support on "arm64".

**Comment by spikerguy** [comment]
> @spikerguy In the informatio above it was stated (on 2018-10-01) that:
> 
> ```
> # TODO(hmchen): Provide support on "arm64".
> ```
[Google Source](https://chromium.googlesource.com/chromium/src/+blame/HEAD/third_party/widevine/cdm/widevine.gni#16)

Lol yea this is the same link we had been following but its there since 2 years now without any update to it.

**Comment by spikerguy** [comment]
@mediaminister tested the updated package now as soon as I try to play a Netflix video it informs be that widevine is not available  for ARM64.
Screenshot.
![IMG_20200411_234312](https://user-images.githubusercontent.com/48839029/79054553-7b879d80-7c4e-11ea-869e-9913f49bd046.jpg)

@dagwieers I will wait for arm64 native support, hoping its coming soon :(

Thanks team for all the friendly response.

**Comment by mediaminister** [comment]
Thanks for reporting, it works as intended.

I also hope arm64 native support is coming soon.
