### ISSUE TITLE
Invalid Cross-device Link when downloading Widevine

### ISSUE THREAD

**Issue by dencrypt** [emilsvennesson/script.module.inputstreamhelper#295]
Hi!

Running Kodi 18.4 on Manjaro Linux.

My Netflix stopped working a while back but it seems not to be the Netflix plugin that was the culprit but the inputstreamhelper. When trying to download the Widevine library I get a "Invalid Cross-device Link" error. It's the same if I use the netflix or through the inputstreamhelper directly.
[kodi2.log](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4370138/kodi2.log)

I've checked all paths and I do have the rights needed to write to the folders where they would put the downloaded file.

**Comment by horstle** [comment]
I should have added AttributeError to OSError in #261 rather than replacing OSError, sorry.

Will create a PR in a few hours.
