### ISSUE TITLE
GitHub CI matrix release management

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#299]
So with the add-on changes for Matrix that require different ZIP packages for pre-Matrix and post-Matrix, there is a clean and simple solution through GitHub CI. We can automatically build and push new packages to the release page.

So we could add a tag `matrix` and define a draft `Matrix` release. On every PR and push, we can build this Matrix-compatible ZIP file, and release it as an attachment to the `Matrix` releases. That would give us a ZIP package for each PR and one for the latest devel branch (which we may have to clean up after a new release).

It is not that hard to do this and would make a real difference to get people to test PRs for fixes, or test-drive on Matrix.

**Comment by mediaminister** [comment]
I am in favor of continuing to use a single codebase that is compatible with both Matrix and Krypton/Leia. So using a separate `matrix` tag or a `Matrix` release doesn't make sense to me.

But we could instead use a _development release_ tag, for instance `0.4.5-dev` or `0.4.5-beta` and generate zip packages for both Matrix and Krypton/Leia.

The only difference between pre-Matrix and post-Matrix in fact is a couple of version numbers in `addon.xml` that can be changed _on the fly_ while building two different zip packages, one for Matrix and one for the earlier Kodi versions. (As explained in this PR: https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/293#issue-386721578

**Comment by dagwieers** [comment]
The tag would just be to have an entry in the releases page to add released ZIP files to (automatically), it wouldn't be used for anything else. So we are basically saying the same thing. Let me create the GitHub CI workflow to showcase this.

**Comment by mediaminister** [comment]
Okay, I look forward to your pull request.

**Comment by mediaminister** [comment]
With the release of v0.4.5 I tested a completely automated workflow: https://github.com/mediaminister/script.module.inputstreamhelper/runs/568560499

Based on https://github.com/xbmc/action-kodi-addon-submitter

**Comment by dagwieers** [comment]
Maybe there is a possibility to use the GitHub Packages interface for listing releases as well.

**Comment by mediaminister** [comment]
Is there a use case for Github Packages? This package only runs in Kodi...

**Comment by dagwieers** [comment]
@mediaminister I was hoping it would be useful as a store for our ZIP files, rather than making it part of a package-specific repository.

But I guess Matrix users either use the official releases, or have to modify the package themselves. Let's close this.
