### ISSUE TITLE
Adhere to Kodi Add-on structure guidelines

### ISSUE THREAD

**Issue by asciidisco** [emilsvennesson/script.module.inputstreamhelper#3]
I´ve briefly checked the Add-on structure & would like to make some suggestions based on the Kodi [guidelines](http://kodi.wiki/view/Add-on_structure) for Add-ons:

1.) The `lib` folder should be placed within the `resources` folder, see [Section 3.9.3](http://kodi.wiki/view/Add-on_structure#resources.2Flib.2F)

2.) The `art` folder should be dropped and the icon should be directly placed in the `resources` folder, see [Section 1.4.2.1.13](http://kodi.wiki/view/Addon.xml#.3Cassets.3E)

3.) The Changelog file should be dropped in favour of the `<news/>` section in the `addon.xml`, see: http://kodi.wiki/view/Addon.xml#.3Cnews.3E

I know, just a few tiny things (which seems like nitpicking), but they need to be done if the Add-on enters the formal approval process ;)

**Comment by emilsvennesson** [comment]
1.) As I've understood it, this applies to add-ons but not modules. I actually used a module already in the official repository (https://github.com/timewasted/script.module.m3u8) as base and it seems like they all have the `lib` folder in the root. It's not really clear though and confused me quite a bit as well.

2.) I think (?) this should be fine, and I've used the `art` folder structure in other add-ons that's in the official repository. It's kind of superfluous here though seeing as we only have an icon so I'll move it to the `resources` folder anyway.

3.) I think it makes sense to keep the changelog.txt for a complete changelog across all versions and then use the `<news/>`  tag to display what's changed in the latest version. Thoughts about this?

Thanks a lot for you suggestions! :-)

**Comment by asciidisco** [comment]
1.) Absolutely confused by this as well :D 
I think they´ve changed the layout when moving from Kodi 16 to 17, but in the end, it´s a minor detail.

2.) Probably fine as well. But as you said, as it´s just one file, it makes sense to move it up.

3.) Agree. Makes no sense to completely drop it, adding the `<news/>` section additionally seems to be a good thing though.

I´m happy with this being closed :)

**Comment by emilsvennesson** [comment]
@asciidisco Perfect. :-) I've added the news tag and moved the icon now.

Closing.
