### ISSUE TITLE
Download times out

### ISSUE THREAD

**Issue by Mintux92** [emilsvennesson/script.module.inputstreamhelper#305]
Good morning,
I am installing neflix on libreelec. Netflix installs without problems, when I try to log in it asks me to install the various addons but when it tries chrome os at some point it stops and in the logs I find what I attach. How could I solve it?

KODI 18.2
ARCHITECTURE: RPi 3 B+
Repository: Castagnait Repository 1.1.1

log:
```
2020-04-05 20:49:55.974 T:1545548656 ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 182, in run
route([part for part in g.PATH.split('/') if part])
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 33, in lazy_login_wrapper
return func(*args, **kwargs)
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 57, in route
play(videoid=pathitems[1:])
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/videoid.py", line 294, in wrapper
return func(*args, **kwargs)
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 133, in timing_wrapper
return func(*args, **kwargs)
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 72, in play
list_item = get_inputstream_listitem(videoid)
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 144, in get_inputstream_listitem
if not is_helper.check_inputstream():
File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/init.py", line 1053, in check_inputstream
return self._check_drm()
File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/init.py", line 1008, in _check_drm
return self.install_widevine()
File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/init.py", line 776, in install_widevine
return self._install_widevine_arm()
File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/init.py", line 703, in _install_widevine_arm
downloaded = self._http_download(url, message=localize(30022), checksum=arm_device['sha1'], hash_alg='sha1', dl_size=int(arm_device['zipfilesize'])) # Downloading the recovery image
File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/init.py", line 414, in _http_download
chunk = req.read(chunk_size)
File "/usr/lib/python2.7/socket.py", line 384, in read
File "/usr/lib/python2.7/httplib.py", line 597, in read
File "/usr/lib/python2.7/socket.py", line 384, in read
File "/usr/lib/python2.7/ssl.py", line 772, in recv
File "/usr/lib/python2.7/ssl.py", line 659, in read
SSLError: ('The read operation timed out',)
2020-04-05 20:50:12.348 T:1936587152 ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.netflix/play/movie/81033429/?profile_guid=NPDMLGKCNBEABNDKVTJBXE6DSE]
```

**Comment by mediaminister** [comment]
Can you please update InputStreamHelper to v0.4.5 and try again and provide [a full debug log](https://kodi.wiki/view/Log_file/Easy) if the error happens again? 
It seems there was a problem with the internet connection and the download of Widevine failed.

Apart from providing a nicer error message there is nothing we can do about a failing internet connection.

**Comment by AlleSchonWeg** [comment]
I had the same problem. Problem was, if i use a newer kodi version, kodi disabled most of my addons. So i decided to downgrade. The solution was to disable the widevine check in inputstreamhelper.

**Comment by dagwieers** [comment]
@AlleSchonWeg In that case you can simply disable inputstreamhelper from the settings.

**Comment by horstle** [comment]
So, what should be done about this? I could think of these options:
* Increase the timeout introduces in #275 (not sure that helps much)
* Catch the error and return False
* Catch the error and ask whether the download should be restarted
* Catch the error and retry to read that chunk (idk if that's even possible, or if the stream would have moved its position)

**Comment by dagwieers** [comment]
@horstle The urlopen timeout in PR #275 is a connection timeout, and IMO should not be set to 5 seconds. When you have a bad connection lowering the connection timeout seems the wrong thing to do IMO. I don't understand why the PR talks about it influencing the "chunk download".

**Comment by horstle** [comment]
> When you have a bad connection lowering the connection timeout seems the wrong thing to do IMO.

I didn't propose to lower it, but to __increase__ it. Afaik the default value should be None (i.e. no timeout), but I assumed it would be set to something smaller in Kodi. If that's not the case #275 makes no sense.

> I don't understand why the PR talks about it influencing the "chunk download".

Well, according to the docs that timeout is for "blocking operations", but idk if calling read is considered to be one.

**Comment by dagwieers** [comment]
That's is what I am saying. PR #275 makes no sense. It would be good to understand the use-case where this did help though...

**Comment by mediaminister** [comment]
> Afaik the default value should be None (i.e. no timeout)

Indeed, this means that if your internet goes down while downloading, `urlopen` will wait forever to get data.

> Catch the error and retry to read that chunk (idk if that's even possible, or if the stream would have moved its position)

That's totally possible using the http range header, I implemented a working example:
(You can turn off and on your internet connection while downloading to test.) 
```python
# -*- coding: utf-8 -*-

from __future__ import absolute_import, division, print_function, unicode_literals
import os
import time
from socket import timeout
from ssl import SSLError

try:  # Python 3
    from urllib.request import Request, urlopen
    from urllib.error import URLError
except ImportError:  # Python 2
    from urllib2 import Request, URLError, urlopen


def run():
    url = 'https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_12739.111.1_bob_recovery_stable-channel_mp.bin.zip'
    zipfilesize = 1017204780
    filename = url.split('/')[-1]
    download_path = os.path.join(os.getcwd(), filename)

    chunk_size = 32 * 1024
    position = 0
    begin = 0
    end = zipfilesize
    with open(download_path, 'wb+') as image:
        while position < zipfilesize:
            headers = {'Range': 'bytes=%s-%s' % (begin, end)}
            req = Request(url, headers=headers)
            try:
                result = urlopen(req, timeout=5)
                while position < zipfilesize:
                    data = result.read(chunk_size)
                    if data:
                        image.write(data)
                        position = image.tell()
                        percent = position / zipfilesize * 100
                        print('downloading %d %%' % percent, end='\r')
            except (timeout, URLError, SSLError) as exc:
                print('internet is down', end='\r')
                begin = position
                time.sleep(0.5)
    print('download is ready')


if __name__ == '__main__':
    run()
```

**Comment by horstle** [comment]
Did you check the hash of the resulting file? While reading your code I get the impression it might write the first 32KiB of the zipfile again and again, until the wanted size is reached.

**Comment by horstle** [comment]
I hadn't seen the header specifying the beginning. I can confirm the checksums always match, with or without losing network connection.

**Comment by horstle** [comment]
> Well, according to the docs that timeout is for "blocking operations", but idk if calling read is considered to be one.

I can now confirm this. The read times out after the seconds specified in urlopen.

**Comment by mediaminister** [comment]
>  I think it wouldn't hurt to increase the timeout a little.

10 seconds is okay for me.
