### ISSUE TITLE
Option to disable inputstreamhelper in settings + manual download cdm over GUI settings

### ISSUE THREAD

**Issue by JohnPlayerSpecial2018** [emilsvennesson/script.module.inputstreamhelper#32]
Please work in 2 settings over GUI (maybe in inputstream.adaptive addon settings). It improves usability and avoids workaround over ssh:

1) "Option to disable inputstreamhelper" -> Not everybody has enabled automatic addon updates and updating cdm on an older inputstream.adaptive can cause incompatibility. Would be more user-friendly to have this option also over GUI.

2) Manual download cdm -> If users reject cdm update once (because of staying on older/incompatible inputstream.adaptive version, temporal reasons, by mistake..), there is no other chance for updating over Kodi GUI as to wait until inputstreamhelper asks again (this can take long time..).

**Comment by horstle** [comment]
I actually worked on something similar over here: [https://github.com/horstle/script.module.inputstreamhelper/tree/temp_disable](https://github.com/horstle/script.module.inputstreamhelper/tree/temp_disable)

I don't really like the code about manually running the helper and temporary disabling is currently not working if I remember correctly. Anyways making the "option to disable" visible is only a tiny change, I'll create a PR soon (probably today). After that it will be possible to change the setting by going to the kodi settings > system (change from standard to expert there) > addons > manage dependencies > Inputstream Helper > configure.
