### ISSUE TITLE
inputstreamaddon to be deprecated

### ISSUE THREAD

**Issue by phunkyfish** [emilsvennesson/script.module.inputstreamhelper#320]
https://forum.kodi.tv/showthread.php?tid=353560

I noticed it is given as a reference in the README file. Only applies to Matrix.

**Comment by mediaminister** [comment]
Thanks for letting us know. I updated the code example in the README file so it will work both on Kodi Matrix and older Kodi versions.

**Comment by phunkyfish** [comment]
No problem
