### ISSUE TITLE
cannot import name link when trying to install widewine in Netflix

### ISSUE THREAD

**Issue by Matheos96** [emilsvennesson/script.module.inputstreamhelper#346]
Add-on version: 0.4.6
Operating system: Windows 10

I recently installed the Netflix addon by CastagnaIT on my Windows 10 machine running the latest Kodi Leia 18.6. I have been able to log in and everything so that is okay. When I try to play my first video it obviously asks me to install widewine. I accept and agree to the terms but straight after I get given the following:

Netflix Add-on Error
The addon encountered the following error: ImportError: cannot import name link

The debug log can be found from this link: https://paste.ubuntu.com/p/rtNVpQ4P74/

From the log we can see that it is inputstreamhelper that throws this error.
I have tried reinstalling it
Any ideas?

**Comment by horstle** [comment]
#332 fixed this. v0.4.7 was already released with this fix, should be in the repo soon.

**Comment by Matheos96** [comment]
> #332 fixed this. v0.4.7 was already released with this fix, should be in the repo soon.

Yea sorry lol. I just found the issue covering it. Was just about to go ahead and close this issue.
