### ISSUE TITLE
Not able to use

### ISSUE THREAD

**Issue by ddmakadia1699** [emilsvennesson/script.module.inputstreamhelper#347]
After unzipping it is showing one or more ..... failed. Something like this. 
It is downloading but not able to use. 
failed every time.

**Comment by horstle** [comment]
Do you already have v0.4.7 installed? If not, try that. It most probably fixes your issue. It should be in the repo now, so simply update inputstreamhelper.

**Comment by mediaminister** [comment]
@ddmakadia1699 Please provide a full debug log if this is not fixed in [v0.4.7](https://github.com/emilsvennesson/script.module.inputstreamhelper/releases/tag/v0.4.7): https://kodi.wiki/view/Log_file/Easy
