### ISSUE TITLE
InputStream Helper Add-on error

### ISSUE THREAD

**Issue by zacheasow** [emilsvennesson/script.module.inputstreamhelper#358]
I was trying to run Netflix on the Raspberry Pi 4B with Kodi. I was able to get Netflix, but when I was installing Widevine CDM for playback, there would always be an error saying: InputStream Helper Add-on error. What should I do?

**Comment by horstle** [comment]
Please provide a debug log.
https://kodi.wiki/view/Log_file/Easy
