### ISSUE TITLE
Can't install widevine (Kodi + Amazon addon + Raspberry Pi)

### ISSUE THREAD

**Issue by aitormendez** [emilsvennesson/script.module.inputstreamhelper#361]
Sorry if it is a duplicate (I cannot confirm it with my little knowledge). The popup window asked me to ask for help here.

After install Amazon VOD addon in Kodi 18.6 and try to see video content, a popup window with missing libraries is shown, prompt me to install them.

`2020-06-06 18:10:01.287 T:1504415968   ERROR: [script.module.inputstreamhelper] Widevine is missing the following libraries: [u'libnss3.so', u'libnssutil3.so', u'libnspr4.so']`

Line 2572 in log: https://paste.kodi.tv/abisisisit.kodi

After hit OK button, a new pop up appears with the error. There are a pictures of the screen here: https://imgur.com/a/ksQY6cg

If I try to do the same again (install libraries hitting the OK button) there is no more pop up window with the error. Just the first try is shown the pop up.

Thank you for the help.

**Comment by horstle** [comment]
Running `sudo apt install libnss3` should fix that.

**Comment by aitormendez** [comment]
Yes! Thank you.
