### ISSUE TITLE
{"error":{"code":-32602,"message":"Invalid params."},"id":1,"jsonrpc":"2.0"}

### ISSUE THREAD

**Issue by brianjmurrell** [emilsvennesson/script.module.inputstreamhelper#37]
I'm trying to get the Kodi [Netflix addon](https://github.com/asciidisco/plugin.video.netflix) to work on a Kodi 18 installation.  Everything works until I select an episode and then I get this right before it fails to play:

```
17:27:17.126 T:140508056471296   DEBUG: [script.module.inputstreamhelper-0.3.3]: Platform information: ('Linux', 'pc.example.com', '4.18.16-300.fc29.x86_64', '#1 SMP Sat Oct 20 23:24:08 UTC 2018', 'x86_64', 'x86_64')
17:27:17.126 T:140508056471296   DEBUG: [script.module.inputstreamhelper-0.3.3]: jsonrpc payload: {'params': {'addonid': 'inputstream.adaptive'}, 'jsonrpc': '2.0', 'id': 1, 'method': 'Addons.GetAddonDetails'}
17:27:17.129 T:140508056471296   DEBUG: [script.module.inputstreamhelper-0.3.3]: jsonrpc response: {"error":{"code":-32602,"message":"Invalid params."},"id":1,"jsonrpc":"2.0"}
17:27:17.130 T:140508056471296   DEBUG: [script.module.inputstreamhelper-0.3.3]: inputstream.adaptive is not installed.
```

Just hoping on the odd chance that somebody knows what that is before I start piling on and through debug.

**Comment by horstle** [comment]
In the last line it says inputstream.adaptive is not installed, so you need to install it (usually as an addon).

**Comment by vlmaksime** [comment]
Looks like You need to instal inputstream.adaptive manually: https://forum.kodi.tv/showthread.php?tid=323459

**Comment by brianjmurrell** [comment]
Yeah.  Needed to install it from the O/S package database.
