### ISSUE TITLE
Invalid setting type

### ISSUE THREAD

**Issue by horstle** [emilsvennesson/script.module.inputstreamhelper#388]
I recently saw a debug log of a standard LibreELEC installation and it had a line:
`EXCEPTION: Invalid setting type`

It seems that the call to `getSettingNumber` in `get_setting_float` fails with a type error, when called on `last_check` or `last_modified`, e.g. in `info_dialog`. That's not really a problem, since it is handled by `get_setting_float`, but still should be looked into.
Even after changing `getSettingNumber` to `getSettingInt` and changing both values to a small integer it still produced the same error, but when I changed the lines in `info_dialog` to read the values of `update_frequency`, the error vanished, even though it looked exactly the same in the settings.xml.

When I realised this I also thought again about the problem that both these values aren't stored if installing from the settings page and exiting the page with the "Abort" button afterwards. So I thought maybe we should create an independent xml/json/... file to store those values instead of hiding them in the settings. That would avoid both these issues. What do you think?

**Comment by dagwieers** [comment]
I would prefer to keep it in the *settings.xml* if possible. I guess we have to figure out what is going on and if needed, get this fixed upstream if it is a bug...

**Comment by horstle** [comment]
Ok, some more things I tried:
* Set the values with setSettingNumber - that didn't change anything
* Specify `type="number"` in the settings.xml - after that they couldn't be read at all and the settings page had an additional tab...

**Comment by mediaminister** [comment]
I found out two things:
- `type="number" `can only be used for integers, so `getSettingNumber` is useless.
- invisible settings  with` type="number"` need to be in a category otherwise an empty tab is shown.
