### ISSUE TITLE
Get segment encryption data

### ISSUE THREAD

**Issue by ah-ma** [emilsvennesson/script.module.inputstreamhelper#390]
Hi,
I work on a website that uses com.widevine.alpha to decrypt the video for streaming and i have access to the original unencrypted video, the playlist and all the license url,
I need to basically embed watermarks to the video depending on the requesting user's data, so i need to decrypt some of the segments manually, embed the watermark, then reencrypt the segments again.
I have been studying on the subject for a while but it seems that the com.widevine.alpha module deciphers the license key and returns a class with the key inside instead of just a plain key.
Is it achievable and can i do it through this great library?
Thx.

**Comment by dagwieers** [comment]
Not possible. This project is something else, for more information read the README.
