### ISSUE TITLE
Widevine broken on update: x86 lib on ARM ?

### ISSUE THREAD

**Issue by amateusz** [emilsvennesson/script.module.inputstreamhelper#395]
Hi, I think automatic update has just broken my setup.

I'm on Raspberry Pi 2, OSMC `4.19.122-1-osmc #1 SMP PREEMPT Wed May 27 07:09:59 UTC 2020 armv7l`
OSMC `VERSION_ID="2020.06-1"`

---
I started [some DRM-dependent plugin](https://github.com/asciidisco/plugin.video.netflix), I was asked to update Widevine so I did let it finish; it did so nicely (I checked if there is enough disk space prior).
Then I couldn't play the video.
I checked the logs (`~/.kodi/temp/kodi.log`) and it was complaining for _something Widevine_ - I don't have this log unfortunatelly. Kodi rotates them so quickly (?)

But here is what I noticed:
```
~/.kodi$ file cdm*/libwidevinecdm.so
cdm_bak/libwidevinecdm.so:   ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=2790b672c54a8c529f679751324dd48b323f3d0b, stripped
cdm/libwidevinecdm.so:       ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=7b1ce3ce3c0d0ee6591e1cf2d6cdc61de62c2178, stripped
```
I'm not sure how your folder structure works, but contents of `backup` folder are like this:
```
~/.kodi/userdata/addon_data/script.module.inputstreamhelper/backup$ file */libwidevinecdm.so
12739.111.1/libwidevinecdm.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=b0096d0863ff56a0b62a3e33f20a8b5dcb029060, stripped
13020.67.0/libwidevinecdm.so:  ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=0518f32c249a91d353237a2712aa9264ec8a8f6a, stripped
13020.82.0/libwidevinecdm.so:  ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=0518f32c249a91d353237a2712aa9264ec8a8f6a, stripped
13020.87.0/libwidevinecdm.so:  ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=0518f32c249a91d353237a2712aa9264ec8a8f6a, stripped
13310.91.0/libwidevinecdm.so:  ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=7b1ce3ce3c0d0ee6591e1cf2d6cdc61de62c2178, stripped
```

My guess is that the update process got it wrong and downloaded the x86 version instead of the ARM one.

I manually replaced one of the ARM backups into `.kodi/cdm/` and now it works

**Comment by jakubcermak** [comment]
Hi, I have the same issue, also the same fix helped me.
Using raspi4 and LibreElec 9.2.5
Log: http://paste.kodi.tv/uxurituqab 
Most interesing part of the log is the:
`
020-10-01 21:54:41.802 T:2664858480   ERROR: [script.module.inputstreamhelper] [u'ldd', u'/storage/.kodi/cdm/libwidevinecdm.so'] cmd failed.
2020-10-01 21:54:41.803 T:2664858480   DEBUG: [script.module.inputstreamhelper] [u'ldd', u'/storage/.kodi/cdm/libwidevinecdm.so'] cmd output:
                                            **$	not a dynamic executable**
2020-10-01 21:54:41.803 T:2664858480   ERROR: [script.module.inputstreamhelper] Failed to check for missing Widevine libraries.
`

I have used [this script](https://gist.github.com/ruario/3c873d43eb20553d5014bd4d29fe37f1) to download correct libwidevinecdm.so and now it works.

**Comment by horstle** [comment]
Hi, thanks for all the detailed info. It seems we have a wrong entry in CHROMEOS_RECOVERY_ARM_HWIDS in lib/inputstreamhelper/config.py. I'll fix it in a few hours.

For the future: You can simply revert to a previous version by opening the inputstreamhelper addon and chosing "revert from backup" (or whatever it's called).

**Comment by angelitto2005** [comment]
Same issue here. I'm using 
OSMC. Kodi 18.7
InputStream Helper 0.5.0
InputStream Adaptive 2.4.5
Widevine CDM version 4.10.1679.0 extracted from  Chome OS Image, PHASER 360, with version 13310.91.0.
```
2020-10-02 03:13:20.362 T:3206517472 ERROR: [script.module.inputstreamhelper] [u’ldd’, u’/home/osmc/.kodi/cdm/libwidevinecdm.so’] cmd failed.
2020-10-02 03:13:20.362 T:3206517472 ERROR: [script.module.inputstreamhelper] Failed to check for missing Widevine libraries.
2020-10-02 03:13:20.363 T:3206517472 ERROR: EXCEPTION: Invalid setting type
2020-10-02 03:13:20.364 T:3206517472 NOTICE: [script.module.inputstreamhelper] Widevine update check was made on 2020-10-02 01:22
2020-10-02 03:13:20.735 T:4068143104 NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.netflix/play/movie/81001887/?profile_guid=ODAURZY6UNDEFHAUVIVTQOCYRY
2020-10-02 03:13:20.737 T:3066004192 NOTICE: Creating InputStream
2020-10-02 03:13:22.362 T:3066004192 ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/home/osmc/.kodi/cdm/libwidevinecdm.so)
2020-10-02 03:13:22.363 T:3066004192 ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
2020-10-02 03:13:22.365 T:3066004192 ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/play/movie/81001887/?profile_guid=ODAURZY6UNDEFHAUVIVTQOCYRY]
2020-10-02 03:13:22.365 T:3066004192 NOTICE: CVideoPlayer::OnExit()
2020-10-02 03:13:22.397 T:4068143104 NOTICE: CVideoPlayer::CloseFile()
2020-10-02 03:13:22.452 T:4068143104 NOTICE: VideoPlayer: waiting for threads to exit
2020-10-02 03:13:22.452 T:4068143104 NOTICE: VideoPlayer: finished waiting
2020-10-02 03:13:27.313 T:3206517472 ERROR: [plugin.video.netflix (2)] Traceback (most recent call last):
File “/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py”, line 33, in wrapper
func(*args, **kwargs)
File “/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py”, line 249, in run
success = route(pathitems)
File “/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py”, line 90, in lazy_login_wrapper
return func(*args, **kwargs)
File “/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py”, line 126, in route
_execute(nav_handler, pathitems[1:], G.REQUEST_PARAMS)
File “/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py”, line 153, in _execute
executor(pathitems=pathitems)
File “/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py”, line 164, in timing_wrapper
return func(*args, **kwargs)
File “/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory_utils.py”, line 34, in set_custom_viewmode
override_partial_setting_id = func(*args, **kwargs)
File “/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/directory.py”, line 105, in home
list_data, extra_data = common.make_call(‘get_mainmenu’) # pylint: disable=unused-variable
File “/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/utils/logging.py”, line 164, in timing_wrapper
return func(*args, **kwargs)
File “/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py”, line 88, in make_call
return make_addonsignals_call(callname, data)
File “/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py”, line 160, in make_addonsignals_call
timeout_ms=IPC_TIMEOUT_SECS * 1000)
File “/home/osmc/.kodi/addons/script.module.addon.signals/lib/AddonSignals.py”, line 176, in makeCall
return CallHandler(signal, data, source_id, timeout_ms, use_timeout_exception).waitForReturn()
File “/home/osmc/.kodi/addons/script.module.addon.signals/lib/AddonSignals.py”, line 118, in waitForReturn
raise OSError
OSError
2020-10-02 03:13:32.048 T:3091182304 ERROR: CPythonInvoker(24, /home/osmc/.kodi/addons/plugin.video.netflix/addon.py): script didn’t stop in 5 seconds - let’s kill it
```

**Comment by angelitto2005** [comment]
@horstle, i can't revert because i did a fresh install of wivevine, last night and in Backups folder i have only 13310.91.0.
So, if you are kind, please send me a link with an earlier version of the ”libwidevinecdm.so”.

**Comment by CastagnaIT** [comment]
Problem confirmed also by other users in the forum thread (Netflix)
Another log here: https://github.com/peak3d/inputstream.adaptive/issues/519

I cannot test directly because the update has not yet arrived in my country?!

**Comment by dagwieers** [comment]
@angelitto2005 Thanks, this made it really easy to remove those affected.

We need to go over that list again, and also look for newer models that are also ARM-based (hopefully any ARM64 devices yet? :-))

**Comment by dagwieers** [comment]
@mediaminister @horstle We should update inputstreamhelper ASAP. The default update frequency is 31 days, assuming this just started 24h ago, on average 3% of users with ARM devies are impacted. Since pushing this out takes at least 24 hours, the impact will go up to 4.5% (average) or 6% (worst case).

Are we ready to release the master branch as v0.5.1, I don't see any major changes since v0.5.0.

**Comment by CastagnaIT** [comment]
just installed, this is the image downloaded
```json
{
    "sku": "",
    "sha1": "0b9f6a3a1bb74ed287864f5699639a9b21d62c2c",
    "name": "IdeaPad Flex 3 CB 11IGL05",
    "photourl": "",
    "url": "https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_13310.91.0_octopus_recovery_stable-channel_mp-v19.bin.zip",
    "hwid": "PHASER360",
    "hwids": [],
    "zipfilesize": 1449795231,
    "version": "13310.91.0",
    "filesize": 2724225024,
    "file": "chromeos_13310.91.0_octopus_recovery_stable-channel_mp-v19.bin",
    "md5": "f9620f3936214be29801d475f9ab2032",
    "hwidmatch": "^PHASER360 [G|H].{11}C.*",
    "desc": "",
    "model": "IdeaPad Flex 3 CB 11IGL05",
    "channel": "stable-channel",
    "manufacturer": "Lenovo"
}

```

**Comment by dagwieers** [comment]
### If you are affected by this issue now, follow these steps:
- Go to **Add-ons** » **Program add-ons**
- Start **InputStream Helper**
- Select and click on **Restore Widevine CDM library...**
- Pick any version, but stay away from **4.10.1582.2 (13310.91.0)**

**Comment by dagwieers** [comment]
Thanks everyone! Your reports helped to quickly address the issue before it impacted more people.

It was good to see our previous work on archiving and reverting Widevine CDM was helpful here. And we already improved InputStream Helper to better assess and prevent these issues from happening in the future.

We welcome feedback and contributions on making DRM playback in Kodi more reliable.
