### ISSUE TITLE
Canceling an update should use old Widevine CDM

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#408]
If InputStream Helper proposes to update Widevine CDM and you cancel (but you do have a widevinecdm.so library) it should attempt playback using the existing Widevine CDM and not cancel playback.

We ask to update Widevine CDM not because the existing one is failing (it might not exist, but we know this), but because sufficient time has passed to warrant an update.

**Comment by horstle** [comment]
You mean when cancelling message `#30033` `There is an update available for [B]Widevine CDM[/B].`? It alreay does what you want. If you decline there, it still tries to play.

**Comment by dagwieers** [comment]
That is not what I have experienced myself.

**Comment by horstle** [comment]
I had checked again right before posting and it worked for me. That's also what one would expect when looking at the code. The relevant lines in `_update_widevine` are https://github.com/emilsvennesson/script.module.inputstreamhelper/blob/bef0bff26bd7fc733a62ba77d3ea6261a120bba8/lib/inputstreamhelper/__init__.py#L297-L300

`_update widevine` is only called here https://github.com/emilsvennesson/script.module.inputstreamhelper/blob/bef0bff26bd7fc733a62ba77d3ea6261a120bba8/lib/inputstreamhelper/__init__.py#L326-L327

where it returns True no matter what `_update_widevine` does.

**Comment by horstle** [comment]
A few days ago I got an update message again and after cancelling playback started just fine (LibreELEC on RPi4). @dagwieers can this be closed or are you still experiencing something different?

**Comment by dagwieers** [comment]
I think this can be closed. I have not experienced this again. My bad.
