### ISSUE TITLE
Plugin can't find fdisk without specifying PATH variable

### ISSUE THREAD

**Issue by SinafdeGiraf** [emilsvennesson/script.module.inputstreamhelper#41]
I am running Kodi 18 (BETA4) on raspbian stretch.

Fdisk was installed, but the plugin could not find it, because /sbin isn't part of the PATH variable for normal users. `PATH=$PATH:/sbin kodi` fixed the issue.

**Comment by dagwieers** [comment]
@SinafdeGiraf Is this still an issue?

**Comment by dagwieers** [comment]
As I don't think this is still an issue, I am going to close this.
If you still have an issue, please reopen this ticket or report back.

**Comment by matt-the-bat** [comment]
This issue arises for me, when using cron to autostart kodi. 
Two solutions in the user crontab:
`@reboot sudo -u pi /usr/bin/kodi --standalone`
Or
`@reboot PATH=$PATH:/sbin /usr/bin/kodi-standalone`

**Comment by horstle** [comment]
This shouldn't be an issue after #327 was merged. Maybe you'd want to test it? That might help getting it merged sooner.

**Comment by matt-the-bat** [comment]
Yeah this should solve it no matter the PATH.
