### ISSUE TITLE
Missing libnss3.so on rpi3+ libreelec

### ISSUE THREAD

**Issue by AlleSchonWeg** [emilsvennesson/script.module.inputstreamhelper#418]
Hi,
after update from last milhouse rpi builds to https://test.libreelec.tv/ build(04.01.2021) i try to update widevine. It extracts the chrome os image but after installation a message appears that libnss3.so is missing.
ldd shows:
```
/storage/.kodi/cdm$  ldd libwidevinecdm.so 
	linux-vdso.so.1 (0x7effa000)
	/usr/lib/libarmmem-v7l.so (0x76790000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x76767000)
	libm.so.6 => /usr/lib/libm.so.6 (0x766fe000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x766eb000)
	librt.so.1 => /usr/lib/librt.so.1 (0x766d4000)
	libnss3.so => not found
	libnssutil3.so => /usr/lib/libnssutil3.so (0x766a1000)
	libnspr4.so => /usr/lib/libnspr4.so (0x7666a000)
	libc.so.6 => /usr/lib/libc.so.6 (0x7652a000)
	/usr/lib/ld-linux-armhf.so.3 (0x76eee000)
	libplc4.so => /usr/lib/libplc4.so (0x76f16000)
	libplds4.so => /usr/lib/libplds4.so (0x76f12000)
```
The question is: how can i install libnss3.so? apt-get isn't working on libreelec. Or is the library part of the chrome os image?

**Comment by horstle** [comment]
AFAIK libnss3.so should be included as part of LibreELEC. Maybe it didn't build that day. I'd just try a different test build.

**Comment by chris42** [comment]
I just had the same issue. January 03 seems to work

**Comment by AlleSchonWeg** [comment]
Thanks. January 03 works.
