### ISSUE TITLE
widevine  HTTP returned error 500

### ISSUE THREAD

**Issue by KyKyIIIKuH** [emilsvennesson/script.module.inputstreamhelper#420]
Hello.
Sorry if this is not the right place.
I am using inputstream.adaptive is used through inputstream.helper.

There was a 500 error, when playing DRM content.
I will be grateful for your help.

Log file:
[error_play_widevine_cdm.log](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/5784300/error_play_widevine_cdm.log)

**Comment by horstle** [comment]
That's not a problem of inputstreamhelper. Please ask the developers of plugin.video.wakanim or inputstream.adaptive.
