### ISSUE TITLE
I think I may have solved the Widevine installation problem in Kodi 18 on Raspbian

### ISSUE THREAD

**Issue by seankurth** [emilsvennesson/script.module.inputstreamhelper#44]
My Config: Raspbian Stretch Lite with vanilla LXDE and Openbix installed on top, Raspberry Pi 3B+, Kodi 18.0-1.

**Prerequisites**

1. The following instructions were tested in the Nautilus file manager, not LXDE's default PCmanFM. Install it with `sudo apt-get install nautilus` , then reboot to make sure all of the GNOME dependencies get loaded.

2. Inputstream.adaptive may be unavailable from the Kodi addon repository and need to be installed from the Terminal. To do that, open a terminal, and type `sudo apt-get install kodi-inputstream-adaptive -y`. If the package name can't be found, enter these commands in order, replacing `stretch` with the version name for whichever Raspbian version you're using if not Stretch: `sudo echo "deb http://pipplware.pplware.pt/pipplware/dists/stretch/main/binary /" > /etc/apt/sources.list.d/pipplware_kodi18.list`, `wget -O - http://pipplware.pplware.pt/pipplware/key.asc | sudo apt-key add -`, `apt-get update && apt-get dist-upgrade -y`. After all of these have completed, reboot and try `sudo apt-get install kodi-inputstream-adaptive -y` again.

3. If the helper throws the error "fdisk and parted not found on this machine," or something to that effect, run Kodi as root by typing `sudo kodi` in the terminal, then install the Netflix, Amazon, and/or Inputstream.adaptive addons as root.

**Why the automatic way doesn't work, as far as I can tell**

I downloaded the SPRING recovery image myself, and tried to convert it from a binary to an iso and mount it. bchunk failed because the file size was too large, so I looked up which other 32-bit ARM Chromebooks there are. It turns out there's an HP Chromebook, hwid "SKATE," whose recovery image is just under 600mb. I tried to convert and mount that, and it worked, So, here are the steps to get the widevine installer to download that image instead:

**Instructions**

1. Assuming you've already set everything up under a root instance of Kodi, closed it, and then opened Nautilus as root,  navigate to `/root/.kodi/addons/script.module.inputstreamhelper/lib` and open `config.py` in your text editor of your choice.

2. Change `CHROMEOS_ARM_HWID = 'SPRING'` to `CHROMEOS_ARM_HWID = 'SKATE'`, then save the file.

3. Open Kodi as root again, configure the Amazon VOD or Netflix addon with your account information, and try to play any movie that you're fine with being in your watch history.

4. You will be prompted to install Widevine, accept all of the prompts and wait.

5. The installation will eventually fail, but before it failed, it was able to extract a working `libwidevine.so`. This is all you'll need from the installer anyway. Close Kodi.

6. Download the file [recovery.conf](https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.conf) from Google, using either the terminal command `wget https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.conf` or a web browser.

7. Navigate to `/home/[your username]/[folder you put recovery.conf in]`, and rename it `widevine_config.json`, using the root Nautilus window that is still open. Copy it to `/root/.kodi/cdm`, `/root/.kodi/userdata/addon_data/script.module.inputstreamhelper/cdm`, and anywhere else under `/root/.kodi/userdata/addon_data/script.module.inputstreamhelper/` where you can find a copy of libwidevine.so.

8. Launch Kodi again as root. You may now get the message "Netflix error" and be unable to open the Netflix app. If this happens, use Amazon VOD, or if you don't subscribe to that service, skip to step 10.

9. In the Amazon VOD app, attempt to play a movie. You will get prompted to update Widevine, but if you decline this prompt the movie will now play, and you shouldn't get asked again. If you ever are, just decline again.

10. If you haven't set up Kodi with Amazon VOD, Netflix, and inputstream.adaptive on your own user account, do so. If you have, skip this step.

11. In a root Nautilus window, copy `libwidevine.so` and `widevine_config.json` to the same folders you put them in during step 7, but under `/home/[your username]/.kodi` instead of `/root/.kodi`.

12. Repeating this step for every folder under `/home/[your username]/.kodi` that contains copies of `libwidevine.so` and  `widevine_config.json`, right-click on the folder and select "Properties." Under the permissions tab, select "Create and delete files" in all 3 dropdown menus. Select "Change permissions for enclosed files..." and do the same to these menus, here also selecting "Read or write" wherever applicable, then click "Change", wait a few seconds. and close both dialog boxes.

13. Open Kodi again, this time doing so under your own account either by simply clicking on "Sound & video > Kodi" in the main application/start menu, or entering the command `kodi` in the terminal. Widevine has been installed and configured, so Amazon VOD and Netflix should now work normally.

**For future reference**

Presumably you will need to actually update libwidevine.so and widevine_config.conf eventually, in which case you can find a more recent ARM 32-bit recovery image, change the HWID in `config.py` again, and repeat these instructions. Recovery images can be found [here](https://cros-updates-serving.appspot.com), or likely in a fresh copy of [recovery.conf](https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.conf)

**Comment by Cyber1000** [comment]
Hi,

I had it much easier with installing today:
- latest Raspbian Stretch Lite
- No Linux-UI, only console
- Kodi 18.0-1
- Raspberry Pi 3B
- SDCard wih 32Gb (and only 2Gb used so far)
- /boot/config.txt tweaked with gpu_mem=256 (for reference, don't think it matters here)

So nearly the same setup, but with Pi 3 instead of 3B+ and no  grafical linux interface like LXDE.

I did:
- aptitude install kodi-inputstream-adaptive libnss3 libnspr4
- installed this "Amazon VOD" plugin
 user under which kodi runs must have some rights to mount, unmount, ... . 
My user is named "kodi" and so /etc/sudoers file must contain this: 
`kodi ALL=NOPASSWD:/bin/mount, /bin/umount, /sbin/losetup, /sbin/modprobe`
- started a film, kodi said, it had to activate and download from chrome OS, I accepted and waited
- works!

My problems where that I had to add the entry in /etc/sudoers and install kodi-inputstream-adaptive, libnss3, libnspr4, I missed some of them out first place, but after that everything worked. I didn't have to copy files manually ...

**Comment by dagwieers** [comment]
The future probably looks more like #72 so we only need the diskspace to store the ZIP file.
But in the meantime we moved to the `SPRING` image. #60

**Comment by dagwieers** [comment]
The latest **inputstreamhelper** selects the Chrome OS image with the latest version and the smallest size dynamically. So this is no longer hard-coded. For instance today it would select:
```
Debug: [script.module.inputstreamhelper]: Find best ARM image to use from recovery.conf
Debug: [script.module.inputstreamhelper]: EXPRESSO (2931324855) is smaller than BOB (3373816646)
Debug: [script.module.inputstreamhelper]: BIG (2139677845) is smaller than EXPRESSO (2931324855)
Debug: [script.module.inputstreamhelper]: JERRY (12239.92.1) is newer than BIG (12239.92.0)
Debug: [script.module.inputstreamhelper]: MICKEY (2871488773) is smaller than JERRY (3359473879)
```
