### ISSUE TITLE
Postpone reasking Widevine update with 24h or 48h

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#451]
Currently ISH will ask the user to update Widevine CDM on every playback request, which is painful if you reject it because the timing is not right or you have other reason for not doing it.

I think we are annoying our users needlessly with this. Therefore I would propose we postpone asking the user again in 24h or 48h if he rejects it.

Obviously #69 would be better, but may not be possible before the next major Kodi release (the next few years).

**Comment by mediaminister** [comment]
The problem is that `last_check` timestamp is only set if the user is on the latest Widevine version. I changed this to set last_check from the moment the version check is done. See https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/450
