### ISSUE TITLE
Apple TV tvOS widevine CDM?

### ISSUE THREAD

**Issue by AntiBigmac** [emilsvennesson/script.module.inputstreamhelper#456]
Is there anyway me to use Netflix addon with Apple TV 4K 2021?

Currently, I have gotten error message that the widevine CDM is not available on this system architecture. 

Any suggetions?

**Comment by matthuisman** [comment]
think you need this PR to be merged in:
https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/429

**Comment by AntiBigmac** [comment]
> think you need this PR to be merged in: https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/429
> 
> 
> 
> In the meantime, you can try installing the "Video Test Streams" add-on from Slyguy repo (https://www.matthuisman.nz/2020/02/slyguy-kodi-repository.html)
> 
> Then try to play the "Inputstream Adaptive - Dash with Widevine"
> 
> Then follow prompts to install Widevine CDM.
> 
> (slyguy CDM installer should already support Darwin ARM64)
> 
> 
> 
> Or, manually download this file:
> 
> https://k.slyguy.xyz/.decryptmodules/widevine/4.10.2198.0-mac-arm64.dylib
> 
> and rename it to **libwidevinecdm.dylib** and put it in a folder called **cdm** in the kodi userdata directory

Thank you for the suggetions. I did try but it says "Darwin AppleTV11,1 Kodi v19 does not yet support Widevine playback"

I may have to wait. Thanks.

**Comment by matthuisman** [comment]
oh strange - seems platform.machine() on that is returning "AppleTV11" instead of something like arm64.

Can you write **exactly** what it says between Darwin and Kodi
Was it actually **AppleTV11,1**  (with the comma and 1?)
then I can hack in the supported platform to be that.

**Comment by AntiBigmac** [comment]
"Darwin AppleTV11,1 Kodi v19 does not yet support Widevine playback"

- This is exactly what says.

**Comment by matthuisman** [comment]
@AntiBigmac 
ok, try install again now :)

**Comment by AntiBigmac** [comment]
> @AntiBigmac 
> 
> ok, try install again now :)
> 
> I made Darwin AppleTV11,1 point to the Darwin arm64 cdm
> 
> 
> 
> https://www.theiphonewiki.com/wiki/J305AP
> 
> `The model identifier is: AppleTV11,1`

Thanks. I am really apppriciated all of your efforts.

But now I have another error message. 

- "One or more items failed to play. Check the log for more information about this message."

**Comment by matthuisman** [comment]
Right. So it probably isn't supported if it's still not playing widevine content. A debug log would help confirm

**Comment by mediaminister** [comment]
We definitely need a full debug log: https://kodi.wiki/view/Log_file/Easy

**Comment by AntiBigmac** [comment]
I am trying to get full log file but Apple TV 4K couldn't use keyboard.

Is there any other way to get log file?

**Comment by AntiBigmac** [comment]
Here is log file. 

[https//paste.kodi.tv/ajubiyahuz]()

**Comment by matthuisman** [comment]
@AntiBigmac 
Do all the other test streams in that addon play?

**Comment by AntiBigmac** [comment]
> @AntiBigmac 
> 
> Do all the other test streams in that addon play?

I did test with "video test stream". I did choose different resolutions. 
The other test beside with widevine, all good.

Also I set debugging for the video components.

**Comment by AntiBigmac** [comment]
Here is log for the all test from Video test addon. 

[https://paste.kodi.tv/akipokoaw]()

**Comment by matthuisman** [comment]
looks like you may not have a decrypter
You should have a "Found decrypter" line after "Searching for decrypters"

eg.
```
Searching for decrypters in: C:\Users\Matt\AppData\Roaming\Kodi\19\portable_data\addons\inputstream.adaptive\
Found decrypter: C:\Users\Matt\AppData\Roaming\Kodi\19\portable_data\addons\inputstream.adaptive\ssd_wv.dll
```

**Comment by AntiBigmac** [comment]
"could you try installing the tvOS deb linked below"

- My son just took my Macbook to his summer school. I will try after he will be home.

Thank you so much all of your hard works to address these issues. 👍👍

**Comment by matthuisman** [comment]
If it works, I'll be quite surprised :)

**Comment by AntiBigmac** [comment]
> If it works, I'll be quite surprised :)

I hope so. Will post result and log file after testing.

**Comment by matthuisman** [comment]
@AntiBigmac 
did you test?

**Comment by AntiBigmac** [comment]
> @AntiBigmac 
> 
> did you test?

My son is still at Summer camp.  Will test after, he will be back home.

**Comment by matthuisman** [comment]
found another user to test, and no good.
The mac ARM64 widevine blob doesn't seem to work on iOS or tvOS
https://forum.kodi.tv/showthread.php?tid=363757&pid=3052325#pid3052325

**Comment by AntiBigmac** [comment]
> found another user to test, and no good.
> 
> The mac ARM64 widevine blob doesn't seem to work on iOS or tvOS
> 
> https://forum.kodi.tv/showthread.php?tid=363757&pid=3052325#pid3052325

Too bad but at least it was worth of the shot. 

Thank you very much for the your efforts. Really appriciate.

**Comment by horstle** [comment]
So I guess this can be closed?
