### ISSUE TITLE
Kodi restarts during downloading Chrome OS 

### ISSUE THREAD

**Issue by ValentijnDemeyer** [emilsvennesson/script.module.inputstreamhelper#460]
Dear,
I'm running Coreelec (19.2-Matrix_rc2) on an Amlogix S905X from an SD card (16gb).

when trying to install Widevine the system always crashes around 2/3 third of the download.
I briefly checked the log, but couldn't find a clear explanation why it crashed (no error message), seems like it just stopped.
log: https://paste.kodi.tv/qanodafeza.kodi 
I pasted the whole log, but the interaction with the addon seems to start as from line 2814. 

Personally I have a dirty workaround by restoring a backup with working widevine from another device (rpi4), but I was interested to know what could explain the behaviour.

Kind regards,
Valentijn

**Comment by horstle** [comment]
Do you have some kind of automatic suspend or maybe screensaver which might become active before the download finishes?
Please try disabling any of that or regularly press a button on your remote/keyboard (but one which doesn't really do anything, like "Ctrl" on a keyboard).

I'm not sure, but I think a progress dialog doesn't keep the system awake? If so, we should find a way to do so @mediaminister @dagwieers.

**Comment by mediaminister** [comment]
If the system crashes maybe there is a problem with writing to the filesystem. Please try using another SD card.

**Comment by ValentijnDemeyer** [comment]
I tried a clean install on a spare SD card I often use to play around and kept the system awake. 
Unfortunately this didn't help.
Also the log of the clean install doesn't add additional info.

@mediaminister, I also would suspect a system type of error given that this happens during the download of the file, which in my opinion is quiet straight forward. 
Therefore I went looking on the Coreelec forum and have found someone with a similar issue (unfortunatley without a solution). But I'll continue looking in that direction: https://discourse.coreelec.org/t/s905x-emmc-bootloader-image-to-try-to-fix-large-file-transfert-crash/14353

In the meantime I was wondering if someone could help me by finetuning my workaround. 
* By either indicating what code to for the addon to identify a manually added widevine backup in the following folder: \\IP\Userdata\addon_data\script.module.inputstreamhelper\backup
* or by indicating how to replace the libwidevinecdm.so file in the .kodi/cdm folder

thanks in advance

**Comment by horstle** [comment]
The easiest way would be to just put the libwidevinecdm.so in the .kodi/cdm directory, then go to the inputstreamhelper settings page and enable the option "Disabled".

**Comment by mediaminister** [comment]
I guess you could try this: https://discourse.coreelec.org/t/le-potato-segmentation-fault-on-large-file-transfer/690/46

**Comment by ValentijnDemeyer** [comment]
Thanks for the advice and support, I'll make it work 😉
