### ISSUE TITLE
Manually start libwidevine update

### ISSUE THREAD

**Issue by joendres** [emilsvennesson/script.module.inputstreamhelper#47]
I'm not sure if this is a support question or an enhancement suggestion: I'd like to start a libwidevine update manually.

What happened:
I got a message box about a libwidevine update and started it. It didn't work because ther was not enough free disk space. I added disk space, but now I don't know how to trigger the update again. Just starting a video (as the first time I got the message) doesn't work.

**Comment by horstle** [comment]
Currently the easiest way to force a reinstall is to remove the directory "userdata/addon_data/script.module.inputstreamhelper". In Libreelec that's found under /storage/.kodi.
I had been working on this a few months ago, I'll work on it a bit further and probably create a pull request in the next few days.

**Comment by emilsvennesson** [comment]
Yeah, this is definitely something that should be made possible.

I have been quite busy the last couple of months and haven't had the time or effort to work or review any pull requests, but I'm going to continue working on this module next month. Sorry for going MIA!

**Comment by AreaScout** [comment]
you can set ``WIDEVINE_UPDATE_INTERVAL_DAYS = 0`` in config.py, then it will check on each movie you play

**Comment by joendres** [comment]
@horstle Thanks for the hint. I was able to force an update by removing the files from that directory.

**Comment by joendres** [comment]
@AreaScout Thanks for the hint. But since fully automatic installation doesn't work for me, it doesn't solve my problem.

**Comment by dagwieers** [comment]
@joendres We are revising how we would like the plugin to behave, and what control we can put in the hands of the users #85, insights from users are very much appreciated.

**Comment by dagwieers** [comment]
Closed by #91
