### ISSUE TITLE
Widevine for 64bit raspberry pi

### ISSUE THREAD

**Issue by mkuthan** [emilsvennesson/script.module.inputstreamhelper#472]
I've got an error that Widevine is not available on 64 bit Raspberry PI but there is available package in the Raspberry Bullseye: libwidevinecdm0:armhf (multiarch), version 4.10.2252.0-1. The library is installed under custom path /opt/WidevineCdm/_platform_specific/linux_arm/libwidevinecdm.so. 

How can I configure inputstream helper plugin to use Widevine shared library installed in the system?

**Comment by horstle** [comment]
You can try to use the libwidevinecdm.so by copying it to ~/.kodi/cdm/ (create the cdm directory if it doesn't exist yet) and disabling inputstreamhelper by opening the settings page and __enabling__ the option "Disable"! Do not disable the addon itself!

But most probably it won't work. As the error message says, the library only works on 32bit userspace.

**Comment by mkuthan** [comment]
I've followed the instruction but got an error. Unfortunatelly without a details about root cause :(

```
ERROR <general>: AddOnLog: inputstream.adaptive: Unable to load widevine shared library (/home/kodi/.kodi/cdm/libwidevinecdm.so)
```

Tested with two library versions available in the repository https://archive.raspberrypi.org/debian/pool/main/w/widevine/:
* 4.10.2252.0
* 4.10.1679.0

Thanks anyway for you help :)
