### ISSUE TITLE
Missing settings

### ISSUE THREAD

**Issue by adrianmihalko** [emilsvennesson/script.module.inputstreamhelper#473]
I am trying to use one addon which needs Widevine support, but I get error that DRM playback has failed.

I installed latest InputStrem Helper 0.5.8, but it is still not working.

Based on [this guide](https://github.com/emilsvennesson/script.module.inputstreamhelper/wiki/Troubleshooting) I am trying to reinstall Widevine, but I have no options like reinstall/remove:

![IMG_1292](https://user-images.githubusercontent.com/733361/141687915-011e59c8-b146-4d31-80a2-c0d23727db54.JPG)

My device is Xiaomi Mi TV Stick.

**Comment by horstle** [comment]
> My device is Xiaomi Mi TV Stick.

Most of inputstreamhelper is disabled on Android, since Android should have Widevine built in. Your issue is not related to this addon. You should probably ask in the Kodi forum and post a debug log.
