### ISSUE TITLE
Problem installing widevime cdm

### ISSUE THREAD

**Issue by lstauber** [emilsvennesson/script.module.inputstreamhelper#480]
raspberry pi 4, libreelec.
Install widevime cdm ends with "successfully", but then helper information shows "widevine cdm is at version 4.10.2391.0 and was installed on Never".
DRM playback does not work (ivysilani.cz).
Any logs needed, any thoughts?
Thanks...

**Comment by mediaminister** [comment]
Please reboot your Raspberry Pi after installing Widevine CDM.
Yes, to investigate this problem I need a log file: https://kodi.wiki/view/Log_file/Easy

**Comment by mediaminister** [comment]
> Install widevime cdm ends with "successfully", but then helper information shows "widevine cdm is at version 4.10.2391.0 and was installed on Never".

You need to close the InputStream Helper add-on and open the InputStream Helper information pane again to see the updated information.

I guess it just works after a reboot.

**Comment by lstauber** [comment]
Hi, reboot did not help. I'll try the log file things asap. Perhaps it is only the other addon broken...

**Comment by MuhChy** [comment]
Me and my friend are also unable to install Widevine. Also tried netflix which also don't work anymore because of the Input helper module

**Comment by horstle** [comment]
@MuhChy Try these test builds: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/497#issuecomment-1068239609

**Comment by MuhChy** [comment]
Ok let me check
