### ISSUE TITLE
Kodi 18 - Error when installing widevine on Raspbian (RPi 3b+)

### ISSUE THREAD

**Issue by NickkoG** [emilsvennesson/script.module.inputstreamhelper#49]
I use the lastest Kodi 18 build available on Raspbian repository.
All Kodi extentions are up to date.
I use a Raspberry 3B+ and Raspbian

I use Amazon VOD, when I try to play a movie, I get a dialog to ask me if I want to install widevine, I accept and follow instruction. Each time it fail.

I get this error in the log: 

`DEBUG: [script.module.inputstreamhelper-0.3.3]: ['sudo', 'losetup', '/dev/loop0', '/home/pi/.kodi/userdata/addon_data/script.modu     le.inputstreamhelper/tmp/chromeos_11316.165.0_daisy-skate_recovery_stable-channel_skate-mp-v2.bin', '-o', '1278464'] cmd executed successfully.

DEBUG: [script.module.inputstreamhelper-0.3.3]: ['sudo', 'mount', '-t', 'ext2', '/dev/loop0', '-o', 'ro', '/home/pi/.kodi/userdat     a/addon_data/script.module.inputstreamhelper/tmp/mnt'] cmd failed.

DEBUG: [script.module.inputstreamhelper-0.3.3]: ['sudo', 'mount', '-t', 'ext2', '/dev/loop0', '-o', 'ro', '/home/pi/.kodi/userdat     a/addon_data/script.module.inputstreamhelper/tmp/mnt'] cmd output:
                                             mount: wrong fs type, bad option, bad superblock on /dev/loop0,
                                                    missing codepage or helper program, or other error

                                                    In some cases useful info is found in syslog - try
                                                    dmesg | tail or so.

DEBUG: [script.module.inputstreamhelper-0.3.3]: ['sudo', 'losetup', '-d', '/dev/loop0'] cmd executed successfully.

DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions

DEBUG: CAddonSettings[inputstream.adaptive]: loading setting values

DEBUG: [script.module.inputstreamhelper-0.3.3]: Widevine is not installed.`

Someone have an idee to resolve thie problem please?
Thanks in advance.

**Comment by NickkoG** [comment]
Nobody have an idea, an advise?

**Comment by dagwieers** [comment]
I would check if */home/pi/.kodi/userdata/addon_data/script.modu le.inputstreamhelper/tmp/chromeos_11316.165.0_daisy-skate_recovery_stable-channel_skate-mp-v2.bin* is not corrupt, maybe the file system was full, maybe the download halted or got interrupted?

You need at least 2GB of free space IIRC.

**Comment by dagwieers** [comment]
Mine apparently is downloading a different file more recently:
```
kodi03:~ # ls -lha .kodi/userdata/addon_data/script.module.inputstreamhelper/tmp/
total 2067032
drwxr-xr-x    3 root     root        4.0K Mar 23 02:55 .
drwxr-xr-x    4 root     root        4.0K Mar 23 02:25 ..
-rw-r--r--    1 root     root        1.4G Mar 23 02:55 chromeos_11316.165.0_daisy-spring_recovery_stable-channel_spring-mp-v3.bin
-rw-r--r--    1 root     root      562.5M Mar 23 02:53 chromeos_11316.165.0_daisy-spring_recovery_stable-channel_spring-mp-v3.bin.zip
drwxr-xr-x    2 root     root        4.0K Mar 23 02:30 mnt
```
Maybe try it once again ?

**Comment by kaminsky9444** [comment]
https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/57

**Comment by dagwieers** [comment]
I am going to close this, if you still have an issue, feel free to reopen or report back.
Thanks!
