### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)

### ISSUE THREAD

**Issue by DanielGabris** [emilsvennesson/script.module.inputstreamhelper#495]
Hello, 

since today I get following error when trying to start any movie on netflix addon. 
"InputStream Helper has geberated an internal error:: 'asci' codec cat't decode byte 0xe2 in position 58437: ordinal not in range (128)
KODI version 18.7 runninig on Linux arm (raspberry 3)
InputStream Helpre is at version 0.5.8

also get error when tried to reinstall widevine CDM.
 Worked well until today, nothing was updated lately. 

error from log:
2022-03-11 17:57:46.346 T:1354748096   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/script.module.inputstreamhelper/default.py", line 8, in <module>
                                                run(sys.argv)
                                              File "/home/pi/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 14, in run
                                                widevine_install()
                                              File "/home/pi/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 42, in widevine_install
                                                Helper('mpd', drm='widevine').install_widevine()
                                              File "/home/pi/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 34, in clean_before_after
                                                result = func(self, *args, **kwargs)
                                              File "/home/pi/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 221, in install_widevine
                                                result = install_widevine_arm(backup_path())
                                              File "/home/pi/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 69, in install_widevine_arm
                                                devices = chromeos_config()
                                              File "/home/pi/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
                                                return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                              File "/home/pi/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 73, in http_get
                                                return content.decode()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
                                            -->End of Python script error report<--
2022-03-11 17:57:46.347 T:1354748096   DEBUG: onExecutionDone(14, /home/pi/.kodi/addons/script.module.inputstreamhelper/default.py)

Thanks for help.

Daniel

**Comment by Daniel80P** [comment]
Hi,

I get the exact same error running the same version of kodi and input stream helper on a RPi 3B+....
Help would be greatly appreciated.

Best regards
Daniel

**Comment by ShaveenR** [comment]
Hi,

I have the same issue, will appreciate a fix. For now I will try to downgrade the version and see if it works.

Regards,
S

**Comment by DokuroKM** [comment]
Changing line 73 in lib/inputstreamhelpers/util.py to the following seems to work for me:
`    return content.decode("utf-8")`

Seems that the file used to get the current version of Widevine has been changed on googles side...

**Comment by Daniel80P** [comment]
> Changing line 73 in lib/inputstreamhelpers/util.py to the following seems to work for me: ` return content.decode("utf-8")`
> 
> Seems that the file used to get the current version of Widevine has been changed on googles side...

Works for me too...
Thanks a lot...

Regards Daniel

**Comment by ShaveenR** [comment]
> Changing line 73 in lib/inputstreamhelpers/util.py to the following seems to work for me: ` return content.decode("utf-8")`
> 
> Seems that the file used to get the current version of Widevine has been changed on googles side...

Thanks!!! This works

**Comment by calvin4242** [comment]
Thank you very much it worrks!

**Comment by mDfRg** [comment]
> Changing line 73 in lib/inputstreamhelpers/util.py to the following seems to work for me: ` return content.decode("utf-8")`
> 
> Seems that the file used to get the current version of Widevine has been changed on googles side...

For anyone in doubt: the correct file name is util**s**.py. In case someone like me uses LibreElec (Kodi appliance type OS) the full path to the file in question is /storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py
so one can login via ssh to your kodi box and edit it with 

```
nano /storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py
```

@DokuroKM: Thanks for the solution!

**Comment by yenicem** [comment]
> > Changing line 73 in lib/inputstreamhelpers/util.py to the following seems to work for me: ` return content.decode("utf-8")`
> > Seems that the file used to get the current version of Widevine has been changed on googles side...
> 
> For anyone in doubt: the correct file name is util**s**.py (notice the s). In case someone like me uses LibreElec (Kodi appliance type OS) the full path to the file in question is **/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py** so one can login via ssh to their kodi box and edit it with
> 
> ```
> nano /storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py
> ```
> 
> @DokuroKM: Thanks for the solution!

I get:

return content.decode("UTF-8")
                                                 ^
SyntaxError: 'return' outside function

**Comment by nxdefiant** [comment]
Do not add or remove spaces when modifying the line. The spaces are required for proper function. There should be exactly 4 spaces, the line that starts with return must align with the previous line.

**Comment by yenicem** [comment]
@nxdefiant 
Thank you for your Syntax correction. It was very fast :-)

@ mDfRg
Thank you for the solution

Netflix runs without problems on my system now.

**Comment by Daikath** [comment]
I am running into this problem, running kodi leia, on libreelec 9, using a raspberry pi 3,, I have no idea how to change that line of code,,, where would I find and edit it. So netflix works again on my device? The devices to log on remotely to edit seem to be android based..

Any help would be greatly appreciated.

**Comment by tokr94** [comment]
SSH to your raspberry pi e. g. using Putty: ``ssh root@libreelec`` with password libreelec unless you changed the default password. Then call ``nano /storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py`` as mentioned above and navigate to line 73. Change the line, press ctrl + o and ctrl+ x so save and exit the file and restart you pi.

**Comment by splashcrum** [comment]
> Changing line 73 in lib/inputstreamhelpers/util.py to the following seems to work for me: ` return content.decode("utf-8")`
> 
> Seems that the file used to get the current version of Widevine has been changed on googles side...
@DokuroKM thanks a lot, it's working for me

**Comment by Daikath** [comment]
> SSH to your raspberry pi e. g. using Putty: `ssh root@libreelec` with password libreelec unless you changed the default password. Then call `nano /storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py` as mentioned above and navigate to line 73. Change the line, press ctrl + o and ctrl+ x so save and exit the file and restart you pi.

Thanks man! I tried googling around for a solution before, but this post had all the right buzzwords and info for me to figure it out. It's downloading the widevine right now!

**Comment by tarifari** [comment]
Nice, i hope this will fix my netflix error. Widevine is downloading again

**Comment by horstle** [comment]
Closing, since #496 should fix this. It would be great if some users could test the builds [here](https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/497#issuecomment-1068239609) and report if it works, so I can do a release, soon.

**Comment by movikbence** [comment]
It works for me with the given fix, thank you so much
