### ISSUE TITLE
Disable update check when using `Play from here`

### ISSUE THREAD

**Issue by Sopor** [emilsvennesson/script.module.inputstreamhelper#498]
The addon will check for a new Widevine every month and it happens right before the video is about to start. That is no big deal, but when using `Play from here` it is quite annoying when that update dialog popups :(

I couldn't find any settings to disable the update check more than increasing it to 90 days.

Would it be possible to at least disable the update check between the videos when using `Play from here`?

**Comment by horstle** [comment]
I don't think that will be possible on our side. Maybe the Netflix/Amazon/... addon, that is using inputstreamhelper could avoid calling inputstreamhelper in such a situation.
