### ISSUE TITLE
[Windows 64bit] - Wrong widevine lib (for 32bit systems) will be fetched

### ISSUE THREAD

**Issue by asciidisco** [emilsvennesson/script.module.inputstreamhelper#5]
Using `arch = platform.machine()` to determine the Windows system type doesn't seem to be sufficient for 64bit systems, as the return value is `AMD64` regardless of the architecture.

This can be solved by utilizing `platform.architecture()` to fetch the system architecture (and it wouldn't do any harm if done so).

**Comment by gismo112** [comment]
@emilsvennesson 
I send you PR #6 to fix this Problem.
Thanks for your nice Addon.

Greets Gismo
