### ISSUE TITLE
[Enhancement] Add proxy support

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#50]
While testing our own addon's proxy support I discovered that **inputstreamhelper** does not adhere to Kodi's proxy configuration, which breaks playing DRM streams.

It is not that hard to make addon's using Requests to use Kodi's proxy settings. You can find our implementation at: https://github.com/pietje666/plugin.video.vrt.nu/pull/87

The testing methodology I used was to disable the default gateway (or in LibreELEC, configure a non-existing gateway) and then test your local proxy and see if everything works as expected.

**Comment by emilsvennesson** [comment]
Hi!

Is there any actual explanation why this is needed to be done by the add-on? You would assume that Kodi would use its proxy settings system wide, because I can imagine that there's a lot of add-on that won't handle this proxy stuff themselves.

**Comment by dagwieers** [comment]
Well, everything that uses internal functionality (like ListItem) does use global Kodi settings, but you are using the python Requests library independently, and it doesn't know about Kodi's proxy settings.

This patch gets Kodi's proxy settings and applies them to your requests-invocation.

And indeed, there are quite some addon's that do not have (full) proxy support (netflix, youtube, etc), or have their own proxy support (retrospect). Or our own vrt.nu addon which did use Kodi's proxy for everything that was handled by Kodi, but not for the stuff that used the requests library.

**Comment by dagwieers** [comment]
BTW Feel free to configure a proxy in Kodi and test it yourself, your addon will not be using the Kodi proxy. So DRM playback will simply fail in environments that require a proxy to be used.
