### ISSUE TITLE
Widevine CDM extraction error

### ISSUE THREAD

**Issue by fumo88** [emilsvennesson/script.module.inputstreamhelper#511]
Hi, 

first of all thanks for the project and great work.

I am experiencing an issue with LibreELEC Kodi 19 freshly installed on both RPi 4 2GB and older RPi 3B+ when trying to download widevine library.
I tried with the same 32GB SD card on both platforms and I am having the same issue.

List of steps to replicate the issue: 
- Download LibreELEC USB-SD creator 1.4 for windows
- Write latest LibreELEC image for RPi on SD card
- Insert SD card in RPi and power on, complete first run configuration, reboot
- At reboot, go to add-on list and install from repository LA7-LA7d Kodi plugin ([link](https://github.com/luivit/plugin.video.rivedila7))
- Open plugin and start any stream (e.g. Diretta LA7)
- Start the Widevine installation

The installation properly starts, but then it stops at the end of the "Scanning the filesystem for the Widevine CDM..." task.
I attach the whole log, at the end I also activated debug mode and repeated the widevine installation steps: [kodi.log](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/8457392/kodi.log)

The errors are:
- File libwidevinecdm.so not found in the ChromeOS image
- Extracting widevine from the zip failed!

Anyone else with the same problem?
Could you please support?

Thanks in advance!
fumo88

**Comment by fumo88** [comment]
**Update:** I also tried to locally download the ChromeOS image to extract the library via the wv_cros.py script by horstle (attached for your convenience), but I am facing the same issue.
The script terminates with the following error: "4 File libwidevinecdm.so not found in the ChromeOS image"

**Comment by horstle** [comment]
Ok, so I know where the issue is, but I don't understand why it happens. The check `dir_dict['name_len'] == len(filename)` in line 96 of arm_chromeos.py fails, because the length of the filename is reported as 21, not 17, as it should be for "libwidevinecdm.so".

A quick and dirty solution would probably be to remove "BOB" from line 87 in config.py (in ~/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/).

I'll look further into this tomorrow.

**Comment by zud222** [comment]
The only working quick and dirty solution I found was removing the file length check from line 96 (`dir_dict['name_len'] == len(filename)`).

Looking into the current ChromeOS Images with TestDisk I found that they for some reason contain a deleted file "libwidevinecdm.so#new" (filename with 21 chars, not 17) which appears to be identical to "libwidevinecdm.so" in the same folder and somehow breaks the search logic.

As said above, I worked around this by simply commenting out the second half of the if-check on line 96. `if dir_dict['inode'] < self.sb_dict['s_inodes_count']: ###quick & dirty### and dir_dict['name_len'] == len(filename):`.

**Comment by horstle** [comment]
OK, I had hoped it was only an issue with that specific image, but I guess I'll have to properly implement searching through the filesystem, instead of the rather naive approach used so far.

**Comment by RomanB67** [comment]
Hello,
i had für und problem.
Fresh install libreelec 10.0.2. in Raspberry Pi 4
Install Netflix
Start Widevine Installation with the same errors

Greetings ans thanks for helping

**Comment by RoSoFo11** [comment]
Hello,

Many many thanks to zud222 for this quick & dirty solution. With this I got the widevine cdm installed on my Raspberry Pi 3 B+ with libreelec 9.2.8 and Kodi 18.9.

For someone else who wants to use the q & d solution, here is the path of the arm_chromeos.py file on libreelec 9.2.8: ~/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine

**Comment by RomanB67** [comment]
Hello,
 
also thanks for the quick & dirty solution. Also works on Raspberry Pi 4 with libreelec 10.0.2

**Comment by horstle** [comment]
Testbuilds with a fix can be found here: https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/512#issuecomment-1094379719

**Comment by thelacesz** [comment]
I have the same problem. :(

**Comment by horstle** [comment]
You could try installing a testbuild from here: https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/512#issuecomment-1098497007

**Comment by thelacesz** [comment]
Thank you very much!
