### ISSUE TITLE
Playback fails with latest Widewine Release 14588.98.0 on RPI4 (Libreelec)

### ISSUE THREAD

**Issue by sb9x** [emilsvennesson/script.module.inputstreamhelper#518]
In Kodi .log appears
2022-05-20 23:05:00.154 T:937     ERROR <general>: AddOnLog: inputstream.adaptive: Decrypt Sample returns failure!

LibreELEC:/.kodi/cdm # ls -l libwidevinecdm.so
-rwxr--r--    2 root     root       7607224 May 20 23:02 libwidevinecdm.so
LibreELEC: /.kodi/cdm # ldd libwidevinecdm.so
        /usr/lib/libarmmem-v7l.so (0xf6a04000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0xf69f2000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0xf69e0000)
        librt.so.1 => /usr/lib/librt.so.1 (0xf69ce000)
        libm.so.6 => /usr/lib/libm.so.6 (0xf697c000)
        libc.so.6 => /usr/lib/libc.so.6 (0xf6820000)
        /usr/lib/ld-linux-armhf.so.3 (0xf7b0f000)
LibreELEC:~/.kodi/cdm # sha1sum libwidevinecdm.so
cd3b716627828ba9499d4309028d5010ceafb125  libwidevinecdm.so

the restore to an earlier version of widewine doesnt solve the problem!

**Comment by horstle** [comment]
After restoring, you need to reboot.

**Comment by sb9x** [comment]
I had already the pi restarted. It doesn't solve the problem. The problem exists since the update procedure has found the libwidevine update.

**Comment by sb9x** [comment]
I had restarted the, but It doesn't solve my problem.

**Comment by horstle** [comment]
Please provide a full debug log.

**Comment by sb9x** [comment]
Here is the debug log: 
[http://ix.io/3Ywp](http://ix.io/3Ywp)

there are a lots a of Decrypt Sample returns failure errors. 
the problem was introduced since the last widewine update. the restore to an earlier version (with reboot) doesnt solve it.

**Comment by sb9x** [comment]
My problem is solved
Since the update input stream adaptive 20.2.2.1
