### ISSUE TITLE
Stuck on "Extracting Widevine CDM from image..."

### ISSUE THREAD

**Issue by morrogenduath** [emilsvennesson/script.module.inputstreamhelper#519]
I have a fresh install of LibreElec 10.0.2 on RPI 3B+, on a 32GB microSD card.

I try to use three plugins that use Widevine CDM (specifially Amazon VOD, VRT Nu and VTM Go).

Inputstream Helper is at version 0.5.10+matrix.

Widevine is not yet installed so it starts the extraction process.
At some point it reaches around 90%, then it jumps back to around 30% and then it's stuck on "Extracting Widevine CDM from image..."

I can cancel, but then it just gets stuck on 'Cancelling'. The only thing I can do next is ssh in and reboot.

The kodi.log doesn't seem to show a lot.
If there's any other log I should produce or any other info I should give, let me know.

Thanks in advance for the help!
[kodi.log](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/8935618/kodi.log)

**Comment by horstle** [comment]
I heard of this before, but didn't find the time to fix it yet. It's actually a combination of 2 issues:

1. The progress dialog is somewhat broken. Just ignore the percentage.
2. Sometimes the extraction takes very long, I have to look in to why that is (possibly the path changed).

But the good news is, it should actually still work. You just have to be very patient.
The earliest I can look into this will probably be in two weeks.

**Comment by morrogenduath** [comment]
Thanks for the reply. It did indeed work after 30 minutes or so.

**Comment by raj11000** [comment]
> I heard of this before, but didn't find the time to fix it yet. It's actually a combination of 2 issues:
> 
> 1. The progress dialog is somewhat broken. Just ignore the percentage.
> 2. Sometimes the extraction takes very long, I have to look in to why that is (possibly the path changed).
> 
> But the good news is, it should actually still work. You just have to be very patient. The earliest I can look into this will probably be in two weeks.

Nothing change  jio tv not working now .it gives error winevine window version not supported.
I tried to install inputstream helpline link but it got stuck after waiting 1.30 hrs . I forcely closed . Jio is now working on Android devices .
It has been stopped.No live tv working on kodi now days  due to WIDEVINE DRM ISSUE.

**Comment by raj11000** [comment]
Please sort out issue widevine cdm issue immediately
