### ISSUE TITLE
Widevine decompression issue

### ISSUE THREAD

**Issue by pblacq** [emilsvennesson/script.module.inputstreamhelper#526]
Attempting to install Widevinecdm using 0.5.10+matrix.

The Chromium image appears to be corrupted (attempted several times).

Downloads ok, but after a while fails with a zlib error:
zlib.error: Error -3 while decompressing data: invalid literal/length code

attempting to manually unzip the archive:
~/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/chromeos_15117.112.0_bob_recovery_stable-channel_mp.bin.zip
results in a similar error: error:  invalid compressed data to inflate.

Is there a work around to change the source of chromeOS image?

**Comment by horstle** [comment]
In the inputstreamhelper settings there is the "Install from" option. You can either specify a URL in the setting below before clicking on "install from" or specify a local file during the dialog.

**Comment by tenans** [comment]
I've got the same issue, but I've solved downloaded the zip from my pc and load onto rpi4 via smb.

**Comment by horstle** [comment]
Is this still happening?

**Comment by g-t3n** [comment]
Hi I’ve tried the past week and seems to work fineIl giorno 10 apr 2023, alle ore 15:04, horstle ***@***.***> ha scritto:﻿
Is this still happening?

**Comment by horstle** [comment]
Thanks for the info, then I'll close the issue.

**Comment by g-t3n** [comment]
Thank you!
