### ISSUE TITLE
Widevine CDM failing to extract from image

### ISSUE THREAD

**Issue by bzoit** [emilsvennesson/script.module.inputstreamhelper#527]
Hello! I have Kodi 19 on my Pi 3B+ running the latest version of Raspbian. I tried installing CastagnaIT's Netflix add-on for Kodi, but it requires Widevine CDM library. When I try to install it through Kodi, the EULA appears, and the Chrome OS stage finishes correctly, but then it gets to the "extracting Widevine from image" stage and it gets stuck at about 30%. I've tried multiple times to install it, but the issue keeps repeating. I've looked into many GitHub issues and other forum posts, but I can't find any solution that works. There's nothing unusual in my kodi.log file. If anyone could help, it'd be greatly appreciated!

**Comment by horstle** [comment]
I guess this is probably the same as #519 . With some ChromeOS images you have to wait extremely long. I'm not sure when I'll be able to fix/improve that.

**Comment by bzoit** [comment]
Thank you for the solution! I let it run for about an hour and it completed.
