### ISSUE TITLE
How to use inputstreamhelper from PVR Addon

### ISSUE THREAD

**Issue by flubshi** [emilsvennesson/script.module.inputstreamhelper#54]
I have already included inputstreamhelper in a python video addon. This works pretty good. Especially the widevine download improves the user experience a lot.

I am also working on a PVR plugin. This needs widevine as well and it would be great to use inputstreamhelper for the setup. As the PVR plugins are written in C++, I am a bit helpless how to call check_inputstream() or how to use a python library from there...

My current idea is to extend PR #52 created by @horstle such that a PVR plugin could execute this, e.g. by RunScript or the JSON API.

Or is there already a solution to use inputstreamhelper from C++/PVR Plugins?

**Comment by flubshi** [comment]
A short update to explain my current workaround: I added the inputstreamhelper as dependency. 
A small python script is shipped with the c++ pvr addon. The python script calls check_inputstream(). The python helper script is linked to plugin preferences. A big disadvantage is, that a user has to run the script manually...
I would prefer to implement a cleaner solution.

**Comment by dagwieers** [comment]
I would like to add RunPlugin API calls for common needs by other add-ons.
https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/59#issuecomment-521318459

**Comment by dagwieers** [comment]
We still need to add check_inputstream() support to the API.

**Comment by dagwieers** [comment]
Now #98 implements this.
