### ISSUE TITLE
Python version 3.0

### ISSUE THREAD

**Issue by ajbathe** [emilsvennesson/script.module.inputstreamhelper#540]
I tested the version from today under LibreELEC nightly-20230417-83ec8ac (aarch64) with an RPi4 and had to change
```
<     <import addon="xbmc.python" version="2.25.0"/>
---
>     <import addon="xbmc.python" version="3.0.0"/>
```
to get the Widevince CDM 4.10.2557.0 under arm64. Runs well here. Could you please release the next version 0.5.11 ?

I see only a very tiny problem in the log with ldd:

```
2023-04-27 12:19:36.119 T:1231  critical <general>: [script.module.inputstreamhelper] ['ldd', '/storage/.kodi/cdm/libwidevinecdm.so'] cmd failed.
2023-04-27 12:19:36.119 T:1231  critical <general>: [script.module.inputstreamhelper] Failed to check for missing Widevine libraries.
```
ldd libwidevinecdm.so gives
`./libwidevinecdm.so: error while loading shared libraries: ./libwidevinecdm.so: DT_RELR without GLIBC_ABI_DT_RELR dependency`
I guess you'll already know this cosmetic error message.

**Comment by horstle** [comment]
I would like to merge #538 first, but didn't get any answer from @CastagnaIT yet. I'll probably merge it and do a release some time this weekend.

**Comment by CastagnaIT** [comment]
I haven't had time these days, perhaps later today or tomorrow

**Comment by ajbathe** [comment]
Is there a chance to see the DT_RELR without GLIBC_ABI_DT_RELR issue disappearing? I think it is not a critical error but an information. libwidevinecdm.so with md5sum 9b68488364ac2a7d4e7e15cb36ebb489 is working well, it is version 4.10.2557.0 on arm64:
`libwidevinecdm.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=b71fd3342a03fdb140e1f7a757960df219d63625, stripped`
