### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by npmstart-pray** [emilsvennesson/script.module.inputstreamhelper#543]
I've ISH installed somehow on my kodi machine (raspi4/xbian) but it says I've never installed/updated the WideVine cdm. 
Should I?

**Comment by horstle** [comment]
It was probably installed as dependency of another addon. If that addon needs the Widevine library, it will call ISH to install it. If you can play every video you want to, there is no need for it.

**Comment by npmstart-pray** [comment]
I’m having issues with my main addon since installing WideVine. Away it goes. Thank you. Sent from nowhere near my ready room with my new tricorderOn May 7, 2023, at 18:18, horstle ***@***.***> wrote:﻿
It was probably installed as dependency of another addon. If that addon needs the Widevine library, it will call ISH to install it. If you can play every video you want to, there is no need for it.
