### ISSUE TITLE
Repeated Episodes!

### ISSUE THREAD

**Issue by TiiigBitties** [emilsvennesson/script.module.inputstreamhelper#548]
I’m currently on Kodi matrix 19.4 with InputStream Helper 0.6.0+matrix.1 and as far as I can tell this is the current one, but for about a month now all new episodes play the same episode. Ted Lasso has been playing S3E3 on every newly uploaded episode for a while now. Is this on anyone else’s end or is this my end?

**Comment by TiiigBitties** [comment]
P.S. using The Crew for streaming, forgot to mention that bit

**Comment by horstle** [comment]
This has absolutely nothing to do with inputstreamhelper and The Crew is on the Banned Addon list: https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons
