### ISSUE TITLE
Cannot install widevine on Kodi 18.1 libreElec 9.0.1 LePotato

### ISSUE THREAD

**Issue by Acromion1754** [emilsvennesson/script.module.inputstreamhelper#55]
Hi, 
I'm trying to install widevine on a Kodi powered AML-S905X-CC (Le Potato).
It freezed for 4 times in the "10 minutes of unzip&mount", and now is running (launched 3 hours ago) but without success.
Here's the log:
https://pastebin.com/AYp11Qyv
is there any method to install it manually? 
Thanks in advance

Danilo

**Comment by dagwieers** [comment]
The manual instructions are not as straightforward, but you can find them in the source-code.

We do want to improve the feedback to the user, so expect this to be better in a future version.
Be sure you have sufficient disk space available.

**Comment by dagwieers** [comment]
@Acromion1754 We would need to have a Kodi log with debugging enabled (**Kodi Settings** » **System** » **Logging** » **Enable debug logging**) otherwise we have nothing to go by.

If you can no longer reproduce this, or if you are no longer interested in a fix for this, let us know so we can close this issue. Thanks!

**Comment by dagwieers** [comment]
You may want to try our master branch version which will show you the progress it is making on screen. Can you try the below ZIP file?
https://github.com/emilsvennesson/script.module.inputstreamhelper/archive/master.zip

Let me know of this works out. I am going to close this issue as I have provided you with manual installation instructions, a way to get debugging information and a new build.

Feel free to reopen or report back here.
