### ISSUE TITLE
Inputstream.adaptive is missing?

### ISSUE THREAD

**Issue by Taxicletter** [emilsvennesson/script.module.inputstreamhelper#552]
I updated Libreelec to 11.O.1 (Kodi 20.1 Nexus) on a Raspberry Pi 4.

If I try to watch something with an add-on that used to work (VRT of NetFlix), I get that Inputstream.adaptive is misisng. I deleted it, because it wasn't working and it tried unsuccessfully to re-install Widevine.
But now I cannot find the inputstream anymore in the addons and inputstreamhelper doesn't work anymore.
I checked and I have the latest version of those addons.

Apparently I'm the only one, because I'm searching the web for answers, but I can't find anything.

**Comment by ltguillaume** [comment]
https://dl.google.com/widevine-cdm/versions.txt is gone (404)

Probably has to do with the fact that Google is deprecating Widevine Content Decryption Module?

**Comment by Taxicletter** [comment]
Some dependencies are missing in the Nexus repository. When trying to install the Internet Archive Game Launcher
I see "vds.rar" and "script.module.infotagger" and "vfs.libarchive" are missing. I found that is indeed the case. So maybe the inputstream/widevine need one of these as well, or maybe other parts are missing as well?

**Comment by ltguillaume** [comment]
That seems unrelated to me.

**Comment by Taxicletter** [comment]
OK. So now I have two problems in stead of one :-)

**Comment by Taxicletter** [comment]
I did a fresh install of LibreELEC and Kodi, now there was no problem with inputstream or WideVine.
I think _maybe_ my SD-card was to full and that caused installation troubles.

**Comment by horstle** [comment]
> I get that Inputstream.adaptive is misisng. I deleted it, because it wasn't working

So you delete inputstream.adaptive and then you wonder why addons relying on it don't work anymore?

> I checked and I have the latest version of those addons.

You obviously don't, since you uninstalled one of them...



> https://dl.google.com/widevine-cdm/versions.txt is gone (404)

It's not. I don't know, why you can't accesss it, but it is still available.


> Probably has to do with the fact that Google is deprecating Widevine Content Decryption Module?

No, they don't. Google only deprecated older versions of the CDM a few months ago when they released a new version.

I'm closing this because of too much nonsense. I have no idea what you guys are doing to your systems, but it has nothing to do with inputstreamhelper.

**Comment by Taxicletter** [comment]
Hey Horstle,
You're right, it was incomplete and incorrect information. But the inputstream.adaptive already didn't work, deleting it was to install it again, but that didn't work, I couldn't find it anymore.
It was some very idiosyncratic problem, probably because of changing settings, adding and deleting addons, ... . Because on a fresh install, everything worked.
