### ISSUE TITLE
LibreElec 12 nigtly Kodi 21.4.1-Omega

### ISSUE THREAD

**Issue by mariofenech** [emilsvennesson/script.module.inputstreamhelper#553]
Just testing LE12 Kodi 21 and having some errors and streams catchup not working...
Working fine with LE 11 kodi 20
testing with ViwX addon

kodi log
https://pastebin.com/p6j9DaZP

**Comment by horstle** [comment]
Thats not an issue of inputstreamhelper. If it still exists, report to inputstream.adaptive
