### ISSUE TITLE
Streaming Widevine CDM content with Kodi on Fire TV Stick is no longer working

### ISSUE THREAD

**Issue by AntonelloA** [emilsvennesson/script.module.inputstreamhelper#557]
Lately I'm having troubles in streaming free content (specifically italian channels La7) with Kodi installed on a Fire TV Stick.
Content is garbled, and after few seconds even other channels on Kodi stop working, and I need to restart the OS to be able to watch them again. Until a few days ago everything was working fine. 
Is there anything I can try to fix this problem?
Thanks
![2024-02-09-17-40-48-698](https://github.com/emilsvennesson/script.module.inputstreamhelper/assets/20526070/594e2ac9-9af0-46e3-addb-9521bb8abf87)

**Comment by horstle** [comment]
That's not an issue of inputstream helper. i guess it might be related to inputstream.adaptive, so please ask on their github page or in the kodi forum.
