### ISSUE TITLE
widevine extraction: wrong elf class (on x64)

### ISSUE THREAD

**Issue by slynobody** [emilsvennesson/script.module.inputstreamhelper#559]
widevine extraction from an chromeos-image through this helper seems to *deliver the wrong elf class* (on x64 linux) of the widevine-library lately – according to kodi error log.  manually extracting from something like https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_15633.72.0_rammus_recovery_stable-channel_mp-v3.bin.zip resulted in the same error. (tried with chrome-os-user-agents also)

worked around it by installing the usual lib from somewhere else. but i doubt this one will support 1080p which seemed to be why this whole procedure was introduced in the first place?

(debian trixie)

**Comment by horstle** [comment]
On x86 the addon doesn't extract the library from the chrome os image. That is only done on ARM, since that version of the library is not directly available for download.

Please provide a debug log of an installation e.g. started by "reinstall widevine cdm" in the addon settings.

**Comment by slynobody** [comment]
ah, ok. my first impression was it has something to do with x86 vs x64 elf. 

so i did not understood it right, this is *only for arm*. 
my first impression was the widevine does not get shipped and / or signed here and you could get the latest through the chromeos-installer regardless of the system. 

and then something like https://github.com/truedread/netflix-1080p would be done in a more generic way. but this seems to be included, if at all, only in solutions like this: https://github.com/CastagnaIT/plugin.video.netflix

i tried the latest chromeOS from https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_15633.72.0_rammus_recovery_stable-channel_mp-v3.bin.zip – *what should  also be a x64 library?!* (with non-free linux-flavor chromeOS typical capabilities to widevine L3 / 1080p+) – but it also gave me the 'wrong elf' error (maybe one needs to use the correct chromeOS useragent of exactly this build?). maybe the logic behind an approach like this also on x64 lacks something?

**Comment by horstle** [comment]
For x86/x86_64 the addon downloads a small zip archive, which only contains the widevine library. To my knowledge there is no difference between that library and the one which could be extracted from a Chrome OS image of a x86/x86_64 device.

Inputstream Helper automatically installs the Widevine library required on your system. Just run it by using the "Reinstall Widevine CDM" option in the Inputstream Helper settings. If the problem persists, provide a debug log.

**Comment by horstle** [comment]
I guess the issue was resolved...
