### ISSUE TITLE
Content does not play

### ISSUE THREAD

**Issue by F00RY** [emilsvennesson/script.module.inputstreamhelper#560]
My service provider has banned Ne...ix From my Technicolor tv box, download (kodi 20.3)
Install repository y.castagnait-2.0.1.zip To see my content and I get the following error
![IMG_20240303_124106](https://github.com/emilsvennesson/script.module.inputstreamhelper/assets/162046447/dd683f1e-7344-4923-8f47-dc2962a596de)

**Comment by horstle** [comment]
Please report issues with the Netflix addon to its developer:
https://github.com/CastagnaIT/plugin.video.netflix/issues
