### ISSUE TITLE
No module named 'distutils'  Libreelec Piers Nightly Build Rpi5



### ISSUE THREAD

**Issue by hbbernardo** [emilsvennesson/script.module.inputstreamhelper#567]
Since the beginning of this week I'm unable to play any title using the Netflix Addon on the latest nightly builds from Libreelec Piers on my Rpi5

An error message appears saying No module named 'distutils' and asking me to open a ticket on this GitHub

Here's the log: https://www.logpasta.com/paste/819c4662-68f1-4a00-b203-4a8a2ea32e09

Please let me know if I can be of further assistance. 

Thanks.

**Comment by emilsvennesson** [comment]
Fixed on 0.7.0.
