### ISSUE TITLE
Out of date script.module.kodi-six

### ISSUE THREAD

**Issue by Lattay** [emilsvennesson/script.module.inputstreamhelper#58]
Hello,
I cannot install this because it require version 0.0.2 of script.module.kodi-six which is noi longer available on mirrors. The current version available is 0.0.4. Since it is a minor version change it should not cause incompatibilities.

**Comment by mediaminister** [comment]
Fixed in https://github.com/emilsvennesson/script.module.inputstreamhelper/commit/3ef9010bf444d17839ec66cc2f05834e05894d68
