### ISSUE TITLE
Error after upgrading from Kodi 20.5 to 21.1 Unknown addon id 'inputstream.adaptive'

### ISSUE THREAD

**Issue by llucax** [emilsvennesson/script.module.inputstreamhelper#580]
This happens when using the Netflix addon, when I hit play on any video I guess this error:

> Input Stream Helper Add-on Error
> 
> The operation has been cancelled.
> InputStream Helper has generated an internal error:
> Unknown addon id 'inputstream.adaptive'
> 
> Please report it to InputStream Helper github.

After upgrading I got a message saying the InputStream Adaptive addon is not compatible with this version.

**Comment by horstle** [comment]
Please install the latest version of Inputstream Adaptive. If that doesn't work, please provide a full debug log.

**Comment by llucax** [comment]
Thanks for the reply. Actually the issue was that apparently Inputstream Adaptive was installed via the package system (apt) and wasn't installed after the Kodi update (also done via the package manager). Once I discovered that and installed the package everything worked again.

Thanks!
