### ISSUE TITLE
Add unit and integration tests

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#63]
Because this addon is important for a lot of Kodi functionality, we need to ensure we can rely on it to work, and keeps on working. For this we definitely need unit tests and integration tests, and run them regularly so we can prevent and report known issues before they cause issues for users.

Also, when we have unit tests and integration tests, it makes it possible to test the performance and overhead of the plugin as well.

**Comment by dagwieers** [comment]
@mediaminister Not sure how we want to do this. Do we use Mock for this, or do we reuse our testing framework from VRT NU?

**Comment by mediaminister** [comment]
I think we can reuse a subset of the VRT NU testing framework.
