### ISSUE TITLE
Access the zipped image directly to extract CDM

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#72]
There are four major issues with inputstreamhelper on ARM:
- The need for root privileges in order to mount the disk image
- The required tools and kernel capability for performing the process
- The need for 2GB of free disk space
- The time to uncompress a 600MB image on a RPi and write 2GB to an SD card

We can avoid all of this, by using FUSE to mount as a user, and using zipfs to mount the zipped image directly without the need to extract the complete image.

There is a fusepy project to create python-based fuse modules, and there is a zipfs fuse module written in python as well. Currently this enables us to access the binary without the need to uncompress the ZIP file, but it does not allow us to mount the filesystem from without this mounted ZIP file. So what we need to do is create our own extzipfs that does both in a single mount. Or alternatively, instead of mounting it, use the fuse interface to get that file directly from the zipped ext2 image.

This would save us a great deal of time as well, as we wouldn't have to write to the SD card as heavily as we do now.

**Comment by dagwieers** [comment]
In fact FAT.py from FATtools is very close to what we need already, we simply have to wrap the file accessing functions around zipfile. So even FUSE is not needed!

**Comment by dagwieers** [comment]
So apparently the ZIP file is a disk image with a GPT MBR, and various partitions, including an ext2 partition with a filesystem that stores the libwidevinecdm.so.

So our tool needs to be able to:
- access the ZIP file as a normal file (block-device)
- parse the GPT MBR to find the correct partition offset
- access the ext2 filesystem from that offset
- walk the tree to find a file by name

**Comment by dagwieers** [comment]
I have succeeded to mount a partition image using pyext2 and extract our file (with an exact path).
This does not yet:
- traverse the tree to find a file by base name
- read from a specific offset of an image
- work on a zipped image

The two last features would require changes to pyext2. Even if we cannot work directly on a zipped image, being able to extract from the image would already avoid needing to mount as root.

If we go down this path, we will be actively working with the pyext2 project and would need to release a pyext2 and a script.module.pyext2 plugin.

**Comment by dagwieers** [comment]
Uncompressing the zipped image while downloading (to save on disk space) is not an option. with python's ZipFile as it requires the ZipFile to be downloaded completely to memory first. There is no stream interface.

Having random access to the compressed Zip image will be hard as python's ZipFile has no random access interface either. So it would require a new library with an mmap() interface.

**Comment by dagwieers** [comment]
According to https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/292#issuecomment-596257643 the following script https://gist.github.com/pejobo/66d6363dcd819023e28fc05a9b44522d is able to extract the library using 7zip. This would fulfil our requirements although it is unclear how to get 7zip installed on all ARM devices...

**Comment by pejobo** [comment]
As you already noted this wont solve the needed free disc space on the device, since the script extracts the image to disk.
