### ISSUE TITLE
Communicate better to the user

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#76]
I think we can improve the communication to the user. (https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/82#issuecomment-523003862)
And show fewer pop-ups (relates to #70).

If we do this correctly, an add-on does not have to provide its own pop-up.

**Comment by dagwieers** [comment]
This relates to https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/82#issuecomment-523003862

**Comment by dagwieers** [comment]
I think this comes down to 3 major items:

- We should aim at having only a single YES/NO dialog before installing Widevine. Ideally we would have just this:

  1. Ask if the user wants to continue (give the ability to bail out)
  2. Show a progress indicator (ideally the same one for download and extraction)
  3. Show a notification on success *and* failure
  4. On failure, show an OK-dialog with the exact error, or a hint where to report issues on GitHub

   The dialog text will most likely be different depending on whether InputStream Helper was started from playing content, from another add-on or the InputStream Helper settings.

- The license acceptance dialog could be integrated in this YES/NO dialog, although that means either downloading the license upfront, or showing a link to the license, or including the (copyrighted?) license in the add-on.

- The default button is the **Cancel** button, which may give the impression that this is a dangerous or unwanted action. This may be very confusing to our users to the point that they will not continue with the installation. (I witnessed this a few times)

**Comment by michaelarnauts** [comment]
Including the license text in the addon seems like a bad idea. Google can change the license, and the new license should be displayed.
I suggest to download the license before displaying the dialog.

**Comment by dagwieers** [comment]
If we would include the license, obviously we would be monitoring for changes.

Also, today we use the license of the macOS ZIP for the ChromeOS image, so it is not like we are not already have tradeoffs here.

**Comment by mediaminister** [comment]
We can't include files from proprietary software without permission and distribute this. This is always copyright infringement.
We should do the following:
- download Widevine zip to `_temp_path`
- extract LICENSE.txt and load into memory
- show license
  - License accepted > extract Widevine zip from `_temp_path` to `ia_cdm_path`
  - License declined > cleanup `_temp_path`

**Comment by dagwieers** [comment]
@mediaminister Don't we already do this exactly like that? Only for ARM we have a problem here.

**Comment by dagwieers** [comment]
Alright, let's postpone this item and translate what we have now. As I don't see how to improve this now.
