### ISSUE TITLE
_syscmd_uname crashes InputStream Helper

### ISSUE THREAD

**Issue by basrieter** [emilsvennesson/script.module.inputstreamhelper#79]
I have some user reporting issues with Retrospect due to this error:

```20190819 20:21:26 - [CRITICAL] - plugin.py            - 562  - |   File "/home/hette/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 27, in __init__
20190819 20:21:26 - [CRITICAL] - plugin.py            - 562  - |     self._log('Platform information: {0}'.format(platform.uname()))
20190819 20:21:26 - [CRITICAL] - plugin.py            - 562  - |   File "/usr/lib/python2.7/platform.py", line 1265, in uname
20190819 20:21:26 - [CRITICAL] - plugin.py            - 562  - |     processor = _syscmd_uname('-p','')
20190819 20:21:26 - [CRITICAL] - plugin.py            - 562  - |   File "/usr/lib/python2.7/platform.py", line 1000, in _syscmd_uname
20190819 20:21:26 - [CRITICAL] - plugin.py            - 562  - |     rc = f.close()
20190819 20:21:26 - [CRITICAL] - plugin.py            - 562  - + IOError: [Errno 10] No child processes```

Full logs here: https://bitbucket.org/basrieter/xbmc-online-tv/issues/attachments/1190/basrieter/xbmc-online-tv/1566239214.65/1190/retrospect.log

**Comment by dagwieers** [comment]
I have a distinct feeling that Kodi signal handling is interfering with `platform.system()` and there is nothing we can do about it ourselves. Most likely this has been happening before but was never caught. We will have to figure out another way to do `platform.system()`.

**Comment by dagwieers** [comment]
The code is also calling platform.system() all over the place, increasing the chance of getting this issue, whereas it would be much better to store the value and use it for subsequent calls. I will fix that.

**Comment by dagwieers** [comment]
@basrieter If you have users that can reproduce this easily, can they try out #80 ?
https://github.com/dagwieers/script.module.inputstreamhelper/archive/platform-fix.zip

**Comment by basrieter** [comment]
I have asked some users: https://bitbucket.org/basrieter/xbmc-online-tv/issues/1190/npo-start-start-niet

**Comment by henkv1** [comment]
It did not fix the issue. I still get the same error:
`20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - Could not playback the url
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - | Traceback (most recent call last):
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |   File "/home/hette/.kodi/addons/plugin.video.retrospect/resources/libs/plugin.py", line 498, in play_video_item
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |     media_item = self.channelObject.process_video_item(media_item)
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |   File "/home/hette/.kodi/addons/plugin.video.retrospect/resources/libs/chn_class.py", line 425, in process_video_item
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |     return data_parser.Updater(item)
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |   File "/home/hette/.kodi/addons/plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py", line 1131, in update_video_item
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |     return self.__update_video_item(item, whatson_id)
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |   File "/home/hette/.kodi/addons/plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py", line 1262, in __update_video_item
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |     NpoStream.add_mpd_stream_from_npo(None, episode_id, part, proxy=self.proxy, live=item.isLive)
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |   File "/home/hette/.kodi/addons/plugin.video.retrospect/resources/libs/streams/npostream.py", line 115, in add_mpd_stream_from_npo
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |     manifest_update=None if not live else "full")
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |   File "/home/hette/.kodi/addons/plugin.video.retrospect/resources/libs/streams/mpd.py", line 55, in set_input_stream_addon_input
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |     if is_helper.check_inputstream():
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |   File "/home/hette/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 863, in check_inputstream
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |     return self._check_drm()
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |   File "/home/hette/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 817, in _check_drm
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |     if not self._has_widevine():
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |   File "/home/hette/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 315, in _has_widevine
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |     if system_os() == 'Android':  # widevine is built in on android
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |   File "/home/hette/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 56, in system_os
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |     system_os.name = platform.system()
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |   File "/usr/lib/python2.7/platform.py", line 1298, in system
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |     return uname()[0]
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |   File "/usr/lib/python2.7/platform.py", line 1265, in uname
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |     processor = _syscmd_uname('-p','')
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |   File "/usr/lib/python2.7/platform.py", line 1000, in _syscmd_uname
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - |     rc = f.close()
20190820 17:09:49 - [CRITICAL] - plugin.py            - 562  - + IOError: [Errno 10] No child processes
`

**Comment by dagwieers** [comment]
@henkv1 Can you elaborate on the system you are using? Architecture, OS, etc. ?

**Comment by henkv1** [comment]
Its ArchLinux ARM on raspberry pi 2
kodi-rbp 18.3-1
python2 2.7.16-1
linux 4.19.56-2-ARCH

Linux 4.19.56-2-ARCH #1 SMP PREEMPT Thu Jun 27 01:20:36 UTC 2019 armv7l GNU/Linux

uname -p gives an unknown string:
$ uname -p
unknown

**Comment by dagwieers** [comment]
@henkv1 Can you run `python -c "import platform; print platform.system()"` ?

**Comment by dagwieers** [comment]
I think I found an elegant solution to your problem.

Can you try this version of the inputstreamhelper addon? https://github.com/dagwieers/script.module.inputstreamhelper/archive/platform_system.zip

PS I would still like to see the output of the above command.

**Comment by henkv1** [comment]
$ python -c "import platform; print platform.system()"
  File "<string>", line 1
    import platform; print platform.system()
                                  ^
SyntaxError: invalid syntax

**Comment by henkv1** [comment]
$ python2 -c "import platform; print platform.system()"
Linux

**Comment by henkv1** [comment]
Thank you, the new version fixed the issue. Widevine installed without issues. 

PS there is a typo in the dutch translation: "Een update van Widevine CDM is **nodif** voor het afspelen van deze informatie."

**Comment by dagwieers** [comment]
@henkv1 Thanks, I'll fix that.

**Comment by dagwieers** [comment]
@basrieter @emilsvennesson @mediaminister We may want to release a new version of inputstreamhelper for people that suffered from this. Although I have no clear view of the scope of this problem.
