### ISSUE TITLE
libwidevinecdm now depends on nss/nspr

### ISSUE THREAD

**Issue by morajonas** [emilsvennesson/script.module.inputstreamhelper#8]
Raspberry pi3 osmc Kodi 17.5

Hi. After i tried to install the latest Viaplay addon it fails after "sudo is required to mount chrome os image". After that it sas "One or more items failed to play" What can I do to make it work?

Log: https://paste.ubuntu.com/26286106/

Med vänliga hälsningar
Jonas

**Comment by emilsvennesson** [comment]
Hi! You haven't enabled debug logging in the Kodi settings. Please submit a new log with debug logging activated.

**Comment by morajonas** [comment]
I have exceeded the maximum paste size when i try to use paste bin. Can i mail you the log-file?

**Comment by morajonas** [comment]
I cut it in half:

https://pastebin.com/jvJaKWYd

**Comment by emilsvennesson** [comment]
@morajonas  Thank you for the logs. Could you please try commenting out or removing line 181 and 182 in /.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py and try again?

Basically, remove these two lines and try again:
```python
        if 'sudo' in cmd:
            subprocess.check_output(['sudo -k'])  # reset timestamp
```

**Comment by morajonas** [comment]
Silly question, but how can i open the file. I´ve tried open it in command line with no success (Totally new at Linux and osmc). Do i need Python?

**Comment by emilsvennesson** [comment]
@morajonas You can use any text editor you'd like. Python is not needed. If you're changing the file in the terminal, the easiest option is probably by using `nano`.

`nano /path/to/file`

Press CTRL+X to save after you've made the changes.

I've come up with a solution that's probably better as well, so go to line 176 and replace `subprocess.check_output(['sudo -k']) # reset timestamp` with `subprocess.call(['sudo', '-k'])`

Python is very picky about its indentation, so make sure that you have the exact amount of spaces as the line you changed.

**Comment by emilsvennesson** [comment]
@morajonas I'm also attaching a zip file with the changes if you feel like that's easier for you. Go to add-ons -> Install from zip file, reboot OSMC after the installation and give it a new try.
[script.module.inputstreamhelper.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/1595156/script.module.inputstreamhelper.zip)

**Comment by morajonas** [comment]
I´ll try the zip file.

**Comment by morajonas** [comment]
Ok. Widevine installation was successful but after that it sas "One or more items failed to play" and nothing happens when i try to play something on Viaplay. hmmmmm

**Comment by emilsvennesson** [comment]
@morajonas A debug log is very helpful as always. :-)

**Comment by morajonas** [comment]
I´m waiting on it. The Kodi Logfile Uploader is slow :)

**Comment by morajonas** [comment]
https://pastebin.com/h0jJzNbp

**Comment by morajonas** [comment]
Thats not all the report but i hope its enough.

**Comment by emilsvennesson** [comment]
@morajonas Very strange. Maybe something got messed up when it errored out earlier. Could you try removing the cdm folders:
`sudo rm -rf /home/osmc/.kodi/cdm`
`sudo rm -rf /home/osmc/.kodi/userdata/script.module.inputstreamhelper`

**Comment by morajonas** [comment]
Sorry, but that didnt help. Du you want another debug log?

**Comment by emilsvennesson** [comment]
No, that's fine. I am going to test with a Raspberry Pi and OSMC myself as soon as I have time. I'll get back to you!

Happy New Year!

**Comment by morajonas** [comment]
Thanks for quick response and happy new year. Now its time to do creme brulee.

**Comment by emilsvennesson** [comment]
Hi @morajonas!

I had some time to test this yesterday and you're right! It seems like the binary in the latest version of Chrome OS is incompatible with inputstream.adaptive. I have contacted @peak3d, the author of inputstream.adaptive to see if this is something that is fixable.

In the mean time, hard coding an older Chrome OS build will fix the issue. You can do this by changing line 425 in `inputstreamhelper.py` to:
```python 
            self._url = 'https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_7077.134.0_daisy-skate_recovery_stable-channel_skate-mp.bin.zip'
```

Make sure to also delete the cdm folder to force a re-download of the binary (`sudo rm -rf /home/osmc/.kodi/cdm`). I'm attaching a zip file with the change as well. :-)

I hope you're feeling better!

**Comment by morajonas** [comment]
Thank you. Can I just run the zip-file or do i need to delete the cdm folder also?

The good thing about this is that i get a little noob insight in Debian.

**Comment by emilsvennesson** [comment]
@morajonas You have to delete the cdm folder as well. Haha yeah, it's a good way of learning how to do stuff.

**Comment by morajonas** [comment]
It fucking works!!!. Thank you so much for this. Your the man!

**Comment by morajonas** [comment]
Hi again. I have encountered another problem :). The channels in viaplay doesn´t work. It sas "missingvideoerror" Any idea?

**Comment by emilsvennesson** [comment]
@morajonas The git version has this fixed. You can download it from https://github.com/emilsvennesson/kodi-viaplay.

**Comment by emilsvennesson** [comment]
I've talked to @peak3d and later versions of libwidevinecdm depends on the `nss` and `nspr` libraries that is not included in OSMC by default. I have opened a ticket (https://github.com/osmc/osmc/issues/420) so this should hopefully be solved soon.

It has been included in LibreELEC already: https://github.com/LibreELEC/LibreELEC.tv/pull/1791

**Comment by emilsvennesson** [comment]
This is fixed for the upcoming version. It will download an older Widevine binary on < Kodi 18 and keep it until the user has upgraded to Kodi 18.
