### ISSUE TITLE
Lost in French TV

### ISSUE THREAD

**Issue by RasPsykk** [emilsvennesson/script.module.inputstreamhelper#9]
Hello,

thanks for your plugin, it's cool for DRM. I'm working on this website :

https://www.mycanal.fr/live/

there is three free channels and I could see something like :

https://hss-m006-live-aka-canalplus.akamaized.net/live/disk/cnews-clair-hd/hd-clair.isml/Manifest

For the key, I think it's something like that :
certificates
widevine:
"https://secure-webtv-static.canal-plus.com/widevine/cert/cert_license_widevine_com.bin"

I'm using Kodi 18, I'm looking at the code of the Sky Go addon which uses inputstreamhelper.  So if somebody can help me using it, he's welcome.

Regards

**Comment by emilsvennesson** [comment]
Hi! That manifest is Microsoft Smooth Streaming which should be supported by inputstream.adaptive. Something like this should work:

```python
import xbmc
import xbmcgui
import inputstreamhelper

def play_item():
    inputstream_helper = inputstreamhelper.Helper('ism', drm='widevine')
    stream_url = 'STREAM URL'
    if inputstream_helper.check_inputstream():
        playitem = xbmcgui.ListItem(path=stream_url)
        playitem.setProperty('inputstreamaddon', 'inputstream.adaptive')
        playitem.setProperty('inputstream.adaptive.manifest_type', 'ism')
        playitem.setProperty('inputstream.adaptive.license_type', 'com.widevine.alpha')
        playitem.setProperty('inputstream.adaptive.license_key', 'LICENSE REQUEST')
        xbmc.Player().play(item=stream_url, listitem=playitem)
```

**Comment by RasPsykk** [comment]
Hi,
Thanks for your answer, it works with the free live Tv but I have problems with finding links on the website. So I don't know if the problem comes from my code (the same as you) or from the website (token...)

So if you want to chat join me: https://discord.gg/qmH2xZX
Thanks

**Comment by dagwieers** [comment]
@RasPsykk Is your issue still relevant to you or can we close it?

**Comment by dagwieers** [comment]
Given this issue is over 18 months old and seems to be resolved (wrt. inputstreamhelper) I am going to close this. If you still have an issue, feel free to report back.
