### ISSUE TITLE
Create a test plan

### ISSUE THREAD

**Issue by dagwieers** [emilsvennesson/script.module.inputstreamhelper#90]
Since the behavior of **inputstreamhelper** differs from architecture and context, it would be good to have a list of items we would like to test for each architecture/platform. Then we can ask users/contributors to test on their platform by following those steps.

**Comment by mediaminister** [comment]
My current testing includes this:
- build zip from branch or locally checked out pull request
- install and test in different Virtual machines

1. Oracle VM VirtualBox Manager 6.0
**A. Windows 10 x64 VM**
      - test with python 2 and python 3 Kodi versions:
        -  KodiSetup-20190508-13148516-feature_python3-x64.exe
        - kodi-18.3-Leia-x64.exe

    **B. PrimeOS Android x86 VM**
      - test with Kodi from Google Play Store

2. VMWare Workstation 15 Player
 **A. LibreELEC VM**
    - test with ready-to-use `.ova` images from http://ftp.belnet.be/mirror/libreelec.tv/
       - LibreELEC 8.2.5 (Kodi 17.6): LibreELEC-Generic.x86_64-8.2.5.ova
       - LibreELEC 9.0.2 (Kodi 18.2): LibreELEC-Generic.x86_64-9.0.2.ova
       - LibreELEC 9.1.002 (Kodi 18.3): LibreELEC-Generic.x86_64-9.1.002.ova
    
**Test 1:**
This test starts from a clean Kodi install and tests if inputstreamhelper succesfully installs inputstream.adaptive and Widevine DRM without rebooting or crashing
Steps: 
  - clean install Kodi
   - open Kodi
  - enable debug logging, enable install by zip, disable auto updating add-ons
  - install latest master inputstreamhelper zip
  - install VRT NU add-on, enable debug logging, enable DRM and try to play livestream
  - open log file and report if the test fails
  - cleanup VM (remove Kodi completely after test)

**Comment by mediaminister** [comment]
It would be nice if we could test the ARM/Chrome OS workflow on a standard X86 system. Any tips to make this work are welcome.

**Comment by michaelarnauts** [comment]
Option 2 of this suggests to run it virtualised in qemu: https://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html

**Comment by dagwieers** [comment]
I moved this to the Wiki at: https://github.com/emilsvennesson/script.module.inputstreamhelper/wiki/Test-plan

This will become a work-in-progress.

I do think we need to look into automated ARM testing in Travis as well. This will not be a complete end-to-end testing in Kodi itself, but it may detect issues prematurally. For ARM testing we don't actually need ARM, we can call the exact functions for doing ARM testing and get almost complete coverage.

(Coverage reporting is another area to investigate)

**Comment by dagwieers** [comment]
Feel free to open specific issues (or PRs!) for concrete tasks/steps in the testing process. And we can discuss them on its own merits.
